### ISSUE TITLE
summarise_at and summarise_all stopped working with list when using a DBI connection

### ISSUE THREAD

**Issue by mwillumz** [tidyverse/dplyr#4400] opened 2019-05-31 21:15 UTC
I believe the issue is with DBI. I'm having the same problem w/ postgres.

```
library(dplyr)
packageVersion("dplyr")
packageVersion("DBI")
con <- DBI::dbConnect(RSQLite::SQLite(), dbname = ":memory:")

copy_to(con, iris, "iris",
        temporary = FALSE)

by_species <- tbl(con, "iris") %>%
  group_by(Species)

by_species %>%
  summarise_all(list(min_custom = min, max_custom = max))

# Source:   lazy query [?? x 9]
# Database: sqlite 3.22.0 [:memory:]
  Species Sepal.Length_mi~ Sepal.Width_min~ Petal.Length_mi~ Petal.Width_min~ Sepal.Length_ma~
  <chr>              <dbl>            <dbl>            <dbl>            <dbl>            <dbl>
1 setosa               4.3              2.3              1                0.1              5.8
2 versic~              4.9              2                3                1                7  
3 virgin~              4.9              2.2              4.5              1.4              7.9
# ... with 3 more variables: Sepal.Width_max_custom <dbl>, Petal.Length_max_custom <dbl>,
#   Petal.Width_max_custom <dbl>

by_species %>%
  summarise_all(list(min_custom = ~ min(., na.rm = TRUE), max_custom = ~ max(., na.rm = TRUE)))
 
Error in as.pairlist(list(...)) : object 'Sepal.Length' not found

by_species %>%
  summarise_at(vars(Sepal.Length), list(min_custom = ~ min(., na.rm = TRUE), max_custom = ~ max(., na.rm = TRUE)))

Error in as.pairlist(list(...)) : object 'Sepal.Length' not found
```

_Originally posted by @mwillumz in https://github.com/tidyverse/dplyr/issues/4379#issuecomment-497861487_

**Comment by romainfrancois** [comment] 2019-06-03 06:39
duplicate of #4393

**Closed by romainfrancois** 2019-06-03 06:39 UTC
