### ISSUE TITLE
Can't bind cols with custom class

### ISSUE THREAD

**Issue by LudvigOlsen** [tidyverse/dplyr#5067] opened 2020-03-29 13:36 UTC
Updated to latest `tibble` and `dplyr` dev versions.

I can't bind the columns of two tibbles when one of them has an additional custom class. This worked before updating.

Possibly related to https://github.com/tidyverse/dplyr/issues/5066 , https://github.com/r-lib/vctrs/issues/972

``` r
d1 <- tibble::tibble("a" = c(1,2,3))
d2 <- tibble::tibble("b" = c(1,2,3))
class(d2) <- c("clazz", class(d2))
class(d2)
#> [1] "clazz"      "tbl_df"     "tbl"        "data.frame"
dplyr::bind_cols(d1, d2)
#> Error: No common type for `..1` <tbl_df<>> and `..2` <clazz<>>.
```

<sup>Created on 2020-03-29 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Update: Seems to be `dplyr` related as it makes the same mistake with the CRAN version of `tibble`.

**Comment by hadley** [comment] 2020-03-29 18:28
Basically a duplicate of #5063

**Closed by hadley** 2020-03-29 18:28 UTC
