### ISSUE TITLE
`if_any` on zero-column selection yields `TRUE`

### ISSUE THREAD

**Issue by brookslogan** [tidyverse/dplyr#7059] opened 2024-07-26 23:57 UTC
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

`if_any(<zero-column selection>, .fns)` will produce `TRUE`.  This contradicts expectations from, e..g, `any()`.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem
``` r
suppressPackageStartupMessages({
  library(dplyr)
})

tbl <- tibble(
  x1 = 1:5,
  x2 = c(-1, 4, 5, 4, 1),
  y = c(1, 4, 2, 4, 9),
)

# Basic example: this seems surprising:
tbl %>% filter(if_any(c(), ~ is.na(.x)))
#> # A tibble: 5 × 3
#>      x1    x2     y
#>   <int> <dbl> <dbl>
#> 1     1    -1     1
#> 2     2     4     4
#> 3     3     5     2
#> 4     4     4     4
#> 5     5     1     9

# It seems more natural to return zero rows, like this workaround:
tbl %>% filter(!if_all(c(), ~ !is.na(.x)))
#> # A tibble: 0 × 3
#> # ℹ 3 variables: x1 <int>, x2 <dbl>, y <dbl>

# Debugging: checking what is directly output from `if_any`:
tbl %>% filter({tmp <- if_any(c(), ~ is.na(.x)); print(tmp); tmp}) %>% invisible()
#> [1] TRUE

# Less minimal, motivating example: I don't recall the original context where I
# originally encountered this. But we might imagine models where the user can
# manually specify certain variables for special treatment, or when variables
# are selected for special treatment automatically.

predict1 <- function(tbl, regular_predictors, rate_predictors, outcomes) {
  problematic_rows <- tbl %>%
    filter(if_any({{rate_predictors}}, ~ .x < 0))
  if (nrow(problematic_rows) != 0L) {
    stop(paste0(
      "Rate predictors should always be < 0; some problematic rows shown below:",
      paste(collapse = "\n", paste0("  ", capture.output(print(problematic_rows))))
    ))
  }
  return (42L)
}

# Output here is good:
predict1(tbl, x1, x2, y)
#> Error in predict1(tbl, x1, x2, y): Rate predictors should always be < 0; some problematic rows shown below:  # A tibble: 1 × 3
#>        x1    x2     y
#>     <int> <dbl> <dbl>
#>   1     1    -1     1

# Output here is bad; there shouldn't be a problem flagged:
predict1(tbl, c(x1, x2), c(), y)
#> Error in predict1(tbl, c(x1, x2), c(), y): Rate predictors should always be < 0; some problematic rows shown below:  # A tibble: 5 × 3
#>        x1    x2     y
#>     <int> <dbl> <dbl>
#>   1     1    -1     1
#>   2     2     4     4
#>   3     3     5     2
#>   4     4     4     4
#>   5     5     1     9
```

<sup>Created on 2024-07-26 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by DavisVaughan** [comment] 2024-07-27 13:12
At first glance, I'm fairly certain I agree for this reasoning alone

```r
> any()
[1] FALSE
> all()
[1] TRUE
```

**Comment by DavisVaughan** [comment] 2024-07-27 14:06
For TDD - I think the problem is here
https://github.com/tidyverse/dplyr/blob/0005f6768fa765b3bba5148711967d58b6013037/R/across.R#L637-L640

We unconditionally return `TRUE` when there are no inputs, but I think this should only be for `if_all()`. For `if_any()` I think this should return `FALSE`, in line with `any()` and `all()` as shown above.

You could create a new variable called `empty` up here where we branch based on the type of if function being used (i.e. you'd assign it `TRUE` or `FALSE`)
https://github.com/tidyverse/dplyr/blob/0005f6768fa765b3bba5148711967d58b6013037/R/across.R#L618-L624

And then return that instead of just always returning `TRUE`

Don't forget to update the comment here
https://github.com/tidyverse/dplyr/blob/0005f6768fa765b3bba5148711967d58b6013037/R/across.R#L637

And add tests with both `if_any()` and `if_all()` with no inputs

**Closed** 2024-08-15 21:07 UTC
Labels: bug, tidy-dev-day :nerd_face:, rows ↕️
