### ISSUE TITLE
Memory leak(?) in dplyr, magrittr, or one of dplyr's dependencies

### ISSUE THREAD

**Issue by HenrikBengtsson** [tidyverse/dplyr#6207] opened 2022-03-05 19:18 UTC
# Overview

Hi, when enabling GC torture, I sporadically get:

```r
Error in dplyr::mutate(., `:=`(!!targets[idx], 1)) : 
   'rho' must be an environment not promise: detected in C-level eval
```

I don't know if this happens in **dplyr**, **magrittr**, or one of the **dplyr** dependencies.

# Background

I've spent 3+ days and about ~30 hours to narrow in on a _rare_ SEGV_MAPERR segfault problem that involves dplyr, magrittr, and many more packages, resulting `*** caught segfault ***` and `address 0x559700000004, cause 'memory not mapped'` reported by R. Not all runs, but several runs also reported on `*** recursive gc invocation` (also from R).

While trying to narrow in on the problem and trimming down the code (the original code wasn't mine and was quite verbose; I noticed it while revdep check Bioconductor **mistyR**), I lost the segfault on the way, but ended up with sporadic `'rho' must be an environment not <...>: detected in C-level eval` errors:

```
  'rho' must be an environment not ...: detected in C-level eval
  'rho' must be an environment not pairlist: detected in C-level applyClosure
  'rho' must be an environment not pairlist: detected in C-level eval
  'rho' must be an environment not promise: detected in C-level applyClosure
  'rho' must be an environment not promise: detected in C-level eval
```

These only appear if I run with GC torturing, which suggests a memory leak.

My hope is that this is caused by the same underlying problem that triggers my original segfault issue.

# Reproducible example

Here's a script `crash.R` that reproduces the problem together with the `data.rds` file attached as a _fake_ ZIP file ([data.rds.zip](https://github.com/tidyverse/dplyr/files/8191297/data.rds.zip)) to please GitHub (rename `mv data.rds.zip data.rds`).

```r
## Memory leak in magrittr, or dplyr, or?
##
## Example:
## $ R --quiet --no-environ --no-init-file --no-save
## > source("crash.R")
## Run #1
## * Step A
## * Step B
##   - Step 1 of 5
##   - Step 2 of 5
## Error in dplyr::mutate(., `:=`(!!targets[idx], 1)) : 
##   'rho' must be an environment not promise: detected in C-level eval
##
## Requirements:
##   install.packages("dplyr")
##
## Reproduces on:
## * R 4.1.2 (2021-11-01; x86_64-pc-linux-gnu)
##    - RStudio Cloud; Linux Ubuntu 20.04;
##      Running R via the RStudio *Terminal*
## * R 4.1.3 RC (2022-03-02 r81842; x86_64-pc-linux-gnu)
##    - Linux Ubuntu 18.04; built from source with
##      --enable-R-shlib --enable-memory-profiling

library(magrittr)

gctorture2(20L)

for (kk in 1:10) {
  cat(sprintf("Run #%d\n", kk))
  
  cat("* Step A\n")
  targets <- letters[1:11]
  data <- readRDS("data.rds")

  cat("* Step B\n")
  res <- mapply(data, seq_along(data), FUN = function(df, idx) {
    cat(sprintf("  - Step %d of %d\n", idx, length(data)))
    data.frame(feature = targets) %>%
      dplyr::left_join(df, by = "feature") %>%
      dplyr::mutate(!!targets[idx] := 1.0)
  })
}

cat("Done\n")
```

# Example run with traceback

```r
$ R --quiet --no-environ --no-init-file --no-save
> source("crash.R")
Run #1
* Step A
* Step B
  - Step 1 of 5
Error in dplyr::mutate(., `:=`(!!targets[idx], 1)) : 
  'rho' must be an environment not pairlist: detected in C-level eval
> traceback()
8: dplyr::mutate(., `:=`(!!targets[idx], 1))
7: data.frame(feature = targets) %>% dplyr::left_join(df, by = "feature") %>% 
       dplyr::mutate(`:=`(!!targets[idx], 1)) at crash.R#39
6: (function (df, idx) 
   {
       cat(sprintf("  - Step %d of %d\n", idx, length(data)))
       data.frame(feature = targets) %>% dplyr::left_join(df, by = "feature") %>% 
           dplyr::mutate(`:=`(!!targets[idx], 1))
   })(dots[[1L]][[1L]], dots[[2L]][[1L]])
5: mapply(data, seq_along(data), FUN = function(df, idx) {
       cat(sprintf("  - Step %d of %d\n", idx, length(data)))
       data.frame(feature = targets) %>% dplyr::left_join(df, by = "feature") %>% 
           dplyr::mutate(`:=`(!!targets[idx], 1))
   }) at crash.R#37
4: eval(ei, envir)
3: eval(ei, envir)
2: withVisible(eval(ei, envir))
1: source("crash.R")
```

Sometimes it'll take more rounds to trigger the problem.

# Session info

I've reproduced this using R 4.1.2 (RStudio Cloud) and R 4.1.3 RC on Linux.  Haven't tested elsewhere.

```r
$ R --quiet --no-environ --no-init-file --no-save
> library(dplyr)
...
> sessionInfo()
R version 4.1.3 RC (2022-03-02 r81842)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 18.04.6 LTS

Matrix products: default
BLAS:   /home/hb/software/R-devel/R-4-1-branch/lib/R/lib/libRblas.so
LAPACK: /home/hb/software/R-devel/R-4-1-branch/lib/R/lib/libRlapack.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_1.0.8

loaded via a namespace (and not attached):
 [1] fansi_1.0.2      assertthat_0.2.1 utf8_1.2.2       crayon_1.5.0    
 [5] R6_2.5.1         DBI_1.1.2        lifecycle_1.0.1  magrittr_2.0.2  
 [9] pillar_1.7.0     rlang_1.0.2      cli_3.2.0        vctrs_0.3.8     
[13] generics_0.1.2   ellipsis_0.3.2   glue_1.6.2       purrr_0.3.4     
[17] compiler_4.1.3   pkgconfig_2.0.3  tidyselect_1.1.2 tibble_3.1.6    
```

**Comment by HenrikBengtsson** [comment] 2022-03-05 19:46
I had a tea and found a tad more energy to do a push on this.  I've now removed the need for the `data.rds` file, with manually create data.frame:s.  Below is an updated reproducible script.  Compared to using the `data.rds`, it now takes more iterations before the error is triggered.

```r
library(magrittr)

gctorture2(20L)

for (kk in 1:10) {
  cat(sprintf("Run #%d\n", kk))
  
  cat("* Step A\n")
  targets <- letters[1:10]
  data <- lapply(1:2, FUN = function(idx) {
    data.frame(feature = targets, imp = 1:10)
  })

  cat("* Step B\n")
  res <- mapply(data, seq_along(data), FUN = function(df, idx) {
    cat(sprintf("  - Step %d of %d\n", idx, length(data)))
    data.frame(feature = targets) %>%
      dplyr::left_join(df, by = "feature") %>%
      dplyr::mutate(!!targets[idx] := 1.0)
  })
}

cat("Done\n")
```

Example run:

```r
source("crash.R")
Run #1
* Step A
* Step B
  - Step 1 of 2
  - Step 2 of 2
Run #2
* Step A
* Step B
  - Step 1 of 2
Error in dplyr::mutate(., `:=`(!!targets[idx], 1)) : 
  'rho' must be an environment not pairlist: detected in C-level eval
>  
```

**Comment by lionel-** [comment] 2022-03-17 14:27
> I've spent 3+ days and about ~30 hours to narrow in on a rare SEGV_MAPERR segfault problem

wow that's awful, sorry for that. @DavisVaughan found the cause to be a protection issue in my magrittr code. Will be fixed shortly.

**Closed** 2022-03-17 17:29 UTC

**Comment by lionel-** [comment] 2022-03-30 08:21
magrittr 2.0.3 is on CRAN with the memory fix.
