### ISSUE TITLE
Join fails if column is lubridate period or interval

### ISSUE THREAD

**Issue by jschelbert** [tidyverse/dplyr#3766] opened 2018-08-22 15:17 UTC
When trying to join a table that contains a lubridate period or interval column I get an error. 
I know there is some work ongoing about handling period or interval columns in arrange or filter (see #3695), but I did not expect errors when the columns are not involved in any computation (except being joined to another table)...
I'd suggest that joins should be able to handle these columns unless they are specifically used for the join, i.e. when `by = period_column`.

---
Reprex:
```r
library(tidyverse)
library(lubridate)
#> 
#> Attache Paket: 'lubridate'
#> The following object is masked from 'package:base':
#> 
#>     date

df_a <- data_frame(x = 1:10, d = as.period(1:10))
df_a
#> # A tibble: 10 x 2
#>        x d           
#>    <int> <S4: Period>
#>  1     1 1S          
#>  2     2 2S          
#>  3     3 3S          
#>  4     4 4S          
#>  5     5 5S          
#>  6     6 6S          
#>  7     7 7S          
#>  8     8 8S          
#>  9     9 9S          
#> 10    10 10S

df_b <- data_frame(x = 2:8, y =LETTERS[2:8])
df_b
#> # A tibble: 7 x 2
#>       x y    
#>   <int> <chr>
#> 1     2 B    
#> 2     3 C    
#> 3     4 D    
#> 4     5 E    
#> 5     6 F    
#> 6     7 G    
#> 7     8 H

df_c <- data_frame(x = 1:10, d = as.duration(1:10))
df_c
#> # A tibble: 10 x 2
#>        x d             
#>    <int> <S4: Duration>
#>  1     1 1s            
#>  2     2 2s            
#>  3     3 3s            
#>  4     4 4s            
#>  5     5 5s            
#>  6     6 6s            
#>  7     7 7s            
#>  8     8 8s            
#>  9     9 9s            
#> 10    10 10s

df_d <- data_frame(x = 1:10, d = hm(paste("00", 1:10)))
df_d
#> # A tibble: 10 x 2
#>        x d           
#>    <int> <S4: Period>
#>  1     1 1M 0S       
#>  2     2 2M 0S       
#>  3     3 3M 0S       
#>  4     4 4M 0S       
#>  5     5 5M 0S       
#>  6     6 6M 0S       
#>  7     7 7M 0S       
#>  8     8 8M 0S       
#>  9     9 9M 0S       
#> 10    10 10M 0S

df_a %>% left_join(df_b, by = "x")
#> Error in left_join_impl(x, y, by_x, by_y, aux_x, aux_y, na_matches): Column `d` classes Period and Interval from lubridate are currently not supported.

df_c %>% left_join(df_b, by = "x")
#> # A tibble: 10 x 3
#>        x d              y    
#>    <int> <S4: Duration> <chr>
#>  1     1 1s             <NA> 
#>  2     2 2s             B    
#>  3     3 3s             C    
#>  4     4 4s             D    
#>  5     5 5s             E    
#>  6     6 6s             F    
#>  7     7 7s             G    
#>  8     8 8s             H    
#>  9     9 9s             <NA> 
#> 10    10 10s            <NA>

df_d %>% left_join(df_b, by = "x")
#> Error in left_join_impl(x, y, by_x, by_y, aux_x, aux_y, na_matches): Column `d` classes Period and Interval from lubridate are currently not supported.
```

**Comment by hadley** [comment] 2018-08-22 16:03
Duplicate of #2432

**Closed by hadley** 2018-08-22 16:03 UTC
