### ISSUE TITLE
`case_when` quietly inserts NA when not all cases are covered

### ISSUE THREAD

**Issue by mathematiguy** [tidyverse/dplyr#3545] opened 2018-04-26 06:21 UTC
Hi there,

I've noticed that `case_when`, while very useful, will insert `NA` quietly when the given cases do not cover all of the values in the column.

Is this the preferred way for the function to work? I'd prefer if it inserted NAs noisily, just in case I think that I've covered all of the cases but failed to do so. 

Another situation is when I am writing code on a bunch of sample rows to save time, then when I scale up to the full dataset I'd like it to fail noisily if there was an edge case that I failed to observe in my sample dataset.

Or more likely if I misspelled one of the cases, I'd like to know that it inserted `NA`s when I intended for all of the values to be filled in.

```r
# This code inserts NAs in the Species column, but raises no warnings
iris %>%
  mutate(Species = case_when(
    Species == "Setosa" ~ "Setosa",
    Species == "Versicolour" ~ "Versicolour"
    # Virginica not given
    )
```

Instead of no warning, I'd like some kind of warning to be raised. It might be useful if it could say how many `NA`s were inserted, but really I just want to know if any were inserted at all.

I'm happy to put in a pull request if I can get agreement that this is something that should be fixed.

Cheers

**Comment by krlmlr** [comment] 2018-04-26 08:28
Thanks. One way to solve this, which already works, is to add final clause like this:

```r
TRUE ~ { warning("Case not covered"); NA_character_ }
```

You might be able to create your own wrapper around `case_when()` to save typing.

**Comment by romainfrancois** [comment] 2018-04-28 07:46
Something like this perhaps: 

```r
noisy_case_when <- function(..., .default = NA_character_ ){ 
  case_when(..., TRUE ~ { warning("Case not covered"); .default } )
}

iris %>%
  mutate(Species = noisy_case_when(
    Species == "Setosa" ~ "Setosa",
    Species == "Versicolour" ~ "Versicolor"
    ))
```

I'll close this because what you describe is by design and we offer a way around it.

**Closed by romainfrancois** 2018-04-28 07:46 UTC

**Comment by coolbutuseless** [comment] 2018-09-06 11:04
I thought `case_when` evaluated all its RHS expressions regardless of whether or not a matching LHS was matched  (See e.g. https://github.com/tidyverse/dplyr/issues/3475)

So isn't this code **always** going to give the warning "Case not covered"?

``` r
suppressPackageStartupMessages({
  library(dplyr)
})

noisy_case_when <- function(..., .default = NA_character_ ){
  case_when(..., TRUE ~ { warning("Case not covered"); .default } )
}

iris %>%
  head(20) %>%
  mutate(
    Species = levels(Species)[Species],
    Species2 = noisy_case_when(
      Species == "setosa"      ~ "Setosa",
      Species == "versicolor"  ~ "Versicolor",
      Species == 'virginica'   ~ 'Virginica'
    )
  )

#> Warning in eval_bare(f[[3]], env): Case not covered

#>    Sepal.Length Sepal.Width Petal.Length Petal.Width Species Species2
#> 1           5.1         3.5          1.4         0.2  setosa   Setosa
#> 2           4.9         3.0          1.4         0.2  setosa   Setosa
#> 3           4.7         3.2          1.3         0.2  setosa   Setosa
#> 4           4.6         3.1          1.5         0.2  setosa   Setosa
#> 5           5.0         3.6          1.4         0.2  setosa   Setosa
#> 6           5.4         3.9          1.7         0.4  setosa   Setosa
#> 7           4.6         3.4          1.4         0.3  setosa   Setosa
#> 8           5.0         3.4          1.5         0.2  setosa   Setosa
#> 9           4.4         2.9          1.4         0.2  setosa   Setosa
#> 10          4.9         3.1          1.5         0.1  setosa   Setosa
#> 11          5.4         3.7          1.5         0.2  setosa   Setosa
#> 12          4.8         3.4          1.6         0.2  setosa   Setosa
#> 13          4.8         3.0          1.4         0.1  setosa   Setosa
#> 14          4.3         3.0          1.1         0.1  setosa   Setosa
#> 15          5.8         4.0          1.2         0.2  setosa   Setosa
#> 16          5.7         4.4          1.5         0.4  setosa   Setosa
#> 17          5.4         3.9          1.3         0.4  setosa   Setosa
#> 18          5.1         3.5          1.4         0.3  setosa   Setosa
#> 19          5.7         3.8          1.7         0.3  setosa   Setosa
#> 20          5.1         3.8          1.5         0.3  setosa   Setosa
```

Created on 2018-09-06 by the [reprex
package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by krlmlr** [comment] 2018-09-15 08:47
Unfortunately, the warning is evaluated eagerly, at least in current `master`. Tweaked docs in ae38fea3a.
