### ISSUE TITLE
Feature idea for filter and drop_na alternative

### ISSUE THREAD

**Issue by jvanlunenburg** [tidyverse/dplyr#5440] opened 2020-07-27 04:49 UTC
Previous scoped versions of the filter function allowed `any_vars` and `all_vars` aggregation logic. Now it just does the implicit equivalent of `all_vars`. Isn't it an idea to include an argument for this logic parameter in `filter` ? Default to "all" to preserve behavior, and allow "any" so users don't need to write row-wise helper functions.

E.g:

```r
filter(across(everything(), ~ !is.na(.x)), logic = "any") # Keep rows with any valid/non-NA value
```

Currently, to do the above using `across` scoping requires defining an additional rowAny function (see [here](https://stackoverflow.com/a/62829853/4627134)).

In a similar vein, since functions like `filter` and `select` expect the user to phrase the expression in terms of what they want to _keep_, it seems `drop_na` has the opposite mental approach. Wouldn't it be more consistent to have something like `complete_cases` where the user optionally selects the variable subset that needs to be complete?

E.g:

```r
df %>% complete_cases(outcome, all_of(predictor_vars)) # Drop rows our model can't use, but we don't care if other variables have NA values
```

**Comment by hadley** [comment] 2020-07-27 12:39
Duplicate of #4770

**Closed by hadley** 2020-07-27 12:39 UTC
