### ISSUE TITLE
`rename()` fails for multiple fields under sql backends

### ISSUE THREAD

**Issue by javierluraschi** [tidyverse/dplyr#3129] opened 2017-09-28 18:33 UTC
`rename()` works with one variable change...

```r
library(dplyr)
library(RSQLite)

iris_mem <- do.call("memdb_frame", iris)

rename(iris_mem, SL = Sepal.Length)
rename(iris_mem, SW = Sepal.Width)
```

but with two or more it fails...

```r
rename(iris_mem, SL = Sepal.Length, SW = Sepal.Width)
```

```
Error in names(select)[match(old_vars, vars)] <- new_vars : 
  NAs are not allowed in subscripted assignments
```

Related to https://github.com/rstudio/sparklyr/issues/1042

**Comment by JohnMount** [comment] 2017-09-29 15:21
Oddly enough it looks like `dplyr` generates a good query (so possibly fails after the query?).

``` r
suppressPackageStartupMessages(library("dplyr"))
packageVersion("dplyr")
#> [1] '0.7.4'

db <- DBI::dbConnect(RSQLite::SQLite(), 
                     ":memory:")
dL <- data.frame(x = 1, y = 2)
dR <- dplyr::copy_to(db, dL, 'dR')

dL %>%
  rename(a = x, b = y)
#>   a b
#> 1 1 2

dR %>%
  rename(a = x, b = y) %>%
  show_query()
#> <SQL>
#> SELECT `x` AS `a`, `y` AS `b`
#> FROM `dR`

DBI::dbGetQuery(db, 
                'SELECT `x` AS `a`, `y` AS `b` FROM `dR`')
#>   a b
#> 1 1 2

dR %>%
  rename(a = x, b = y)
#> Error in names(select)[match(old_vars, vars)] <- new_vars: NAs are not allowed in subscripted assignments
```

**Comment by kevinykuo** [comment] 2017-10-04 03:14
Dupe of https://github.com/tidyverse/dplyr/issues/2896

**Comment by JohnMount** [comment] 2017-10-04 14:14
If you want dupes we can go back to [`dplyr` 2776](https://github.com/tidyverse/dplyr/issues/2776#issuecomment-301475501) which threw it back in `sparklyr`'s face.

![https://github.com/tidyverse/dplyr/issues/2776#issuecomment-301475501)](https://user-images.githubusercontent.com/4275344/31180381-596215a6-a8d3-11e7-9892-57b9ed032994.png)

**Closed** 2017-10-23 15:58 UTC
