### ISSUE TITLE
Results of Postgres Count function returned as Integer64

### ISSUE THREAD

**Issue by bkkkk** [tidyverse/dplyr#3556] opened 2018-05-07 04:41 UTC
Invoking the `COUNT` function of PostgreSQL returns a dataframe with the count column having type `S3: integer64` instead of a regular integer. This data type is not aggregated correctly by dplyr verbs and cannot be plotted by ggplot2.

The reprex is a bit artificial given that it requires a backend database:

```r
sql("SELECT
        created_at,
        count(*) AS count_col
FROM some_table
GROUP BY 1") %>%
  tbl(src = my_source) %>%
  collect(n = Inf)
```
In this case `count_col` is of type `S3: integer64`.

This happens even when using dplyr verbs:

```r
tbl(my_source, "some_table") %>%
    count()
```

Prior to this, the column type would be integer which can be handled by all dplyr verb and ggplot2.

Not sure if this is a Postgres-specific issue or if it occurs in other DBs as I don't have access to MySQL, etc...

**Comment by romainfrancois** [comment] 2018-05-07 06:02
support for integer64 might happen at some point. #1092

in the meantime, maybe you force the column to be integer with an `as.integer`

**Comment by romainfrancois** [comment] 2018-05-08 06:26
I have limited visibility about database backends, let’s see what others think. I added the database label.

**Comment by hadley** [comment] 2018-05-08 14:11
Duplicate of #1092

**Closed by hadley** 2018-05-08 14:11 UTC
Labels: database
