### ISSUE TITLE
dbplyr:::db_save_query.Microsoft SQL Server fails when passed schema.

### ISSUE THREAD

**Issue by halpo** [tidyverse/dplyr#3450] opened 2018-03-20 17:31 UTC
When running a function that called db_save_query with a Microsoft SQL Server Connection using a table name with schema attached the code fails.

```r
## assuming db is the database connection, with a Examples schema already established.
# 
t1 <- copy_to(db, iris)
t2 <- copy_to(db, iris, t1, name=in_schema('Examples', 'IRIS'))
```
The will produce the error 
```
Error: <SQL> 'select * into Example.IRIS from (SELECT "Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width", "Species"
FROM "##IRIS"') Examples.IRIS
nanodbc/nonodbc.cpp:1587: 42000: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server]Incorrect syntax near '.'.
```
The SQL that is generated from the subsequent call to db_save_query is in the error above but the following code would work
```sql
select * into Example.IRIS from (SELECT "Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width", "Species"
FROM "##IRIS"') ABCDE
```
The fix is very simple if you change line 142 in  [R/db-odbc-mssql.R](https://github.com/tidyverse/dbplyr/blob/4e868ee2098341941d0560e388b0697e22ac87de/R/db-odbc-mssql.R#L142)  to read
```r
  tt_sql <- build_sql("select * into ", as.sql(name), " from (", sql, ") ", ident(random_table_name()), con = con)
```
the problem would be remedies.

**Comment by edgararuiz** [comment] 2018-04-06 15:46
Hi, I believe that this is happening because `copy_to()` defaults to creating a temp table.  Can you try overriding the argument:

`t2 <- copy_to(db, iris, t1, name=in_schema('Examples', 'IRIS'), temporary = FALSE)`

**Comment by halpo** [comment] 2018-04-12 19:12
Nope, doesn't work I try

```r
t2 <- copy_to(db, df=t1, name=in_schema('Examples', 'IRIS'), temporary=FALSE)
```
and I get 
```
Error: <SQL> 'select * into Examples.IRIS from (SELECT "Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width", "Species"
From "##IRIS") Examples.IRIS'
  nanodbc/nanodbc.cpp:1587: 42000: [Microsoft][ODBC Driver 11 for SQL Server][SQL Server] Incorrect syntax near '.'.
```
problem that I mentioned, with the same fix as I previously mentioned.   Another that might work is to sanitize the name when aliasing the sub-query.

**Comment by edgararuiz** [comment] 2018-04-12 19:16
Hi, sorry, I meant to come back and reply to this thread after posting a new article in the website: http://db.rstudio.com/best-practices/schema/#write-non-temporary-tables

I did try my suggestion, and it failed, as it did with you.  The best way to create a permanent table is by using `dbWriteTable` and `SQL`

**Comment by halpo** [comment] 2018-04-12 20:11
Did you try the tweak I suggested?  That fixes it for Microsoft SQL Server at least.

**Comment by edgararuiz** [comment] 2018-04-13 01:44
Oh, I'll check, thanks!

**Comment by hadley** [comment] 2018-05-20 14:03
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by krlmlr** [comment] 2018-06-25 11:46
Closing due to lack of reprex. If you still need help, please open a new issue in https://github.com/tidyverse/dbplyr.

**Closed by krlmlr** 2018-06-25 11:46 UTC
Labels: database, reprex
