### ISSUE TITLE
dplyr 0.7 Intermediate values in mutate calculation create issues

### ISSUE THREAD

**Issue by marcoblume** [tidyverse/dplyr#2884] opened 2017-06-19 15:17 UTC
Hi,

going from dplyr 0.5 to dplyr 0.7 introduced a problem with using variables in the same mutate.
In dplyr 0.7 using sum() on a value that is created in the same mutate brackets is causing an issue.
sum_changed_values and sum_changed_values2 are identical in dplyr0.5 but in dplyr 0.7 sum_changed_values has the wrong values.

dplyr 0.7
```r
devtools::install_version('dplyr', '0.7.0')
library(dplyr)

data_frame(values = c(0.1,0.1)) %>% 
  mutate(changed_values = values + 0.2,
         sum_changed_values = sum(changed_values)) %>% 
  mutate(sum_changed_values2 = sum(changed_values))

# A tibble: 2 x 4
  values changed_values sum_changed_values sum_changed_values2
   <dbl>          <dbl>              <dbl>               <dbl>
1    0.1            0.3      9.881313e-324                 0.6
2    0.1            0.3      9.881313e-324                 0.6
```

-- Restarting System -- 

dplyr 0.5
```r
devtools::install_version('dplyr', '0.5.0')
library(dplyr)

data_frame(values = c(0.1,0.1)) %>% 
  mutate(changed_values = values + 0.2,
         sum_changed_values = sum(changed_values)) %>% 
  mutate(sum_changed_values2 = sum(changed_values))

# A tibble: 2 x 4
  values changed_values sum_changed_values sum_changed_values2
   <dbl>          <dbl>              <dbl>               <dbl>
1    0.1            0.3                0.6                 0.6
2    0.1            0.3                0.6                 0.6
```

**Comment by mbedward** [comment] 2017-06-21 00:59
Yes, I just noticed this behaviour too. Example:

```
dat <- data.frame(x = sample(1:5, 100, rep=TRUE))

dat %>% 
  group_by(x) %>% 
  summarize(N = n()) %>% 
  mutate(p = N / sum(N)), pscaled = p / mean(p))
```

The above code gives Inf values for pscaled. Putting the pscaled expression into a separate mutate produces correct results.

**Comment by hadley** [comment] 2017-06-22 14:45
Duplicate of #2869. dplyr 0.7.1 is now on CRAN.

**Closed by hadley** 2017-06-22 14:45 UTC
