### ISSUE TITLE
n_distinct doesn't work as expected with lists

### ISSUE THREAD

**Issue by idmn** [tidyverse/dplyr#3669] opened 2018-06-13 07:56 UTC
Consider this example:
``` r
x <- list(NULL, 1, 1)
length(unique(x))    
#> [1] 2
```
But:

```r
dplyr::n_distinct(x)        
#> [1] 3
```

**Comment by krlmlr** [comment] 2018-06-25 08:47
Is this a duplicate of #2355?

**Comment by romainfrancois** [comment] 2018-06-25 08:52
It's the same problem yes.

**Closed by romainfrancois** 2018-06-25 08:52 UTC
Labels: bug :bomb:, data frame
