### ISSUE TITLE
dplyr rename_all does not work on grouped data

### ISSUE THREAD

**Issue by JohnMount** [tidyverse/dplyr#2961] opened 2017-07-12 16:17 UTC
Adding a `group_by` causes a previously working `rename_all` to fail. Example below (working then not working `rename_all`).

``` r
suppressPackageStartupMessages(library("dplyr"))
packageVersion("dplyr")
#> [1] '0.7.1.9000'

MYFN <- function(.) { gsub('"', '', ., fixed = TRUE)}
rename_all(mtcars, funs(MYFN)) %>% head()
#>                    mpg cyl disp  hp drat    wt  qsec vs am gear carb
#> Mazda RX4         21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
#> Mazda RX4 Wag     21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
#> Datsun 710        22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
#> Hornet 4 Drive    21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
#> Hornet Sportabout 18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
#> Valiant           18.1   6  225 105 2.76 3.460 20.22  1  0    3    1

dg <- group_by(mtcars, cyl, gear)
rename_all(dg, funs(MYFN))
#> Error: All arguments must be named
```

**Comment by krlmlr** [comment] 2017-07-12 18:41
Thanks, confirmed. The example is somewhat clearer with

```r
MYFN <- function(.) { gsub('a', 'u', ., fixed = TRUE)}
```

**Comment by krlmlr** [comment] 2017-07-12 21:37
Is this a duplicate of #2947?

**Comment by JohnMount** [comment] 2017-07-13 01:47
Looks like a dup to me, sorry.

**Closed** 2017-07-13 07:22 UTC
Labels: bug, data frame
