### ISSUE TITLE
Error: Can't create call to non-callable object with dplyr 0.8.0.1

### ISSUE THREAD

**Issue by zooman** [tidyverse/dplyr#4235] opened 2019-03-02 04:32 UTC
Just upgraded to 0.8.0.1, throwing an exception i find difficult to understand.  "Can't create call to non-callable object".   Code reads a json and converts to a dataframe.  Previous .7xx versions were running fine. 

---

Brief description of the problem

```r
from_kafka = '{"eventTime":1547831236883,"ticker":{"AAPL":{"lastTrade":146.92,"totalVolume":309985.0},"DBC":{"lastTrade":14.82,"totalVolume":7366.0},"JPM":{"lastTrade":99.56,"totalVolume":63695.0},"JNJ":{"lastTrade":127.21,"totalVolume":24515.0},"MRK":{"lastTrade":75.52,"totalVolume":41928.0},"PFE":{"lastTrade":42.57,"totalVolume":87949.0}}}'

row_raw <- jsonlite::fromJSON(from_kafka, flatten = T)

row_clean <- row_raw %>%
  unlist %>% 
  t %>% 
  as.data.frame(., stringsAsFalse = T) %>%  dplyr::select_if(., .predicate = !stringr::str_detect(string = names(.), pattern = "(?i)totalvolume"))
```

**Comment by yutannihilation** [comment] 2019-03-02 09:25
This seems a duplicate of #4213.

**Comment by romainfrancois** [comment] 2019-03-04 11:44
Yes, definitely a duplicate of #4213 which happens to have a simpler `reprex`.

**Closed by romainfrancois** 2019-03-04 11:44 UTC
