### ISSUE TITLE
programmatic use of case_when() does not work with mutate()

### ISSUE THREAD

**Issue by FrancoisGuillem** [tidyverse/dplyr#3936] opened 2018-10-22 15:57 UTC
I need to dynamically generate conditions to use in case_when() but it does not seem to work correctly.

---
In the ``case_when()`` documentation, there is the following example:
```r
patterns <- list(
  x %% 35 == 0 ~ "fizz buzz",
  x %% 5 == 0 ~ "fizz",
  x %% 7 == 0 ~ "buzz",
  TRUE ~ as.character(x)
)
case_when(!!!patterns)
``` 
I tried to use this syntax in a mutate call but I get a "not found" error.  I think it is a scope issue due to the fact that formulas keep reference to the environment where they were created. 

```r
mtcars %>% mutate(cg = case_when(carb <= 2 ~ "low", carb > 2  ~ "high"))
##     mpg cyl  disp  hp drat    wt  qsec vs am gear carb   cg
## 1  21.0   6 160.0 110 3.90 2.620 16.46  0  1    4    4 high
## 2  21.0   6 160.0 110 3.90 2.875 17.02  0  1    4    4 high
## ...

cases <- list(carb <= 2 ~ "low", carb > 2  ~ "high")
mtcars %>% mutate(cg = case_when(!!!cases))

## Error in mutate_impl(.data, dots) : 
##   Evaluation error: object 'carb' not found.
```

**Comment by lionel-** [comment] 2018-10-23 11:12
Duplicate of #3133.

**Comment by lionel-** [comment] 2018-10-23 11:16
In the mean time you can create the list of formulas with `exprs()` rather than `list()`. This will cause the formulas to be evaluated in the data mask, the first time they are evaluated (which is when they record the environment).

**Comment by FrancoisGuillem** [comment] 2018-10-24 09:04
Thank you for the reply.

I tried to use `exprs()` but it is not practical to dynamically generate conditions.  For instance in the previous example, we may want to use breakpoints and labels provided by a user. I have found a solution that uses `substitute()`:

```r
labels <- c("low", "mid", "high")
breaks <- c(2, 4)

cases <- lapply(seq_along(breaks), function(i) {
  substitute(carb <= breaks[i] ~ labels[i], list(i = i))
})
cases <- append(cases, substitute(TRUE ~ labels[length(labels)]))

mtcars %>% mutate(cg = case_when(!!!cases))
## => works!
```
But it only works with local data. On remote data, I get the following error:
```
Error in eval_bare(call, env) : 
  'rho' must be an environment not NULL: detected in C-level eval
```
Same error if I use `exprs()`.

**Comment by lionel-** [comment] 2018-10-24 12:19
Can you provide a reprex for the NULL environment error please?

**Comment by lionel-** [comment] 2018-10-24 12:29
By the way, here is the equivalent quasiquotation syntax:

```r
cases  <- lapply(seq_along(breaks), function(i) {
  expr(carb <= breaks[!!i] ~ labels[!!i])
})

c(cases, exprs(TRUE ~ labels[length(labels)]))
#> [[1]]
#> carb <= breaks[1L] ~ labels[1L]
#>
#> [[2]]
#> carb <= breaks[2L] ~ labels[2L]
#>
#> [[3]]
#> TRUE ~ labels[length(labels)]
```

**Comment by FrancoisGuillem** [comment] 2018-10-24 12:42
Sure, here is a sample code using RSQLite:

```r
library(RSQLite)
library(rlang)
library(dplyr)

con <- dbConnect(SQLite(), ":memory:")
dbWriteTable(con, "mtcars", mtcars)

mtcars_remote <- tbl(con, "mtcars")

# Works
labels <- c("low", "mid", "high")
breaks <- c(2, 4)

cases <- lapply(seq_along(breaks), function(i) {
  expr(carb <= breaks[i] ~ labels[i], list(i = i))
})

cases <- append(cases, expr(TRUE ~ labels[length(labels)]))

mtcars %>% mutate(cg = case_when(!!!cases))
## => works
mtcars_remote %>% mutate(cg = case_when(!!!cases))
## Error in eval_bare(call, env) : 
##   'rho' must be an environment not NULL: detected in C-level eval
```

**Comment by romainfrancois** [comment] 2018-10-26 06:30
Closing here because @lionel- is working on #3133

**Closed by romainfrancois** 2018-10-26 06:30 UTC
