### ISSUE TITLE
Problem with quosures in .funs for summarise_at 

### ISSUE THREAD

**Issue by jonathan-g** [tidyverse/dplyr#4287] opened 2019-03-17 04:11 UTC
Quosure semantics that work in the `.funs` argument to `summarise` do not work in `summarise_at`.
---

The background is using rlang unquoting to avoid a collision between a variable in the calling environment and a column with the same name in a tibble.

Using the rlang unquoting operator `!!` works when I call `summarise` but not when I call `summarise_at`. 

This code used to work for dplyr version 0.7.7. I hadn't used it since last October, and when I tried it today with dplyr 0.8.0.1, I rewrote the `.funs` expression to use `~` instead of `funs()`, and found that the code no longer worked. It does not appear, from the release notes in the subsequent versions of dplyr, that it was intended for there to be a breaking change of this nature.

``` r
library(tidyverse)
df <- tibble::tibble(year = seq(2015, 2050, 5), P = 5.0 + 2.5 * year)
year <- 2037
#
# This breaks
#
dplyr::summarise_at(df, dplyr::vars(-year), ~approx(x = year, y = ., xout = (!!year))$y)
#> Error: Column `P` must be length 1 (a summary value), not 8
#
# It works if I use the literal value
#
dplyr::summarise_at(df, dplyr::vars(-year), ~approx(x = year, y = ., xout = 2037)$y)
#> # A tibble: 1 x 1
#>       P
#>   <dbl>
#> 1 5098.
#
# The quosure works in summarise
#
dplyr::summarise(df, P = approx(x = year, y = P, xout = (!!year))$y)
#> # A tibble: 1 x 1
#>       P
#>   <dbl>
#> 1 5098.
```
---
```r
> sessionInfo()
R version 3.5.2 (2018-12-20)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 17134)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252  LC_CTYPE=English_United States.1252    LC_MONETARY=English_United States.1252 LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] reprex_0.2.1    forcats_0.4.0   stringr_1.4.0   dplyr_0.8.0.1   purrr_0.3.2     readr_1.3.1     tidyr_0.8.3     tibble_2.0.1    ggplot2_3.1.0   tidyverse_1.2.1

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0       cellranger_1.1.0 pillar_1.3.1     compiler_3.5.2   plyr_1.8.4       tools_3.5.2      packrat_0.5.0    jsonlite_1.6     lubridate_1.7.4  gtable_0.2.0    
[11] nlme_3.1-137     lattice_0.20-38  pkgconfig_2.0.2  rlang_0.3.1      cli_1.0.1        rstudioapi_0.9.0 haven_2.1.0      withr_2.1.2.9000 xml2_1.2.0       httr_1.4.0      
[21] fs_1.2.6         generics_0.0.2   hms_0.4.2        grid_3.5.2       tidyselect_0.2.5 glue_1.3.1       R6_2.4.0         readxl_1.3.1     modelr_0.1.4     magrittr_1.5    
[31] backports_1.1.3  scales_1.0.0     rvest_0.3.2      assertthat_0.2.0 colorspace_1.4-0 stringi_1.4.3    lazyeval_0.2.2   munsell_0.5.0    broom_0.5.1      crayon_1.3.4   
```

**Comment by romainfrancois** [comment] 2019-03-19 16:08
@lionel- I'm not sure I follow what happens here. 

``` r
library(tidyverse)
df <- tibble::tibble(year = seq(2015, 2050, 5), P = 5.0 + 2.5 * year)

dplyr:::manip_at
#> function(.tbl, .vars, .funs, .quo, .env, ..., .include_group_vars = FALSE) {
#>   syms <- tbl_at_syms(.tbl, .vars, .include_group_vars = .include_group_vars)
#>   funs <- as_fun_list(.funs, .quo, .env, ...)
#>   manip_apply_syms(funs, syms, .tbl)
#> }
#> <bytecode: 0x7fc55d150408>
#> <environment: namespace:dplyr>
trace(dplyr:::manip_at, tracer = quote({ print(.quo) ; print(.funs) }))
#> Tracing function "manip_at" in package "dplyr (not-exported)"
#> [1] "manip_at"

year <- 2037

df %>% 
  summarise_at(vars(-year), ~approx(x = year, y = ., xout = !!year)$y)
#> Tracing manip_at(.tbl, .vars, .funs, enquo(.funs), caller_env(), ...) on entry 
#> <quosure>
#> expr: ^~approx(x = year, y = ., xout = 2037)$y
#> env:  0x7fc55eebdec0
#> ~approx(x = year, y = ., xout = !!year)$y
#> <environment: 0x7fc55eebdec0>
#> # A tibble: 1 x 1
#>       P
#>   <dbl>
#> 1 5098.
```

So we do have `.quo` that has benefitted from unquoting of `year` ...

**Comment by lionel-** [comment] 2019-03-19 16:47
Is this a duplicate of https://github.com/tidyverse/dplyr/issues/4199?

**Comment by romainfrancois** [comment] 2019-03-20 07:53
Yes. Thanks.

**Closed by romainfrancois** 2019-03-20 07:53 UTC
Labels: bug
