### ISSUE TITLE
Feature Request: Provide option for count() output to include factor levels with 0 occurrences

### ISSUE THREAD

**Issue by philstraforelli** [tidyverse/dplyr#3033] opened 2017-08-17 21:40 UTC
It would be nice if there was an option with `count()` that would allow the inclusion of factor levels without occurrences. This would be helpful for instance when building a Shiny app and an end user selects a filtered dataset that reduces a certain factor level count down to 0, creating an error downstream.

```r
library(forcats)
iris_new <- iris
iris_new$Species <- fct_expand(iris_new$Species, "A new species!")

levels(iris_new$Species)
[1] "setosa"       "versicolor"   "virginica"    "A new species!"

count(iris_new, Species)
```

The output ends up:

```r
# A tibble: 3 x 2
     Species     n
      <fctr> <int>
1     setosa    50
2 versicolor    50
3  virginica    50
```

But it would be nice if there was an option that would result in this:

```r
# A tibble: 4 x 2
     Species     n
      <fctr> <int>
1     setosa      50
2 versicolor      50
3  virginica      50
4  A new species! 0
```

**Comment by bschneidr** [comment] 2017-08-18 15:41
This would be great if I could type something like this:

```r
count(iris_new, Species, .fct_complete = TRUE)
```
instead of this:
```r
library(tidyr)

count(iris_new, Species) %>% 
    complete(Species, fill = list(n = 0L))
```

Also, while I know `forcats` has a sort of prototypical version of this with `fct_count(f = iris_new$Species)`, it seems like using an argument to `dplyr::count()` is more natural than trying to fit `forcats::fct_count()` into the middle of a chain of `dplyr` verbs such as `select()`, `filter()`, etc.

**Comment by philstraforelli** [comment] 2017-08-18 16:21
Fully agree. `fct_count` is a good idea that could be better executed - to me it betrays a bit the `tidyverse` concept of creating an output that is the same as the input (from vector to vector, from tibble to tibble, etc.). Unlike other functions, it takes a vector as an input to create a tibble as output.

**Comment by krlmlr** [comment] 2017-08-22 08:36
Is this a duplicate of #341?

**Comment by philstraforelli** [comment] 2017-08-22 13:50
@krlmlr yes it is. I did look around before opening this issue but evidently didn't use the right words to search.

_Sent from my Google Pixel using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Closed** 2017-08-23 13:18 UTC
