### ISSUE TITLE
Spurious warnings about many-to-many joins

### ISSUE THREAD

**Issue by tomwagstaff-opml** [tidyverse/dplyr#6969] opened 2023-11-21 18:46 UTC
I've noticed recently that dplyr gives warnings when joins result in many-to-many relationships and this hasn't been explicitly noted. This is helpful, but I seem to be getting spurious warnings when the relationships are actually unique.

I'm afraid I can't provide a reprex of the case I'm working on, but my code is in the form

```r
dataset1 %>%
    left_join(dataset2, by = c("a", "b1" = "b2") )
```

It seems like in this case the second column(s) to match on are being ignored when the warning is generated.

**Comment by DavisVaughan** [comment] 2023-11-21 19:20
What version of dplyr are you using? This got dramatically less annoying with dplyr 1.1.1

> this hasn't been explicitly noted

There are many NEWS bullets about this

In our testing this has been working as expected, so we would need a full reprex at this point to see if anything is wrong

**Comment by tomwagstaff-opml** [comment] 2023-11-22 11:01
I'm using dplyr 1.1.3

When I say not explicitly noted, I mean by setting the `relationship` parameter within the join function.

As I said, I'm afraid I can't share the example I'm working on - I've just traced through the examples and found they are in fact unique matches.

**Comment by DavisVaughan** [comment] 2023-11-22 11:24
There is nothing I can do without an example, sorry.

**Comment by tomwagstaff-opml** [comment] 2023-11-22 18:58
I'm afraid I can't reproduce it with a trivial example either. This is closer to my situation, but runs fine:

```
x <- tibble(
  a = c(1, 1, 2, 2),
  b = c(1, 2, 1, 2)
)

y <- rename(x, c = b)

inner_join(x, y, by = c("a", "b" = "c"))
```

Hopefully someone in a position to share their data and code will turn up the same issue.

**Comment by DavisVaughan** [comment] 2023-11-22 21:47
@tomwagstaff-opml thanks for trying it out on your computer too!

Since there currently isn't anything actionable on our end, I am going to close this. But we do want to help, so please feel free to open another issue if you can find a reproducible example that isn't working as expected, thanks!

**Closed by DavisVaughan** 2023-11-22 21:47 UTC
