### ISSUE TITLE
mutate_at with numerical column names

### ISSUE THREAD

**Issue by bs538** [tidyverse/dplyr#4925] opened 2020-03-03 17:22 UTC
mutate_at() does not yield the expected results when applied to a tibble where column names are numerical.

```r
dummy <- 
  tibble(year = rep(2001:2005,2), value = 1:10, variable = c(rep("var1",5),rep("var2",5))) %>%
  spread(year, value)

# subtract 2002 value from all columns - unexpected behaviour
 dummy %>% 
  mutate_at(vars(starts_with("20")), ~ . - `2002`)

# workaround that produces what I would expect the above to do
dummy %>% 
  mutate(baseyr = `2002`) %>% 
  mutate_at(vars(starts_with("20")), ~ . - baseyr) %>% 
  select(-baseyr)
```

**Comment by hadley** [comment] 2020-03-03 19:30
The problem is unrelated to the names of the variables; it's because `mutate_at()` updates the columns sequentially, so after it's been mutated 2002 equal 0.  This is resolved by `across()` which will supersede `mutate_at()` and friends in dplyr 1.0.0:

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(var = 1, `2001` = 1, `2002` = 2, `2003` = 3)

df <- tibble(year = rep(2001:2005,2), value = 1:10, variable = c(rep("var1",5),rep("var2",5))) %>%
  tidyr::spread(year, value)

df %>% 
  mutate(across(starts_with("20"), ~ . - `2002`))
#> # A tibble: 2 x 6
#>   variable `2001` `2002` `2003` `2004` `2005`
#>   <chr>     <int>  <int>  <int>  <int>  <int>
#> 1 var1         -1      0      1      2      3
#> 2 var2         -1      0      1      2      3
```

<sup>Created on 2020-03-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Closed by hadley** 2020-03-03 19:30 UTC
