### ISSUE TITLE
bind_rows() warning messages with glue

### ISSUE THREAD

**Issue by william3031** [tidyverse/dplyr#5247] opened 2020-05-15 02:05 UTC
I think this is similar to this issue, which seems unresolved: https://github.com/tidyverse/dplyr/issues/2688

When binding these datasets, the warning message appears. It isn't so bad in the reprex below, but with real data, sometimes it is repeated over and over.

Like mentioned in the original issue, it would be good to be able to suppress these messages without wrapping the whole thing in `suppressWarnings()`.

I have the latest versions of `dplyr` and `glue` (as well as `vctrs` mentioned in the old post).

```r
library(tidyverse)
library(glue)

iris1 <- iris %>% 
  slice(1:100) %>% 
  count(Species) %>% 
  mutate(text = glue("{Species} (n = {n})")) %>% 
  as_tibble()

iris2 <- iris %>% 
  slice(101:150) %>% 
  count(Species) %>% 
  mutate(text = glue("{Species} (n = {n})")) %>% 
  as_tibble()

bind_rows(iris1, iris2)
```
> Warning messages:
> 1: In bind_rows_(x, .id) :
>  Vectorizing 'glue' elements may not preserve their attributes
> 2: In bind_rows_(x, .id) :
>  Vectorizing 'glue' elements may not preserve their attributes

**Comment by romainfrancois** [comment] 2020-05-15 09:53
I cannot reproduce the problem locally: 

``` r
library(dplyr, warn.conflicts = FALSE)
library(glue)

# so that warnings are promoted to errors
options(warn = 2)

iris1 <- iris %>% 
  slice(1:100) %>% 
  count(Species) %>% 
  mutate(text = glue("{Species} (n = {n})")) %>% 
  as_tibble()

iris2 <- iris %>% 
  slice(101:150) %>% 
  count(Species) %>% 
  mutate(text = glue("{Species} (n = {n})")) %>% 
  as_tibble()

bind_rows(iris1, iris2)
#> # A tibble: 3 x 3
#>   Species        n text               
#>   <fct>      <int> <glue>             
#> 1 setosa        50 setosa (n = 50)    
#> 2 versicolor    50 versicolor (n = 50)
#> 3 virginica     50 virginica (n = 50)
```

<sup>Created on 2020-05-15 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 4.0.0 (2020-04-24)
#>  os       macOS Mojave 10.14.6        
#>  system   x86_64, darwin17.0          
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       Europe/Paris                
#>  date     2020-05-15                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version     date       lib source                        
#>  assertthat    0.2.1       2019-03-21 [1] CRAN (R 4.0.0)                
#>  backports     1.1.7       2020-05-13 [1] CRAN (R 4.0.0)                
#>  callr         3.4.3       2020-03-28 [1] CRAN (R 4.0.0)                
#>  cli           2.0.2       2020-02-28 [1] CRAN (R 4.0.0)                
#>  crayon        1.3.4.9000  2020-04-27 [1] Github (r-lib/crayon@dcf6d44) 
#>  desc          1.2.0       2018-05-01 [1] CRAN (R 4.0.0)                
#>  devtools      2.3.0       2020-04-10 [1] CRAN (R 4.0.0)                
#>  digest        0.6.25      2020-02-23 [1] CRAN (R 4.0.0)                
#>  dplyr       * 0.8.99.9003 2020-05-15 [1] local                         
#>  ellipsis      0.3.0       2019-09-20 [1] CRAN (R 4.0.0)                
#>  evaluate      0.14        2019-05-28 [1] CRAN (R 4.0.0)                
#>  fansi         0.4.1       2020-01-08 [1] CRAN (R 4.0.0)                
#>  fs            1.4.1       2020-04-04 [1] CRAN (R 4.0.0)                
#>  generics      0.0.2       2018-11-29 [1] CRAN (R 4.0.0)                
#>  glue        * 1.4.1       2020-05-13 [1] CRAN (R 4.0.0)                
#>  highr         0.8         2019-03-20 [1] CRAN (R 4.0.0)                
#>  htmltools     0.4.0       2019-10-04 [1] CRAN (R 4.0.0)                
#>  knitr         1.28        2020-02-06 [1] CRAN (R 4.0.0)                
#>  lifecycle     0.2.0       2020-03-06 [1] CRAN (R 4.0.0)                
#>  magrittr      1.5         2014-11-22 [1] CRAN (R 4.0.0)                
#>  memoise       1.1.0       2017-04-21 [1] CRAN (R 4.0.0)                
#>  pillar        1.4.4       2020-05-05 [1] CRAN (R 4.0.0)                
#>  pkgbuild      1.0.8       2020-05-07 [1] CRAN (R 4.0.0)                
#>  pkgconfig     2.0.3       2019-09-22 [1] CRAN (R 4.0.0)                
#>  pkgload       1.0.2       2018-10-29 [1] CRAN (R 4.0.0)                
#>  prettyunits   1.1.1       2020-01-24 [1] CRAN (R 4.0.0)                
#>  processx      3.4.2       2020-02-09 [1] CRAN (R 4.0.0)                
#>  ps            1.3.3       2020-05-08 [1] CRAN (R 4.0.0)                
#>  purrr         0.3.4       2020-04-17 [1] CRAN (R 4.0.0)                
#>  R6            2.4.1       2019-11-12 [1] CRAN (R 4.0.0)                
#>  Rcpp          1.0.4.6     2020-04-09 [1] CRAN (R 4.0.0)                
#>  remotes       2.1.1       2020-02-15 [1] CRAN (R 4.0.0)                
#>  rlang         0.4.6       2020-05-02 [1] CRAN (R 4.0.0)                
#>  rmarkdown     2.1         2020-01-20 [1] CRAN (R 4.0.0)                
#>  rprojroot     1.3-2       2018-01-03 [1] CRAN (R 4.0.0)                
#>  sessioninfo   1.1.1       2018-11-05 [1] CRAN (R 4.0.0)                
#>  stringi       1.4.6       2020-02-17 [1] CRAN (R 4.0.0)                
#>  stringr       1.4.0       2019-02-10 [1] CRAN (R 4.0.0)                
#>  testthat      2.3.2       2020-03-02 [1] CRAN (R 4.0.0)                
#>  tibble        3.0.1       2020-04-20 [1] CRAN (R 4.0.0)                
#>  tidyselect    1.1.0       2020-05-11 [1] CRAN (R 4.0.0)                
#>  usethis       1.6.1.9000  2020-05-11 [1] Github (r-lib/usethis@5186836)
#>  utf8          1.1.4       2018-05-24 [1] CRAN (R 4.0.0)                
#>  vctrs         0.3.0       2020-05-11 [1] CRAN (R 4.0.0)                
#>  withr         2.2.0       2020-04-20 [1] CRAN (R 4.0.0)                
#>  xfun          0.13        2020-04-13 [1] CRAN (R 4.0.0)                
#>  yaml          2.2.1       2020-02-01 [1] CRAN (R 4.0.0)                
#> 
#> [1] /Users/romainfrancois/.R/library/4.0
#> [2] /Library/Frameworks/R.framework/Versions/4.0/Resources/library
```

</details>

**Comment by william3031** [comment] 2020-05-15 10:06
Thanks for looking in to it Romain.

I have copied your code and still have the issue, though it is an error message (probably  because of the `options(warn=2)`).

>Error in bind_rows_(x, .id) : 
> (converted from warning) Vectorizing 'glue' elements may not preserve their attributes

My session info:

```
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=English_Australia.1252  LC_CTYPE=English_Australia.1252    LC_MONETARY=English_Australia.1252
[4] LC_NUMERIC=C                       LC_TIME=English_Australia.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] glue_1.4.0  dplyr_0.8.5

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6     fansi_0.4.1      crayon_1.3.4     assertthat_0.2.1 R6_2.4.1         lifecycle_0.2.0 
 [7] pacman_0.5.1     magrittr_1.5     pillar_1.4.3     rlang_0.4.5      cli_2.0.2        rstudioapi_0.11 
[13] vctrs_0.2.4      ellipsis_0.3.0   tools_3.6.3      purrr_0.3.3      yaml_2.2.1       compiler_3.6.3  
[19] pkgconfig_2.0.3  tidyselect_1.0.0 tibble_3.0.0    
```

**Comment by hadley** [comment] 2020-05-15 12:10
This is fixed in the dev version.

**Closed by hadley** 2020-05-15 12:10 UTC
