### ISSUE TITLE
dplyr does not appear to have hybrid eval on database sources

### ISSUE THREAD

**Issue by JohnMount** [tidyverse/dplyr#3149] opened 2017-10-19 16:45 UTC
The `show_query()` results below make we wonder if `dplyr` still has hybrid eval active on database sources.

``` r
suppressPackageStartupMessages(library("dplyr"))
packageVersion("dplyr")
#> [1] '0.7.4'
suppressPackageStartupMessages(library("sparklyr"))
packageVersion("sparklyr")
#> [1] '0.6.3'

d <- data.frame(x = 1:2)
small <- 1

# SQLite example

my_db <- dplyr::src_sqlite(":memory:", create = TRUE)
# or can connect with:
# my_db <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
# RSQLite::initExtension(my_db) # needed for many summary fns.

dSQLite <- copy_to(my_db, d, 'dSQLite')

# SQLite example

# under hybrid eval
# should not the following be:
#   SELECT `x`, 2.0 AS `z` FROM `dSQLite`
dSQLite %>% mutate(z = sqrt(4)) %>% show_query()
#> <SQL>
#> SELECT `x`, SQRT(4.0) AS `z`
#> FROM `dSQLite`


# Spark example

sc <- sparklyr::spark_connect(version='2.0.2', 
                              master = "local")
dSpark <- copy_to(sc, d, 'dSpark')

# under hybrid eval
# should not the following be:
#    SELECT `x`, 2.0 AS `z` FROM `dSpark`
dSpark %>% mutate(z = sqrt(4)) %>% show_query()
#> <SQL>
#> SELECT `x`, SQRT(4.0) AS `z`
#> FROM `dSpark`

spark_disconnect(sc)
```

**Comment by hadley** [comment] 2017-10-23 15:01
Possible duplicate of #3084

**Comment by hadley** [comment] 2017-10-23 22:21
You need to specifically request that evaluation of expressions happens locally. It's only local variables that are translated automatically.

``` r
library(dplyr, warn.conflicts = FALSE)
library(dbplyr, warn.conflicts = FALSE)

db <- memdb_frame(x = 1:2)

db %>% mutate(z = sqrt(4)) %>% show_query()
#> <SQL>
#> SELECT `x`, SQRT(4.0) AS `z`
#> FROM `wphlajtjqx`
db %>% mutate(z = local(sqrt(4))) %>% show_query()
#> <SQL>
#> SELECT `x`, 2.0 AS `z`
#> FROM `wphlajtjqx`
```

**Closed by hadley** 2017-10-23 22:21 UTC
Labels: bug, database
