### ISSUE TITLE
rename_at does work with SQLite

### ISSUE THREAD

**Issue by shntnu** [tidyverse/dplyr#3132] opened 2017-10-03 13:50 UTC
``` r
library(magrittr)

db <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")

data <- dplyr::copy_to(db, iris)

data %>% dplyr::rename_at(c("Sepal.Width"), toupper)
#> # Source:   lazy query [?? x 5]
#> # Database: sqlite 3.19.3 [:memory:]
#>    Sepal.Length SEPAL.WIDTH Petal.Length Petal.Width Species
#>           <dbl>       <dbl>        <dbl>       <dbl>   <chr>
#>  1          5.1         3.5          1.4         0.2  setosa
#>  2          4.9         3.0          1.4         0.2  setosa
#>  3          4.7         3.2          1.3         0.2  setosa
#>  4          4.6         3.1          1.5         0.2  setosa
#>  5          5.0         3.6          1.4         0.2  setosa
#>  6          5.4         3.9          1.7         0.4  setosa
#>  7          4.6         3.4          1.4         0.3  setosa
#>  8          5.0         3.4          1.5         0.2  setosa
#>  9          4.4         2.9          1.4         0.2  setosa
#> 10          4.9         3.1          1.5         0.1  setosa
#> # ... with more rows

data %>% dplyr::collect() %>% dplyr::rename_at(c("Sepal.Length", "Sepal.Width"), toupper)
#> # A tibble: 150 x 5
#>    SEPAL.LENGTH SEPAL.WIDTH Petal.Length Petal.Width Species
#>           <dbl>       <dbl>        <dbl>       <dbl>   <chr>
#>  1          5.1         3.5          1.4         0.2  setosa
#>  2          4.9         3.0          1.4         0.2  setosa
#>  3          4.7         3.2          1.3         0.2  setosa
#>  4          4.6         3.1          1.5         0.2  setosa
#>  5          5.0         3.6          1.4         0.2  setosa
#>  6          5.4         3.9          1.7         0.4  setosa
#>  7          4.6         3.4          1.4         0.3  setosa
#>  8          5.0         3.4          1.5         0.2  setosa
#>  9          4.4         2.9          1.4         0.2  setosa
#> 10          4.9         3.1          1.5         0.1  setosa
#> # ... with 140 more rows

data %>% dplyr::rename_at(c("Sepal.Length", "Sepal.Width"), toupper)
#> Error in names(select)[match(old_vars, vars)] <- new_vars: NAs are not allowed in subscripted assignments

DBI::dbDisconnect(db)
```

<details><summary>Session info</summary>

``` r
devtools::session_info()
#> Session info -------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.4.1 (2017-06-30)
#>  system   x86_64, darwin15.6.0        
#>  ui       unknown                     
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  tz       America/New_York            
#>  date     2017-10-03
#> Packages -----------------------------------------------------------------
#>  package    * version    date       source                          
#>  assertthat   0.2.0      2017-04-11 cran (@0.2.0)                   
#>  backports    1.1.0      2017-05-22 cran (@1.1.0)                   
#>  base       * 3.4.1      2017-08-18 local                           
#>  bindr        0.1        2016-11-13 cran (@0.1)                     
#>  bindrcpp     0.2        2017-06-17 cran (@0.2)                     
#>  bit          1.1-12     2014-04-09 cran (@1.1-12)                  
#>  bit64        0.9-7      2017-05-08 cran (@0.9-7)                   
#>  blob         1.1.0      2017-06-17 cran (@1.1.0)                   
#>  compiler     3.4.1      2017-08-18 local                           
#>  datasets   * 3.4.1      2017-08-18 local                           
#>  DBI          0.7        2017-06-18 cran (@0.7)                     
#>  dbplyr       1.1.0      2017-06-27 cran (@1.1.0)                   
#>  devtools     1.13.3     2017-08-02 CRAN (R 3.4.1)                  
#>  digest       0.6.12     2017-01-27 CRAN (R 3.4.1)                  
#>  dplyr        0.7.3      2017-09-09 cran (@0.7.3)                   
#>  evaluate     0.10.1     2017-06-24 cran (@0.10.1)                  
#>  glue         1.1.1      2017-06-21 cran (@1.1.1)                   
#>  graphics   * 3.4.1      2017-08-18 local                           
#>  grDevices  * 3.4.1      2017-08-18 local                           
#>  htmltools    0.3.6      2017-04-28 cran (@0.3.6)                   
#>  knitr        1.17       2017-08-10 cran (@1.17)                    
#>  magrittr   * 1.5        2014-11-22 cran (@1.5)                     
#>  memoise      1.1.0      2017-04-21 CRAN (R 3.4.1)                  
#>  methods    * 3.4.1      2017-08-18 local                           
#>  pkgconfig    2.0.1      2017-03-21 cran (@2.0.1)                   
#>  R6           2.2.2      2017-06-17 CRAN (R 3.4.1)                  
#>  Rcpp         0.12.12    2017-07-15 cran (@0.12.12)                 
#>  rlang        0.1.2.9000 2017-09-27 Github (tidyverse/rlang@c6b038f)
#>  rmarkdown    1.6        2017-06-15 cran (@1.6)                     
#>  rprojroot    1.2        2017-01-16 cran (@1.2)                     
#>  RSQLite      2.0        2017-06-19 cran (@2.0)                     
#>  stats      * 3.4.1      2017-08-18 local                           
#>  stringi      1.1.5      2017-04-07 cran (@1.1.5)                   
#>  stringr      1.2.0      2017-02-18 cran (@1.2.0)                   
#>  tibble       1.3.4      2017-08-22 cran (@1.3.4)                   
#>  tools        3.4.1      2017-08-18 local                           
#>  utils      * 3.4.1      2017-08-18 local                           
#>  withr        2.0.0      2017-07-28 CRAN (R 3.4.1)                  
#>  yaml         2.1.14     2016-11-12 cran (@2.1.14)
```

</details>

**Comment by EdwardJRoss** [comment] 2017-10-10 20:53
This looks like a duplicate of #2860, which from the comments sounds like is (being?) solved in #2956.

**Closed** 2017-10-23 15:56 UTC
