### ISSUE TITLE
transmute (and friends) don't like matrices (yet)

### ISSUE THREAD

**Issue by maxheld83** [tidyverse/dplyr#3777] opened 2018-08-27 20:26 UTC
part of #3630 

```
df <- tibble::tibble(m = matrix(1:4, nrow = 2), v = 5:6)
dplyr::transmute(df, v = v * 2)
# works
dplyr::transmute(df, m = m * 2)
# > Error: Evaluation error: Attempt to query lazy column with non-natural slicing index.
```

----

```
# > devtools::session_info()
Session info ---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.5.1 (2018-07-02)
 system   x86_64, darwin15.6.0        
 ui       RStudio (1.1.456)           
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       Europe/Berlin               
 date     2018-08-27                  

Packages -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 package      * version     date       source                            
 assertthat     0.2.0       2017-04-11 CRAN (R 3.5.0)                    
 backports      1.1.2       2017-12-13 CRAN (R 3.5.0)                    
 base         * 3.5.1       2018-07-05 local                             
 bindr          0.1.1       2018-03-13 CRAN (R 3.5.0)                    
 bindrcpp     * 0.2.2       2018-03-29 CRAN (R 3.5.0)                    
 broom          0.5.0       2018-07-17 CRAN (R 3.5.0)                    
 cellranger     1.1.0       2016-07-27 CRAN (R 3.5.0)                    
 checkmate      1.8.5       2017-10-24 CRAN (R 3.5.0)                    
 cli            1.0.0       2017-11-05 CRAN (R 3.5.0)                    
 colorspace     1.3-2       2016-12-14 CRAN (R 3.5.0)                    
 compiler       3.5.1       2018-07-05 local                             
 crayon         1.3.4       2017-09-16 CRAN (R 3.5.0)                    
 data.table     1.11.4      2018-05-27 CRAN (R 3.5.0)                    
 datasets     * 3.5.1       2018-07-05 local                             
 devtools       1.13.6      2018-06-27 CRAN (R 3.5.0)                    
 digest         0.6.16      2018-08-22 CRAN (R 3.5.0)                    
 dplyr        * 0.7.99.9000 2018-08-27 Github (tidyverse/dplyr@a428a81)  
 evaluate       0.11        2018-07-17 CRAN (R 3.5.0)                    
 fansi          0.3.0       2018-08-13 CRAN (R 3.5.1)                    
 filehash       2.4-1       2017-04-07 cran (@2.4-1)                     
 forcats      * 0.3.0       2018-02-19 CRAN (R 3.5.0)                    
 foreign        0.8-71      2018-07-20 CRAN (R 3.5.0)                    
 fs             1.2.6       2018-08-23 CRAN (R 3.5.1)                    
 ggplot2      * 3.0.0       2018-07-03 CRAN (R 3.5.0)                    
 glue           1.3.0       2018-08-27 Github (tidyverse/glue@4e74901)   
 GPArotation    2014.11-1   2014-11-25 cran (@2014.11)                   
 graphics     * 3.5.1       2018-07-05 local                             
 grDevices    * 3.5.1       2018-07-05 local                             
 grid           3.5.1       2018-07-05 local                             
 gridExtra      2.3         2017-09-09 CRAN (R 3.5.0)                    
 gtable         0.2.0       2016-02-26 CRAN (R 3.5.0)                    
 haven          1.1.2       2018-06-27 CRAN (R 3.5.0)                    
 hms            0.4.2       2018-03-10 CRAN (R 3.5.0)                    
 htmltools      0.3.6       2017-04-28 CRAN (R 3.5.0)                    
 httr           1.3.1       2017-08-20 CRAN (R 3.5.0)                    
 jsonlite       1.5         2017-06-01 CRAN (R 3.5.0)                    
 knitr        * 1.20        2018-02-20 CRAN (R 3.5.0)                    
 koRpus         0.10-2      2017-04-04 cran (@0.10-2)                    
 lattice        0.20-35     2017-03-25 CRAN (R 3.5.1)                    
 lazyeval       0.2.1       2017-10-29 cran (@0.2.1)                     
 lubridate      1.7.4       2018-04-11 CRAN (R 3.5.0)                    
 magrittr     * 1.5         2014-11-22 CRAN (R 3.5.0)                    
 MASS           7.3-50      2018-04-30 CRAN (R 3.5.1)                    
 memoise        1.1.0       2017-04-21 CRAN (R 3.5.0)                    
 methods      * 3.5.1       2018-07-05 local                             
 mnormt         1.5-5       2016-10-15 CRAN (R 3.5.0)                    
 modelr         0.1.2       2018-05-11 CRAN (R 3.5.0)                    
 munsell        0.5.0       2018-06-12 CRAN (R 3.5.0)                    
 nFactors       2.3.3       2011-12-20 cran (@2.3.3)                     
 nlme           3.1-137     2018-04-07 CRAN (R 3.5.1)                    
 parallel       3.5.1       2018-07-05 local                             
 paran          1.5.1       2012-09-10 cran (@1.5.1)                     
 pensieve     * 0.0.0.9022  2018-08-27 local                             
 pillar         1.3.0.9000  2018-08-21 Github (r-lib/pillar@3fabb4e)     
 pkgconfig      2.0.2       2018-08-16 cran (@2.0.2)                     
 plyr           1.8.4       2016-06-08 CRAN (R 3.5.0)                    
 psych          1.8.4       2018-05-06 CRAN (R 3.5.0)                    
 purrr        * 0.2.4.9000  2018-08-27 Github (tidyverse/purrr@07bdea2)  
 qmethod        1.5.9003    2018-06-30 Github (maxheld83/qmethod@d85ad64)
 R6             2.2.2       2017-06-17 CRAN (R 3.5.0)                    
 RColorBrewer   1.1-2       2014-12-07 CRAN (R 3.5.0)                    
 Rcpp           0.12.18     2018-07-23 CRAN (R 3.5.0)                    
 readr        * 1.1.1       2017-05-16 CRAN (R 3.5.0)                    
 readxl         1.1.0       2018-04-20 CRAN (R 3.5.0)                    
 rematch        1.0.1       2016-04-21 CRAN (R 3.5.0)                    
 reshape2       1.4.3       2017-12-11 CRAN (R 3.5.0)                    
 rlang          0.2.2.9000  2018-08-27 Github (r-lib/rlang@048262d)      
 rmarkdown    * 1.10        2018-06-11 CRAN (R 3.5.0)                    
 rprojroot      1.3-2       2018-01-03 CRAN (R 3.5.0)                    
 rsconnect      0.8.8       2018-03-09 CRAN (R 3.5.0)                    
 rstudioapi     0.7         2017-09-07 CRAN (R 3.5.0)                    
 rvest          0.3.2       2016-06-17 CRAN (R 3.5.0)                    
 scales         1.0.0       2018-08-09 CRAN (R 3.5.0)                    
 stats        * 3.5.1       2018-07-05 local                             
 stringi        1.2.4       2018-07-20 CRAN (R 3.5.0)                    
 stringr      * 1.3.1       2018-05-10 CRAN (R 3.5.0)                    
 tibble       * 1.4.99.9003 2018-08-24 local                             
 tidyr        * 0.8.1       2018-05-18 CRAN (R 3.5.0)                    
 tidyselect     0.2.4       2018-02-26 CRAN (R 3.5.0)                    
 tidyverse    * 1.2.1       2017-11-14 CRAN (R 3.5.0)                    
 tikzDevice     0.12        2018-07-02 CRAN (R 3.5.0)                    
 tools          3.5.1       2018-07-05 local                             
 utf8           1.1.4       2018-05-24 CRAN (R 3.5.0)                    
 utils        * 3.5.1       2018-07-05 local                             
 withr          2.1.2       2018-03-15 CRAN (R 3.5.0)                    
 xml2           1.2.0       2018-01-24 CRAN (R 3.5.0)                    
 xtable         1.8-2       2016-02-05 CRAN (R 3.5.0)                    
 yaml           2.2.0       2018-07-25 CRAN (R 3.5.0) 
```

**Comment by hadley** [comment] 2018-10-01 19:09
I think this is a duplicate of #3630?

**Closed by hadley** 2018-10-01 19:09 UTC
