### ISSUE TITLE
sample_n cannot sampling with designated size 

### ISSUE THREAD

**Issue by mimisikai** [tidyverse/dplyr#5665] opened 2020-12-18 22:40 UTC
One list contains 352 data.frames, each data frame has xxx obs of 37 variables.
I want to sample 100 rows of each data frame, 

lapply(CD4_arcsinh_trans, function(x) sample_n(x, 100))
 Error: `size` must be less or equal than 23 (size of data), set `replace` = TRUE to use sampling with replacement.
Run `rlang::last_error()` to see where the error occurred. 

Constantly have this error, I cannot understand why the size must be less 23.  

---

Brief description of the problem

```r
# insert reprex here
```

**Comment by romainfrancois** [comment] 2021-01-04 11:07
Can you please add a reprex, using the [reprex](https://reprex.tidyverse.org) package. We do not have `CD4_arcsinh_trans`

**Comment by romainfrancois** [comment] 2021-01-11 14:11
@mimisikai can you please share an example of code that reproduces the problem ?

**Comment by romainfrancois** [comment] 2021-01-12 09:37
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by romainfrancois** 2021-01-12 09:37 UTC
Labels: reprex
