### ISSUE TITLE
Renaming multiple columns fails on database backend

### ISSUE THREAD

**Issue by richgoldberg** [tidyverse/dplyr#2860] opened 2017-06-13 20:56 UTC
I just updated from dplyr 0.5 to dplyr 0.7 and found a minor bug that appears to be backend dependent.  Basically, rename() stopped allowing multiple columns to be renamed at once when pointed towards a SQLite backend.  (I tried the same thing with a data.frame backend and it seemed to work fine.)  

```r
library(dplyr,warn.conflicts = FALSE)

df <- dbplyr::memdb_frame(x = 1:3, y = 4:6)
df
#> # Source:   table<bcypiohokb> [?? x 2]
#> # Database: sqlite 3.11.1 [:memory:]
#>       x     y
#>   <int> <int>
#> 1     1     4
#> 2     2     5
#> 3     3     6
df %>% rename(A=x, B=y)
#> Error in names(select)[match(old_vars, vars)] <- new_vars: NAs are not allowed in subscripted assignments
```

**Comment by hadley** [comment] 2017-06-13 21:37
Can you please use the reprex package to create your reprex so I can see the actual values?

**Comment by richgoldberg** [comment] 2017-06-13 23:21
Here it is (from a different computer but it gets the same result).  Nifty package -- I'd never seen the `reprex` package before.

``` r
library(dplyr)
#> Warning: package 'dplyr' was built under R version 3.3.3
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

# set up a SQLite connection
con <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
copy_to(con, mtcars)
con %>% tbl("mtcars")
#> # Source:   table<mtcars> [?? x 11]
#> # Database: sqlite 3.11.1 [:memory:]
#>      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#>    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#>  1  21.0     6 160.0   110  3.90 2.620 16.46     0     1     4     4
#>  2  21.0     6 160.0   110  3.90 2.875 17.02     0     1     4     4
#>  3  22.8     4 108.0    93  3.85 2.320 18.61     1     1     4     1
#>  4  21.4     6 258.0   110  3.08 3.215 19.44     1     0     3     1
#>  5  18.7     8 360.0   175  3.15 3.440 17.02     0     0     3     2
#>  6  18.1     6 225.0   105  2.76 3.460 20.22     1     0     3     1
#>  7  14.3     8 360.0   245  3.21 3.570 15.84     0     0     3     4
#>  8  24.4     4 146.7    62  3.69 3.190 20.00     1     0     4     2
#>  9  22.8     4 140.8    95  3.92 3.150 22.90     1     0     4     2
#> 10  19.2     6 167.6   123  3.92 3.440 18.30     1     0     4     4
#> # ... with more rows

# try renaming one column
con %>% tbl("mtcars") %>% rename(Weight=wt)
#> # Source:   lazy query [?? x 11]
#> # Database: sqlite 3.11.1 [:memory:]
#>      mpg   cyl  disp    hp  drat Weight  qsec    vs    am  gear  carb
#>    <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#>  1  21.0     6 160.0   110  3.90  2.620 16.46     0     1     4     4
#>  2  21.0     6 160.0   110  3.90  2.875 17.02     0     1     4     4
#>  3  22.8     4 108.0    93  3.85  2.320 18.61     1     1     4     1
#>  4  21.4     6 258.0   110  3.08  3.215 19.44     1     0     3     1
#>  5  18.7     8 360.0   175  3.15  3.440 17.02     0     0     3     2
#>  6  18.1     6 225.0   105  2.76  3.460 20.22     1     0     3     1
#>  7  14.3     8 360.0   245  3.21  3.570 15.84     0     0     3     4
#>  8  24.4     4 146.7    62  3.69  3.190 20.00     1     0     4     2
#>  9  22.8     4 140.8    95  3.92  3.150 22.90     1     0     4     2
#> 10  19.2     6 167.6   123  3.92  3.440 18.30     1     0     4     4
#> # ... with more rows
con %>% tbl("mtcars") %>% rename(HorsePower=hp)
#> # Source:   lazy query [?? x 11]
#> # Database: sqlite 3.11.1 [:memory:]
#>      mpg   cyl  disp HorsePower  drat    wt  qsec    vs    am  gear  carb
#>    <dbl> <dbl> <dbl>      <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#>  1  21.0     6 160.0        110  3.90 2.620 16.46     0     1     4     4
#>  2  21.0     6 160.0        110  3.90 2.875 17.02     0     1     4     4
#>  3  22.8     4 108.0         93  3.85 2.320 18.61     1     1     4     1
#>  4  21.4     6 258.0        110  3.08 3.215 19.44     1     0     3     1
#>  5  18.7     8 360.0        175  3.15 3.440 17.02     0     0     3     2
#>  6  18.1     6 225.0        105  2.76 3.460 20.22     1     0     3     1
#>  7  14.3     8 360.0        245  3.21 3.570 15.84     0     0     3     4
#>  8  24.4     4 146.7         62  3.69 3.190 20.00     1     0     4     2
#>  9  22.8     4 140.8         95  3.92 3.150 22.90     1     0     4     2
#> 10  19.2     6 167.6        123  3.92 3.440 18.30     1     0     4     4
#> # ... with more rows
# WORKS FINE

# now try renaming two columns at once
con %>% tbl("mtcars") %>% rename(Weight=wt, HorsePower=hp)
#> Error in names(select)[match(old_vars, vars)] <- new_vars: NAs are not allowed in subscripted assignments
# GAVE ERROR

# but it works with a data.frame backend
mtcars %>%  rename(Weight=wt, HorsePower=hp)
#>                      mpg cyl  disp HorsePower drat Weight  qsec vs am gear
#> Mazda RX4           21.0   6 160.0        110 3.90  2.620 16.46  0  1    4
#> Mazda RX4 Wag       21.0   6 160.0        110 3.90  2.875 17.02  0  1    4
#> Datsun 710          22.8   4 108.0         93 3.85  2.320 18.61  1  1    4
#> Hornet 4 Drive      21.4   6 258.0        110 3.08  3.215 19.44  1  0    3
#> Hornet Sportabout   18.7   8 360.0        175 3.15  3.440 17.02  0  0    3
#> Valiant             18.1   6 225.0        105 2.76  3.460 20.22  1  0    3
#> Duster 360          14.3   8 360.0        245 3.21  3.570 15.84  0  0    3
#> Merc 240D           24.4   4 146.7         62 3.69  3.190 20.00  1  0    4
#> Merc 230            22.8   4 140.8         95 3.92  3.150 22.90  1  0    4
#> Merc 280            19.2   6 167.6        123 3.92  3.440 18.30  1  0    4
#> Merc 280C           17.8   6 167.6        123 3.92  3.440 18.90  1  0    4
#> Merc 450SE          16.4   8 275.8        180 3.07  4.070 17.40  0  0    3
#> Merc 450SL          17.3   8 275.8        180 3.07  3.730 17.60  0  0    3
#> Merc 450SLC         15.2   8 275.8        180 3.07  3.780 18.00  0  0    3
#> Cadillac Fleetwood  10.4   8 472.0        205 2.93  5.250 17.98  0  0    3
#> Lincoln Continental 10.4   8 460.0        215 3.00  5.424 17.82  0  0    3
#> Chrysler Imperial   14.7   8 440.0        230 3.23  5.345 17.42  0  0    3
#> Fiat 128            32.4   4  78.7         66 4.08  2.200 19.47  1  1    4
#> Honda Civic         30.4   4  75.7         52 4.93  1.615 18.52  1  1    4
#> Toyota Corolla      33.9   4  71.1         65 4.22  1.835 19.90  1  1    4
#> Toyota Corona       21.5   4 120.1         97 3.70  2.465 20.01  1  0    3
#> Dodge Challenger    15.5   8 318.0        150 2.76  3.520 16.87  0  0    3
#> AMC Javelin         15.2   8 304.0        150 3.15  3.435 17.30  0  0    3
#> Camaro Z28          13.3   8 350.0        245 3.73  3.840 15.41  0  0    3
#> Pontiac Firebird    19.2   8 400.0        175 3.08  3.845 17.05  0  0    3
#> Fiat X1-9           27.3   4  79.0         66 4.08  1.935 18.90  1  1    4
#> Porsche 914-2       26.0   4 120.3         91 4.43  2.140 16.70  0  1    5
#> Lotus Europa        30.4   4  95.1        113 3.77  1.513 16.90  1  1    5
#> Ford Pantera L      15.8   8 351.0        264 4.22  3.170 14.50  0  1    5
#> Ferrari Dino        19.7   6 145.0        175 3.62  2.770 15.50  0  1    5
#> Maserati Bora       15.0   8 301.0        335 3.54  3.570 14.60  0  1    5
#> Volvo 142E          21.4   4 121.0        109 4.11  2.780 18.60  1  1    4
#>                     carb
#> Mazda RX4              4
#> Mazda RX4 Wag          4
#> Datsun 710             1
#> Hornet 4 Drive         1
#> Hornet Sportabout      2
#> Valiant                1
#> Duster 360             4
#> Merc 240D              2
#> Merc 230               2
#> Merc 280               4
#> Merc 280C              4
#> Merc 450SE             3
#> Merc 450SL             3
#> Merc 450SLC            3
#> Cadillac Fleetwood     4
#> Lincoln Continental    4
#> Chrysler Imperial      4
#> Fiat 128               1
#> Honda Civic            2
#> Toyota Corolla         1
#> Toyota Corona          1
#> Dodge Challenger       2
#> AMC Javelin            2
#> Camaro Z28             4
#> Pontiac Firebird       2
#> Fiat X1-9              1
#> Porsche 914-2          2
#> Lotus Europa           2
#> Ford Pantera L         4
#> Ferrari Dino           6
#> Maserati Bora          8
#> Volvo 142E             2
# WORKS FINE
```

**Comment by richgoldberg** [comment] 2017-06-13 23:39
BTW, to make sure the issue wasn't just one of version, I updated R to the latest version (3.4.0), updated RStudio and all packages, and reran the example.  Here's the result
``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

# set up a SQLite connection
con <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
copy_to(con, mtcars)
con %>% tbl("mtcars")
#> # Source:   table<mtcars> [?? x 11]
#> # Database: sqlite 3.11.1 [:memory:]
#>      mpg   cyl  disp    hp  drat    wt  qsec    vs    am  gear  carb
#>    <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#>  1  21.0     6 160.0   110  3.90 2.620 16.46     0     1     4     4
#>  2  21.0     6 160.0   110  3.90 2.875 17.02     0     1     4     4
#>  3  22.8     4 108.0    93  3.85 2.320 18.61     1     1     4     1
#>  4  21.4     6 258.0   110  3.08 3.215 19.44     1     0     3     1
#>  5  18.7     8 360.0   175  3.15 3.440 17.02     0     0     3     2
#>  6  18.1     6 225.0   105  2.76 3.460 20.22     1     0     3     1
#>  7  14.3     8 360.0   245  3.21 3.570 15.84     0     0     3     4
#>  8  24.4     4 146.7    62  3.69 3.190 20.00     1     0     4     2
#>  9  22.8     4 140.8    95  3.92 3.150 22.90     1     0     4     2
#> 10  19.2     6 167.6   123  3.92 3.440 18.30     1     0     4     4
#> # ... with more rows

# try renaming one column
con %>% tbl("mtcars") %>% rename(Weight=wt)
#> # Source:   lazy query [?? x 11]
#> # Database: sqlite 3.11.1 [:memory:]
#>      mpg   cyl  disp    hp  drat Weight  qsec    vs    am  gear  carb
#>    <dbl> <dbl> <dbl> <dbl> <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#>  1  21.0     6 160.0   110  3.90  2.620 16.46     0     1     4     4
#>  2  21.0     6 160.0   110  3.90  2.875 17.02     0     1     4     4
#>  3  22.8     4 108.0    93  3.85  2.320 18.61     1     1     4     1
#>  4  21.4     6 258.0   110  3.08  3.215 19.44     1     0     3     1
#>  5  18.7     8 360.0   175  3.15  3.440 17.02     0     0     3     2
#>  6  18.1     6 225.0   105  2.76  3.460 20.22     1     0     3     1
#>  7  14.3     8 360.0   245  3.21  3.570 15.84     0     0     3     4
#>  8  24.4     4 146.7    62  3.69  3.190 20.00     1     0     4     2
#>  9  22.8     4 140.8    95  3.92  3.150 22.90     1     0     4     2
#> 10  19.2     6 167.6   123  3.92  3.440 18.30     1     0     4     4
#> # ... with more rows
con %>% tbl("mtcars") %>% rename(HorsePower=hp)
#> # Source:   lazy query [?? x 11]
#> # Database: sqlite 3.11.1 [:memory:]
#>      mpg   cyl  disp HorsePower  drat    wt  qsec    vs    am  gear  carb
#>    <dbl> <dbl> <dbl>      <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#>  1  21.0     6 160.0        110  3.90 2.620 16.46     0     1     4     4
#>  2  21.0     6 160.0        110  3.90 2.875 17.02     0     1     4     4
#>  3  22.8     4 108.0         93  3.85 2.320 18.61     1     1     4     1
#>  4  21.4     6 258.0        110  3.08 3.215 19.44     1     0     3     1
#>  5  18.7     8 360.0        175  3.15 3.440 17.02     0     0     3     2
#>  6  18.1     6 225.0        105  2.76 3.460 20.22     1     0     3     1
#>  7  14.3     8 360.0        245  3.21 3.570 15.84     0     0     3     4
#>  8  24.4     4 146.7         62  3.69 3.190 20.00     1     0     4     2
#>  9  22.8     4 140.8         95  3.92 3.150 22.90     1     0     4     2
#> 10  19.2     6 167.6        123  3.92 3.440 18.30     1     0     4     4
#> # ... with more rows
# WORKS FINE

# now try renaming two columns at once
con %>% tbl("mtcars") %>% rename(Weight=wt, HorsePower=hp)
#> Error in names(select)[match(old_vars, vars)] <- new_vars: NAs are not allowed in subscripted assignments
# GAVE ERROR

# but it works with a data.frame backend
mtcars %>%  rename(Weight=wt, HorsePower=hp)
#>                      mpg cyl  disp HorsePower drat Weight  qsec vs am gear
#> Mazda RX4           21.0   6 160.0        110 3.90  2.620 16.46  0  1    4
#> Mazda RX4 Wag       21.0   6 160.0        110 3.90  2.875 17.02  0  1    4
#> Datsun 710          22.8   4 108.0         93 3.85  2.320 18.61  1  1    4
#> Hornet 4 Drive      21.4   6 258.0        110 3.08  3.215 19.44  1  0    3
#> Hornet Sportabout   18.7   8 360.0        175 3.15  3.440 17.02  0  0    3
#> Valiant             18.1   6 225.0        105 2.76  3.460 20.22  1  0    3
#> Duster 360          14.3   8 360.0        245 3.21  3.570 15.84  0  0    3
#> Merc 240D           24.4   4 146.7         62 3.69  3.190 20.00  1  0    4
#> Merc 230            22.8   4 140.8         95 3.92  3.150 22.90  1  0    4
#> Merc 280            19.2   6 167.6        123 3.92  3.440 18.30  1  0    4
#> Merc 280C           17.8   6 167.6        123 3.92  3.440 18.90  1  0    4
#> Merc 450SE          16.4   8 275.8        180 3.07  4.070 17.40  0  0    3
#> Merc 450SL          17.3   8 275.8        180 3.07  3.730 17.60  0  0    3
#> Merc 450SLC         15.2   8 275.8        180 3.07  3.780 18.00  0  0    3
#> Cadillac Fleetwood  10.4   8 472.0        205 2.93  5.250 17.98  0  0    3
#> Lincoln Continental 10.4   8 460.0        215 3.00  5.424 17.82  0  0    3
#> Chrysler Imperial   14.7   8 440.0        230 3.23  5.345 17.42  0  0    3
#> Fiat 128            32.4   4  78.7         66 4.08  2.200 19.47  1  1    4
#> Honda Civic         30.4   4  75.7         52 4.93  1.615 18.52  1  1    4
#> Toyota Corolla      33.9   4  71.1         65 4.22  1.835 19.90  1  1    4
#> Toyota Corona       21.5   4 120.1         97 3.70  2.465 20.01  1  0    3
#> Dodge Challenger    15.5   8 318.0        150 2.76  3.520 16.87  0  0    3
#> AMC Javelin         15.2   8 304.0        150 3.15  3.435 17.30  0  0    3
#> Camaro Z28          13.3   8 350.0        245 3.73  3.840 15.41  0  0    3
#> Pontiac Firebird    19.2   8 400.0        175 3.08  3.845 17.05  0  0    3
#> Fiat X1-9           27.3   4  79.0         66 4.08  1.935 18.90  1  1    4
#> Porsche 914-2       26.0   4 120.3         91 4.43  2.140 16.70  0  1    5
#> Lotus Europa        30.4   4  95.1        113 3.77  1.513 16.90  1  1    5
#> Ford Pantera L      15.8   8 351.0        264 4.22  3.170 14.50  0  1    5
#> Ferrari Dino        19.7   6 145.0        175 3.62  2.770 15.50  0  1    5
#> Maserati Bora       15.0   8 301.0        335 3.54  3.570 14.60  0  1    5
#> Volvo 142E          21.4   4 121.0        109 4.11  2.780 18.60  1  1    4
#>                     carb
#> Mazda RX4              4
#> Mazda RX4 Wag          4
#> Datsun 710             1
#> Hornet 4 Drive         1
#> Hornet Sportabout      2
#> Valiant                1
#> Duster 360             4
#> Merc 240D              2
#> Merc 230               2
#> Merc 280               4
#> Merc 280C              4
#> Merc 450SE             3
#> Merc 450SL             3
#> Merc 450SLC            3
#> Cadillac Fleetwood     4
#> Lincoln Continental    4
#> Chrysler Imperial      4
#> Fiat 128               1
#> Honda Civic            2
#> Toyota Corolla         1
#> Toyota Corona          1
#> Dodge Challenger       2
#> AMC Javelin            2
#> Camaro Z28             4
#> Pontiac Firebird       2
#> Fiat X1-9              1
#> Porsche 914-2          2
#> Lotus Europa           2
#> Ford Pantera L         4
#> Ferrari Dino           6
#> Maserati Bora          8
#> Volvo 142E             2
# WORKS FINE
```

**Comment by hadley** [comment] 2017-06-14 12:39
Thanks for providing some code that illustrates the problem — it's a great start 😄 However, your code is currently a bit too complicated: there's data is rather large and obscures the heart of the problem. Can you please try and simplify your example some more? The more minimal you can make the reprex, the faster I can identify the problem and fix it.

**Comment by richgoldberg** [comment] 2017-06-14 13:20
``` r
library(DBI)
library(RSQLite)
library(magrittr)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union


# create a data.frame and corresponding SQLite version
dat = data.frame(x=1:3, y = 4:6)
dat_sql = dbConnect(SQLite(), ":memory:") %T>% copy_to(dat) %>% tbl("dat")

# check the data
dat
#>   x y
#> 1 1 4
#> 2 2 5
#> 3 3 6
dat_sql %>% collect()
#> # A tibble: 3 x 2
#>       x     y
#>   <int> <int>
#> 1     1     4
#> 2     2     5
#> 3     3     6

# try renaming two columns at once
dat %>% rename(A=x, B=y)
#>   A B
#> 1 1 4
#> 2 2 5
#> 3 3 6
dat_sql %>%  rename(A=x, B=y) %>% collect()
#> Error in names(select)[match(old_vars, vars)] <- new_vars: NAs are not allowed in subscripted assignments
```

**Comment by hadley** [comment] 2017-06-14 13:57
Can you please use `dbplyr::membdb_frame()`, `warn.conflicts = FALSE` in `library(dplyr)` and omit the working examples with local data frame?

**Comment by richgoldberg** [comment] 2017-06-14 14:12
```r
library(dplyr,warn.conflicts = FALSE)

df <- dbplyr::memdb_frame(x = 1:3, y = 4:6)
df
#> # Source:   table<bcypiohokb> [?? x 2]
#> # Database: sqlite 3.11.1 [:memory:]
#>       x     y
#>   <int> <int>
#> 1     1     4
#> 2     2     5
#> 3     3     6
df %>% rename(A=x, B=y)
#> Error in names(select)[match(old_vars, vars)] <- new_vars: NAs are not allowed in subscripted assignments
```

**Comment by hadley** [comment] 2017-06-14 14:46
@richgoldberg perfect - thanks!  I'll now go back and delete all the previous attempts.

**Comment by JohnMount** [comment] 2017-06-14 17:00
Possibly related (to help run down causes and extent): [Sparklyr 678](https://github.com/rstudio/sparklyr/issues/678) and [dplyr 2776](https://github.com/tidyverse/dplyr/issues/2776).

**Comment by javierluraschi** [comment] 2017-06-14 17:11
Regarding `sparklyr`, this is fixed on development version, doesn't mean that there is no bug in `dplyr` since I did not fully investigate the root cause but was somewhat related (made worse) by `sparklyr` overriding collect for `dplyr 0.5`. Currently, no plans to backport fix to CRAN but rather we are focusing to polish `sparklyr 0.6` for CRAN release.

**Comment by JohnMount** [comment] 2017-06-14 17:38
Given  [dplyr 2860](https://github.com/tidyverse/dplyr/issues/2860) I think there is possibly more than one bug in the `dplyr` `dbplyr` call path (but possibly not more than one bug for `sparklyr` as `sparklyr` may be overriding steps and avoiding the other issues).

**Comment by hadley** [comment] 2017-06-22 15:45
This is a bug in `rename_vars()` which is moving to `tidyselect::vars_rename()`. I think it's easiest to fix the bug in tidyselect, and then use tidyselect in dplyr: https://github.com/tidyverse/dplyr/issues/2896

**Closed by hadley** 2017-06-22 15:45 UTC
Labels: bug, database
