### ISSUE TITLE
[Feature Request] Join Information added to dplyr joins functions

### ISSUE THREAD

**Issue by GeorgeRJacobs** [tidyverse/dplyr#3231] opened 2017-11-29 16:19 UTC
Perhaps this asking for too much from the package. But, I find that when I am doing data joins, and the like with data in R, there can sometimes be unexpected behavior. Unaccounted for rows added ( left_join() ) and the like. Some sort of helpful output would be ideal for fact checking myself. Along the lines of: 

```
df before: 10 rows

# Oops - this wasn't supposed to create new rows! 
df after: 15 rows
```
I usually do this anyways (`nrow()`, etc), but it might be helpful to display some 'metrics'. It might be especially helpful for new users starting with joins in R to have some useful output to go along with the mental tasks of join conditions. 

Thanks

**Comment by batpigandme** [comment] 2017-11-29 16:34
I haven't gone through all of these packages, but I recently came across @echasnovski's ruler package, which has a nice list of some ~tidy data validation tools at the end https://github.com/echasnovski/ruler

**Comment by GeorgeRJacobs** [comment] 2017-11-29 16:45
Thanks for the link! From the vignettes (quick look), it appears that packages takes the ideas above, and pushes them to the logical conclusion. It would still require new students of R to put some thought into joins and expected output (probably a good thing!). Depending on the goals of the project, some 'gentle' output may still be warranted. Regardless, I will start taking a deeper look.

**Comment by batpigandme** [comment] 2017-11-29 17:26
I'm all for helpful error messages (I'll be curious to see what others think), my major concern would be the meaning that would come from the "mute sign" (i.e. if there's no message, you assume everything's fine). 

My best analogy for this is that, for a long time, none of the four-way intersections on the roads around me had stop signs (we're talking 'burbs, not high traffic). You'd stop (or slow), and look, because there _could_ be cars or kids coming. Then, a few years back, a family moved into a house nearby and somehow got stop signs approved for the three-way intersection in front of it (four if you count their driveway as a road). It drives me crazy, because, as a result, you'd _assume_ you have the right of way/can safely go when there's *no* stop sign at the rest of the intersections on the road. 

Sorry for the long-winded explanation!

**Comment by GeorgeRJacobs** [comment] 2017-11-29 18:32
No worries. I am smarter for it. So if I understand correctly, you are worried about the case where a mute sign occurs, and the person says in their head, "Join = Good. No more critical thinking required.". I think the question turns on whether this sort of message saves user's time by identifying behavior vs. changing a user's _expectation_ of the 'safety' of their join operation.

**Comment by batpigandme** [comment] 2017-11-29 20:43
It's not so much that it'd be bad to have backups in place (again, I'm definitely curious to hear what the devs think), it's just that _outside of_ the ecosystem of a single package, there's no way to control for the same scenario. Likewise, one would want to consider what comparable failsafes would be. Surely there are similar scenarios with other types of joins— in fact, an infinite number of things could go wrong (obviously that's an absurd line of argument), and you'd want to make sure that there's an even-handed expectation of validation. Data quality and validation are broad areas (it's actually what my dad did for years), and I really like the idea of packages that work well with "tidy data," but I'm _not sure_ that this would be in-scope with the join function, if we're working off of the ethos that one function does one thing and does it well.

Again, I could be totally wrong on this. Just my 2¢s atm! 😉

**Comment by GeorgeRJacobs** [comment] 2017-11-29 21:43
I think I see your point. Hmm. Maybe you are right about this. If the join operations are working on tidy data, then what I propose is a lesser issue. And the fact the data isn't tidy would mean that you have more than just this specific problem to deal with most likely. Following that logic, `dplyr`s ethos should be tools for manipulating data using a common set of verbs, not _suggesting_ ways to manipulate said data.

**Comment by krlmlr** [comment] 2018-03-16 13:59
Thanks. I see some overlap with #2183 and #1792, can you confirm?

**Comment by brshallo** [comment] 2018-11-02 19:44
@GeorgeRJacobs I agree having an argument/option to print some “soft” metrics with the `*_join` functions might be nice.  @batpigandme I hear your point regarding the “tidy data” ethos.  Unconscious join errors happen so frequently that an exception here might not be bad.  E.g., could print “how many (/any) rows duplicated from each dataframe”, “how many rows remain from each"… or some individual or *short* list of “foundational join quality metric(s)” … 

Here’s a rough and dirty example:

``` r
library(tidyverse, warn.conflicts = FALSE, quietly = TRUE)

x <- tribble(
  ~key, ~val_x,
  1, "x1",
  2, "x2",
  3, "x3",
  6, "x4"
)

y <- tribble(
  ~key, ~val_y,
  1, "y1",
  2, "y2",
  3, "y3",
  4, "y4",
  5, "y5"
)

inner_join_noisy <- function(..., noisy = TRUE){

  # QUICK example of a "quality metric" to print for `inner_join`
  
  output <- inner_join(...)

  print_num_rows <- function(x_or_y){
    input_name <- deparse(substitute(x_or_y))
    
    x_or_y %>% 
      semi_join(output, by = "key") %>% 
      count() %>% 
      with(n) %>% 
      cat(., " of ", nrow(x_or_y), " individual rows from ", input_name, " included in output.", "\n")
  }
  
  if(noisy){
    print_num_rows(x_or_y = x)
    print_num_rows(x_or_y = y)
  }
  
  output
}

inner_join_noisy(x, y, by = "key", noisy = TRUE)
#> 3  of  4  individual rows from  x  included in output. 
#> 3  of  5  individual rows from  y  included in output.
#> # A tibble: 3 x 3
#>     key val_x val_y
#>   <dbl> <chr> <chr>
#> 1     1 x1    y1   
#> 2     2 x2    y2   
#> 3     3 x3    y3
```

<sup>Created on 2018-11-02 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>


(P.s. not advocating for GUI ETL tools here – though I did see a colleague using a BI tool that had some metrics like this pop-up when specifying a join and thought it seemed like a nifty feature – which led me here.)

**Comment by brshallo** [comment] 2019-03-11 06:30
It looks like @elbersb `tidylog` package has implemented this type of information across joins and other `dplyr` verbs.

**Comment by hadley** [comment] 2019-05-27 15:19
Duplicate of #2183, and I'd definitely recommend tidylog.

**Closed by hadley** 2019-05-27 15:19 UTC
Labels: data frame, feature, generic
