### ISSUE TITLE
Scoped verb not recognizing variable

### ISSUE THREAD

**Issue by behrman** [tidyverse/dplyr#3992] opened 2018-12-04 20:01 UTC
The scoped verb below is not recognizing the variable in the anonymous function.

``` r
library(dplyr)
packageVersion("dplyr")
#> [1] '0.7.99.9000'

iris %>% 
  summarize_if(is.numeric, ~ sum(. - Sepal.Length))
#> Error in (structure(function (..., .x = ..1, .y = ..2, . = ..1) : object 'Sepal.Length' not found
```

<sup>Created on 2018-12-04 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by romainfrancois** [comment] 2018-12-04 20:55
this is a duplicate of #3843, potentially addressed by #3978

**Closed by romainfrancois** 2018-12-04 20:55 UTC
