### ISSUE TITLE
Incomplete docs for select_if() vs. select_at()

### ISSUE THREAD

**Issue by kenahoo** [tidyverse/dplyr#4535] opened 2019-08-15 22:03 UTC
The documentation for `select_if()` and `select_at()` (https://github.com/tidyverse/dplyr/blob/4cab709633a1f6693063b16d0a4555c26bbb1aa2/R/colwise-select.R) doesn't say what the difference is between them, nor what the `_if()` and `_at()` suffixes mean.

It could either link to a suitable place elsewhere in the docs, or add info directly to these docs.

**Comment by kenahoo** [comment] 2019-08-15 22:10
I ask because I'm not sure whether there's a way to select columns simultaneously by name and by type - e.g. "all columns starting with `m_`, and all numeric columns, and the column called `target`".  Not sure whether one or the other of `select_if()` or `select_at()` is capable of doing this, and I seem to keep forgetting how I usually solve this...

**Comment by atusy** [comment] 2019-08-16 10:58
Take a look at the documentation of their second arguments, `.predicate` for the `_if` variants,  `.vars` for `_at` variants.

In source, they are documented here: https://github.com/tidyverse/dplyr/blob/4af23627943d0a5ac1322dd193bc5d42a89a2978/R/colwise.R#L1-L78

To select by name and by type, I recommend `select_at`, though `select_if` also works.

``` r
library(dplyr, warn.conflict = FALSE)
library(purrr, warn.conflict = FALSE)
tibble(m_1 = "m_1", m_2 = "m_2", x = 1, b = "b", target = TRUE) %>%
  select_at(
    vars(starts_with("m"), names(.)[map_lgl(., is.numeric)], "target")
  )
#> # A tibble: 1 x 4
#>   m_1   m_2       x target
#>   <chr> <chr> <dbl> <lgl> 
#> 1 m_1   m_2       1 TRUE
```

<sup>Created on 2019-08-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kenahoo** [comment] 2019-08-16 14:35
Thanks, @atusy .  These would be good places to cross-reference in the docs.

**Comment by atusy** [comment] 2019-08-17 09:06
Your welcome.

FYI, `select`'s document is referencing `scoped`'s document.

https://github.com/tidyverse/dplyr/blob/4af23627943d0a5ac1322dd193bc5d42a89a2978/R/colwise-select.R#L5

**Comment by hadley** [comment] 2019-12-10 22:44
Now a duplicate of #4597 — in dplyr 1.0.0 you'll be able to do something like `select(df, starts_with("m_") & is.numeric)`

**Closed by hadley** 2019-12-10 22:44 UTC
