### ISSUE TITLE
Regression bug in 0.7.5: can't select a column from a dataframe if any column is NA

### ISSUE THREAD

**Issue by daattali** [tidyverse/dplyr#3603] opened 2018-05-26 19:49 UTC
This worked in 0.7.4 and errors in 0.7.5:

```
df <- data.frame(x=1, y=2, z=3)
colnames(df) <- c("x","y")
dplyr::select_(df, "x")
# Error in select_impl(.data, vars) : Column `3` cannot have NA as name
```

You may argue that the second line is bad code, but I don't think dplyr should break trying to select from that dataframe

**Comment by krlmlr** [comment] 2018-05-26 20:39
Just checked, it's *dplyr* (and not *tidyselect*) that throws the error. This change should have been in the NEWS, I don't remember why it's not there.

We're moving towards stricter handling of input, I think it's better to fail early here.

**Comment by daattali** [comment] 2018-05-26 20:47
Should it really be an error though? If I'm trying to select a column that is named, which means throwing away the unnamed ones, I want that to work.

Usecase in hand: I know the first 3 columns of the dataframe **definitely** exist, and there may be other variables or there may not be. So I change the names of the first 3 (that I know exist), and then extract them, throwing away any other columns (if they exist). I don't think that operation should fail, that feels like excessive error handling. Is it a bug or an explicitly intended feature?

**Comment by krlmlr** [comment] 2018-05-26 20:53
The following feels like a clearer solution. (It fails if fewer columns exist.)

```r
... %>% select(1:3) %>% set_names(c(...))
```

I'd like to err on the side of caution here.

**Comment by daattali** [comment] 2018-05-26 21:11
Yep I can certainly change to do that, but was it actually intended behaviour that dplyr functions would stop working with dataframes that have a column named NA?

**Comment by hadley** [comment] 2018-05-26 21:50
It was intended that dplyr throw a clear error message when you give it an invalid data frame.

**Comment by daattali** [comment] 2018-05-26 21:55
@hadley got it. Is there a document that specifies what a valid/invalid dataframe is? I legitimately want to know what other rules there, and I can't find anywhere that mentions a column name must not be NA (as trivial as it might be)

**Comment by romainfrancois** [comment] 2018-05-27 09:02
Might be related to https://github.com/tidyverse/tidyselect/issues/61

**Comment by krlmlr** [comment] 2018-05-27 18:50
`?tibble::set_tidy_names()` contains a description, but it could be clearer. Also, at some point we should link to that page.

**Comment by hadley** [comment] 2018-05-28 14:26
Documentation for data.frame is a place to start:

> The column names should be non-empty, and attempts to use empty names will have unsupported results.

**Comment by romainfrancois** [comment] 2018-05-28 14:29
🤔 so perhaps instead of https://github.com/tidyverse/tidyselect/pull/62 perhaps `vars_select()` should error when it is given NA or empty.

**Comment by daattali** [comment] 2018-05-28 14:32
Seems like there's an agreement that the behaviour I reported is a feature rather than a bug, this can be closed then unless you want to keep it open to ensure it gets documented

**Comment by romainfrancois** [comment] 2018-05-28 14:34
if it's a feature, I'd like to enforce it and test about it. In any case thanks for pointing it out.

**Comment by billdenney** [comment] 2018-07-14 10:53
I wish that the code were more forgiving to users without tidy data (i.e. who receive data from others who may know nothing of good data handling and must work with it as is).  At least some of these errors are not required for functionality because the user is trying to convert messy to tidy data (as I noted in #3712), but it is now harder than it was.

With this new feature, as it breaks existing code, it would be helpful if the error messages related to invalid names suggested a way to fix it.  The current error message says “Column `1` cannot have NA as name” which isn’t precisely accurate; perhaps an updated error message could be:
“Column `1` is named NA which is not supported by the tidyverse please use tibble::set_tidy_names() or another method to rename or remove these columns”

**Comment by billdenney** [comment] 2018-07-17 17:57
I've been thinking more about this issue as it comes up in data that I receive pretty often (due to receiving messy data from external sources that I cannot control).

I think it makes sense that the *output* of all functions is a well-formed data.frame (or tibble or ...), but it's helpful to the user (i.e. at least me and probably @daattali) to be as forgiving as feasible on *input*.

In the cases that @daattali and I have cited, we are trying to select only well-formed column names from a data.frame that includes both well-formed and ill-formed names.  We are trying to convert data from messy to tidy.  In @daattali's case, the bad column names are known in advance (at least in the specific case mentioned).  In my case, the bad column names often move from one data delivery to the next (atrocious but true).

Would it be feasible/reasonable to allow positive selection of well-formed names to work as long as the selected name is not `NA` or `""` (which is my reading of the invalid names from the `data.frame` help page)?

Perhaps the enforcement of well-formed names on input makes sense for most other functions, but `select` is often used on messy data to improve its tidyness.

**Comment by lparsons** [comment] 2018-07-19 21:14
:+1: for the [Robustness Principle](https://en.wikipedia.org/wiki/Robustness_principle): *"Be conservative in what you send, be liberal in what you accept"*

**Closed** 2019-06-08 07:39 UTC
