### ISSUE TITLE
Grouped n_distinct of factor variable slow when there are many groups

### ISSUE THREAD

**Issue by mpelath** [tidyverse/dplyr#4547] opened 2019-08-30 17:39 UTC
When there are many groups, and we are summarizing a factor variable using n_distinct(), the processing time is orders of magnitude slower than the equivalent approach using distinct().  On large (~80M record) dataset, the difference is between not-finishing-overnight and a few minutes.

Summarizing a numeric variable is reasonably fast, interestingly.

This is using dplyr 0.8.3.

```r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
data <- tibble(x = rep(seq(1, 10000), each = 10),
               y = floor(runif(100000, 0, 10)))

system.time(result1 <- data %>% group_by(x) %>% summarize(n = n_distinct(y)))
#>    user  system elapsed 
#>    0.05    0.00    0.07
system.time(result2 <- data %>% distinct() %>% count(x))
#>    user  system elapsed 
#>    0.03    0.00    0.03

all_equal(result1, result2)
#> [1] TRUE

data <- tibble(x = rep(seq(1, 10000), each = 10),
               y = factor(floor(runif(100000, 0, 10))))

system.time(result1 <- data %>% group_by(x) %>% summarize(n = n_distinct(y)))
#>    user  system elapsed 
#>    2.29    2.46    4.97
system.time(result2 <- data %>% distinct() %>% count(x))
#>    user  system elapsed 
#>    0.03    0.00    0.03

all_equal(result1, result2)
#> [1] TRUE
```

<sup>Created on 2019-08-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by mpelath** [comment] 2019-09-10 14:49
In general, I'm finding huge (>10x) performance differences between 0.7.4 (for example) and 0.8.3.  While there are some improvements, the degradation in performance in some contexts is so serious as to make dplyr unusable.  If I can isolate other examples, I will enter issues.

**Comment by batpigandme** [comment] 2019-09-10 14:53
I think this might be related to https://github.com/tidyverse/dplyr/issues/4166

**Comment by romainfrancois** [comment] 2019-11-26 11:13
Here is where we are with dev version. This is one case where we lost performance because hybrid evaluation has been quarantine. Added milestone and `hybrid` tag to come back to it. 

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
data <- tibble(x = rep(seq(1, 10000), each = 10),
  y = floor(runif(100000, 0, 10)))

system.time(result1 <- data %>% group_by(x) %>% summarize(n = n_distinct(y)))
#>    user  system elapsed 
#>   7.234   0.025   7.262
system.time(result2 <- data %>% distinct() %>% count(x))
#>    user  system elapsed 
#>   1.531   0.004   1.535

all_equal(result1, result2)
#> [1] TRUE

data <- tibble(x = rep(seq(1, 10000), each = 10),
  y = factor(floor(runif(100000, 0, 10))))

system.time(result1 <- data %>% group_by(x) %>% summarize(n = n_distinct(y)))
#>    user  system elapsed 
#>   7.180   0.009   7.194
system.time(result2 <- data %>% distinct() %>% count(x))
#>    user  system elapsed 
#>   1.507   0.004   1.511

all_equal(result1, result2)
#> [1] TRUE
```

<sup>Created on 2019-11-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Comment by hadley** [comment] 2019-12-11 23:11
I think the problem is actually `n_distinct()` because swapping it out for `vec_unique_count()` gives a massive performance improvement:

``` r
library(dplyr, warn.conflict = FALSE)
library(vctrs)

df <- tibble(
  g = rep(seq(1, 10000), each = 10),
  x = floor(runif(100000, 0, 10))
)
df_g <- group_by(df, g)
x_g <- split(df$x, df$g)

system.time(summarize(df_g, n = n_distinct(x)))
#>    user  system elapsed 
#>   8.160   0.039   8.210
system.time(lapply(x_g, n_distinct))
#>    user  system elapsed 
#>   8.100   0.038   8.173

system.time(summarize(df_g, n = vec_unique_count(x)))
#>    user  system elapsed 
#>   0.180   0.003   0.184
system.time(lapply(x_g, vec_unique_count))
#>    user  system elapsed 
#>   0.012   0.000   0.012
```

<sup>Created on 2019-12-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

The problem seems to be the use of `tibble()` which is quite slow. We can probably swap out for a lower-level constructor here. `n_distinct()` is going to move to https://github.com/r-lib/funs/issues/44, so I'm going to track this issue there and close this one.

**Closed** 2019-12-11 23:12 UTC
Labels: funs :laughing:, performance :rocket:
