### ISSUE TITLE
Example from `filter` doesn't work as suggested

### ISSUE THREAD

**Issue by moodymudskipper** [tidyverse/dplyr#5530] opened 2020-09-14 14:03 UTC
In `filter_all `we read : 

```
# You can vary the selection of columns on which to apply the
# predicate. filter_at() takes a vars() specification:
filter_at(mtcars, vars(starts_with("d")), any_vars((. %% 2) == 0))
# ->
filter(mtcars, across(starts_with("d"), ~ (.x %% 2) == 0))
```

This is not right, as `any_vars()` doesn't have a direct replacement (this would be the replacement for `all_vars()`). 

```
library(dplyr, warn.conflicts = FALSE)
filter_at(mtcars, vars(starts_with("d")), any_vars((. %% 2) == 0))
#>                      mpg cyl disp  hp drat    wt  qsec vs am gear carb
#> Mazda RX4           21.0   6  160 110 3.90 2.620 16.46  0  1    4    4
#> Mazda RX4 Wag       21.0   6  160 110 3.90 2.875 17.02  0  1    4    4
#> Datsun 710          22.8   4  108  93 3.85 2.320 18.61  1  1    4    1
#> Hornet 4 Drive      21.4   6  258 110 3.08 3.215 19.44  1  0    3    1
#> Hornet Sportabout   18.7   8  360 175 3.15 3.440 17.02  0  0    3    2
#> Duster 360          14.3   8  360 245 3.21 3.570 15.84  0  0    3    4
#> Cadillac Fleetwood  10.4   8  472 205 2.93 5.250 17.98  0  0    3    4
#> Lincoln Continental 10.4   8  460 215 3.00 5.424 17.82  0  0    3    4
#> Chrysler Imperial   14.7   8  440 230 3.23 5.345 17.42  0  0    3    4
#> Dodge Challenger    15.5   8  318 150 2.76 3.520 16.87  0  0    3    2
#> AMC Javelin         15.2   8  304 150 3.15 3.435 17.30  0  0    3    2
#> Camaro Z28          13.3   8  350 245 3.73 3.840 15.41  0  0    3    4
#> Pontiac Firebird    19.2   8  400 175 3.08 3.845 17.05  0  0    3    2
filter(mtcars, across(starts_with("d"), ~ (.x %% 2) == 0))
#>  [1] mpg  cyl  disp hp   drat wt   qsec vs   am   gear carb
#> <0 lignes> (ou 'row.names' de longueur nulle)
```

**Comment by romainfrancois** [comment] 2020-09-17 07:42
labelled as documentation, and otherwise duplicate of #4770

**Closed** 2021-01-27 13:40 UTC
Labels: documentation
