### ISSUE TITLE
Possible inconsistence when using distinct

### ISSUE THREAD

**Issue by iago-pssjd** [tidyverse/dplyr#5526] opened 2020-09-08 14:34 UTC
I tried the next code with the next result:
```r
> distinct(c(3,NA))
Error in UseMethod("distinct_") : 
  no applicable method for 'distinct_' applied to an object of class "c('double', 'numeric')"
In addition: Warning message:
`distinct_()` is deprecated as of dplyr 0.7.0.
Please use `distinct()` instead.
See vignette('programming') for more help
This warning is displayed once every 8 hours.
Call `lifecycle::last_warnings()` to see where this warning was generated. 
```
I am not using `distinct_` so it is a bit strange. Then I check it:
```r
> distinct(c(3,NA))
Error in UseMethod("distinct_") : 
  no applicable method for 'distinct_' applied to an object of class "c('double', 'numeric')"
> traceback()
3: distinct_(.data, .dots = compat_as_lazy_dots(...), .keep_all = .keep_all)
2: distinct.default(c(3, NA))
1: distinct(c(3, NA))
```
So `distinct_` is deprecated but you mantain its internal use. I just let you know of this.

I do not expect anything, since I see in the help that the argument of this function should be a data frame.

**Comment by romainfrancois** [comment] 2020-09-17 08:11
Perhaps we can differentiate between actual calls of `distinct_()` and those from `distinct.default()` ?

**Comment by hadley** [comment] 2020-11-16 20:24
Duplicate of #5573

**Closed by hadley** 2020-11-16 20:24 UTC
