### ISSUE TITLE
Empty computed columns when fetching from SQLite

### ISSUE THREAD

**Issue by mrkowalski** [tidyverse/dplyr#3167] opened 2017-10-26 15:18 UTC
dplyr does not return any values for SQLite-fetched columns that are **computed**, i,e:

`SELECT CAST (strftime('%w', tt.date) AS INT) AS day_of_week FROM tt;`

dplyr: 0.7.4
dbplyr: 1.1.0
RSQLite: 2.0

In a RStudio notebook, when displaying the data, like:

```
db <- src_sqlite('data/database.db')
data <- tbl(db, 'Some view I use')
data
```
The type reported for the column is "lgl" regardless of what I cast it to and the value for **each** row is always "NA".

**Comment by hadley** [comment] 2017-10-27 12:44
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by krlmlr** [comment] 2018-01-19 13:40
Closing, because reprex is missing for more than two months.

**Closed by krlmlr** 2018-01-19 13:40 UTC
Labels: reprex
