### ISSUE TITLE
USAGE section: example of Remove NA's when calculating for mean.

### ISSUE THREAD

**Issue by CGWallace** [tidyverse/dplyr#4533] opened 2019-08-12 22:52 UTC
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem
In the example for the use of mean The N is not the number of samples used to get the mean but the number overall samples. As a result the filter does not act as expected. 
```r
# insert reprex here
``` r
#'reprex' failed when I tried this example

starwars %>%
  group_by(species) %>%
  summarise(
    n = n(),
    mass = mean(mass, na.rm = TRUE)
  ) %>%
  filter(n > 1,
         mass > 50)
# A tibble: 8 x 3
#species      n  mass
#<chr>    <int> <dbl>
#1 Droid        5  69.8
#2 Gungan       3  74  
#3 Human       35  82.8
#4 Kaminoan     2  88  
#5 Mirialan     2  53.1
#6 Twi'lek      2  55  
#7 Wookiee      2 124  
#8 Zabrak       2  80  


starwars %>%
  drop_na(mass) %>%
  group_by(species) %>%
  summarise(
    n = n(),
    mass = mean(mass)
  ) %>%
  filter(n > 1,
         mass > 50)

# A tibble: 5 x 3
#species      n  mass
#<chr>    <int> <dbl>
#1 Droid        4  69.8
#2 Gungan       2  74  
#3 Human       22  82.8
#4 Mirialan     2  53.1
#5 Wookiee      2 124 

# Further to this the 'sd' function only works 
# if it comes before the mean function

starwars %>%
  drop_na(mass) %>%
  group_by(species) %>%
  summarise(
    n = n(),
    sd1=sd(mass),
    mass = mean(mass),
    sd2=sd(mass)
  ) %>%
  filter(n > 1,
         mass > 50)

# A tibble: 5 x 5
#species      n   sd1  mass   sd2
#<chr>    <int> <dbl> <dbl> <dbl>
#1 Droid        4 51.0   69.8    NA
#2 Gungan       2 11.3   74      NA
#3 Human       22 19.4   82.8    NA
#4 Mirialan     2  4.38  53.1    NA
#5 Wookiee      2 17.0  124      NA

``

**Comment by dpprdan** [comment] 2019-09-05 09:14
@CGWallace `n()` returns the "The number of observations in the current group." (see the [documentation](https://dplyr.tidyverse.org/reference/n.html)). What you seem to be after is the number of observations in the current group where `x` is not NA (or some other condition). This is different from what `n()` is supposed to do. 

Instead of `drop_na(mass)` you could also do a `sum(!is.na(mass))` (`!is.na()` evaluates to TRUE (== 1) if x is not missing and FALSE (== 0) if it is)

``` r
library(dplyr, warn.conflicts = FALSE)
library(tidyr)

starwars %>%
  drop_na(mass) %>%
  group_by(species) %>%
  summarise(
    n = sum(!is.na(mass)),
    mass = mean(mass)
  ) %>%
  filter(n > 1,
         mass > 50)
#> # A tibble: 5 x 3
#>   species      n  mass
#>   <chr>    <int> <dbl>
#> 1 Droid        4  69.8
#> 2 Gungan       2  74  
#> 3 Human       22  82.8
#> 4 Mirialan     2  53.1
#> 5 Wookiee      2 124
```

Regarding the `sd()` function: The problem is that you summarise the `mass` vector to the `mean()` and assign it to itself (i.e. overwrite it). So once you call `sd()` for the second time, `mass` only contains a single value per group. A single value cannot have a standard deviation by definition. 

You can get around this by not overwriting `mass`:

``` r
library(dplyr, warn.conflicts = FALSE)
library(tidyr)

starwars %>%
  drop_na(mass) %>%
  group_by(species) %>%
  summarise(
    n = sum(!is.na(mass)),
    sd1 = sd(mass),
    mass_mean = mean(mass),
    sd2 = sd(mass)
  ) %>%
  filter(n > 1, mass_mean > 50)
#> # A tibble: 5 x 5
#>   species      n   sd1 mass_mean   sd2
#>   <chr>    <int> <dbl>     <dbl> <dbl>
#> 1 Droid        4 51.0       69.8 51.0 
#> 2 Gungan       2 11.3       74   11.3 
#> 3 Human       22 19.4       82.8 19.4 
#> 4 Mirialan     2  4.38      53.1  4.38
#> 5 Wookiee      2 17.0      124   17.0
```

**Closed** 2019-10-07 21:27 UTC
