### ISSUE TITLE
change in ntile function versus dplyr 0.8.3

### ISSUE THREAD

**Issue by rogerjbos** [tidyverse/dplyr#5387] opened 2020-07-07 20:07 UTC
The ntile() function in dplyr 1.0.0 gives different results than in version 0.8.3.  Looking at the function code, it has changed a great deal.  I show both functions in my reprex.  ntile_083 scales us as the value of n increases, but ntile1_100 does not, its output is invariant to n (as long as n >= x).  This is a big change in the output.  Was this the intented result?

```r
ntile_083 <- function (x = row_number(), n) {
  len <- sum(!is.na(x))
  if (len == 0L) {
    rep(NA_integer_, length(x))
  } else {
    as.integer(floor(n * (row_number(x) - 1)/len + 1))
  }
}

ntile_100 <- function (x = row_number(), n) {
  if (!missing(x)) {
    x <- row_number(x)
  }
  len <- length(x) - sum(is.na(x))
  n <- as.integer(floor(n))
  if (len == 0L) {
    rep(NA_integer_, length(x))
  } else {
    n_larger <- as.integer(len%%n)
    n_smaller <- as.integer(n - n_larger)
    size <- len/n
    larger_size <- as.integer(ceiling(size))
    smaller_size <- as.integer(floor(size))
    larger_threshold <- larger_size * n_larger
    bins <- if_else(x <= larger_threshold, 
                    (x + (larger_size - 1L)) / larger_size,
                    (x + (-larger_threshold + smaller_size - 1L)) / smaller_size + n_larger)
    as.integer(floor(bins))
  }
}

x <- seq(.1,1,.1)
ntile_083(x, 10)
ntile_083(x, 100)
ntile_083(x, 1000)

ntile_100(x, 10)
ntile_100(x, 100)
ntile_100(x, 1000)
```

**Comment by brianrice2** [comment] 2020-07-15 00:43
I'm admittedly not super familiar with `ntile()` but the results seem weird to me as well. I was testing it with natural sequences and `n = 100` (since it's pretty much percentile at that point), for example:
```
> t <- 10
> ntile_083(1:t, 100)
 [1]  1 11 21 31 41 51 61 71 81 91

# we can match the old results for these simples sequences with seq(),
# which corresponds to the percentile (offset by 1)
> int(floor(seq(1, 100, 100 / t)))
 [1]  1 11 21 31 41 51 61 71 81 91

# but now it just returns seq(1, t)
> ntile(1:t, 100)
 [1]  1  2  3  4  5  6  7  8  9 10
```
and this has me thinking it's a bug. In the [latest commit changes](https://github.com/tidyverse/dplyr/commit/7ca1c044c5d3a7808276440722259a6e7624d15d#diff-32fe91d06a86f79e56dfe6cb218a057b) almost all the new tests have `n < len(x)`, so may have just slipped through when it was rewritten. I think I will poke around the code and see if I can tell what's driving this change.

**Comment by hadley** [comment] 2020-07-15 12:33
It's definitely not a bug. @krlmlr can you please explain.

**Comment by hadley** [comment] 2020-08-28 15:05
Closing because this is deliberate; hopefully Kirill will provide an explanation for you.

**Closed by hadley** 2020-08-28 15:05 UTC

**Comment by krlmlr** [comment] 2020-08-30 04:01
`ntile()` returns

> 1. a rough rank, which breaks the input vector into n buckets.
> 2. The size of the buckets may differ by up to one, larger buckets have lower rank.

The first property means that

- all values are in `1:n`
- for `x[[i1]] < x[[i2]]`, `ntile(x, n)[[i1]] <= ntile(x, n)[[i2]]`

Both implementations fulfill this property.

The second property only holds for dplyr >= 1.0.0, this is what SQL Server and other databases do internally. Do we need to document better?

I see how the results are confusing when `length(unique(x)) < n` . Here, "buckets" are of size 0 or one only; the original implementation disperses the buckets of size one all over the domain, the new implementation aligns them at the beginning. For what use case does this make a difference?
