### ISSUE TITLE
Error: Internal error in `dict_hash_with()`: Dictionary is full.

### ISSUE THREAD

**Issue by fdq09eca** [tidyverse/dplyr#6144] opened 2021-12-31 03:51 UTC
I ran the following code

```r
BEDGRAPHS_fps <- list.files(get_wd(), pattern = ".*\\.copynumber\\.bedgraph$")


get_sample_col <- function(fp) {
            fn = fp |> basename() |> tools::file_path_sans_ext()
            cat(">> start processing", fn, "\n")
            df <- read.table(file = fp, sep = "\t", header = FALSE, col.names = c("chr", "start", "end", "value")) |>
                head(10) |>
                dplyr::rowwise() |>
                dplyr::mutate("{fn}" := tibble::tibble("chr" = chr, "pos" = start:end, "{fn}_value" := value) |> list()) |> 
                dplyr::select(fn |> tidyselect::all_of()) |>
                tidyr::unnest(col = fn |> tidyselect::all_of()) |> 
                dplyr::mutate_if(is.character, as.factor) |> 
                dplyr::distinct(chr, pos, .keep_all = TRUE) # dictionary is full error!!
            cat(">> finish processing", fn, "\n")
            return(df)
        }

sample_cols <- BEDGRAPHS_fps |> lapply(get_sample_col)
```

It ends up with there is one `fp` throw the following error

```
Error: Internal error in `dict_hash_with()`: Dictionary is full.
Run `rlang::last_error()` to see where the error occurred.
```

the `dim()` of the `df` is `913792256, 3`

I saw the relevant issue and seems it has been solved from [therkildsen-lab/data-processing/issues/7](https://github.com/therkildsen-lab/data-processing/issues/7)

so I tried 

```r
devtools::install_github("r-lib/vctrs")
```

but it gave me the following error

```
/usr/bin/gtar: r-lib-vctrs-f9afbff/src: Cannot mkdir: No space left on device
/usr/bin/gtar: r-lib-vctrs-f9afbff/src/type-tibble.c: Cannot open: No such file or directory
```

the above error is just a snippet of it, the original one is much longer but the main reason is still `No space left on device`, which does not make any sense to me, as I have plenty of storage available...

here is my `sessionInfo()`

```r
> sessionInfo()
R version 4.1.0 (2021-05-18)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: CentOS Stream 8

Matrix products: default
BLAS/LAPACK: /rds/bear-apps/2021a/EL8-has/software/FlexiBLAS/3.0.4-GCC-10.3.0/lib64/libflexiblas.so.3.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] ps_1.6.0          prettyunits_1.1.1 rprojroot_2.0.2   crayon_1.4.1     
 [5] withr_2.4.2       R6_2.5.0          lifecycle_1.0.0   magrittr_2.0.1   
 [9] rlang_0.4.11      cachem_1.0.5      cli_2.5.0         curl_4.3.1       
[13] rstudioapi_0.13   remotes_2.4.0     fs_1.5.0          testthat_3.0.2   
[17] callr_3.7.0       ellipsis_0.3.2    desc_1.3.0        devtools_2.4.1   
[21] tools_4.1.0       glue_1.4.2        purrr_0.3.4       pkgload_1.2.1    
[25] fastmap_1.1.0     compiler_4.1.0    processx_3.5.2    pkgbuild_1.2.0   
[29] sessioninfo_1.1.1 memoise_2.0.0     usethis_2.0.1 
```

**Comment by romainfrancois** [comment] 2022-01-03 08:57
@fdq09eca can you simplify the example code and make it reproducible ?

**Comment by hadley** [comment] 2022-04-16 13:03
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2022-04-16 13:03 UTC
Labels: reprex
