### ISSUE TITLE
Joining to sf data.frame fails

### ISSUE THREAD

**Issue by dblodgett-usgs** [tidyverse/dplyr#5022] opened 2020-03-22 21:26 UTC
Reviewing some test failures with:
```r
> packageVersion("dplyr")
[1] ‘0.8.99.9002’
> packageVersion("sf")
[1] ‘0.8.1’
```
I get an error when joining a `data.frame` to an `sf` `data.frame`. I think this is a bug? Reprex below.

``` r
nc <- sf::read_sf(system.file("shape/nc.shp", package="sf"))

attributes <- dplyr::select(sf::st_drop_geometry(nc), CNTY_ID, AREA)

geometry <- dplyr::select(nc, CNTY_ID)

dplyr::left_join(attributes, geometry, by = "CNTY_ID")
#> Error: `nm` must be `NULL` or a character vector the same length as `x`

class(geometry) <- "data.frame"

joined <- dplyr::left_join(attributes, geometry, by = "CNTY_ID")

sf::st_sf(joined)
#> Simple feature collection with 100 features and 2 fields
#> geometry type:  MULTIPOLYGON
#> dimension:      XY
#> bbox:           xmin: -84.32385 ymin: 33.88199 xmax: -75.45698 ymax: 36.58965
#> epsg (SRID):    4267
#> proj4string:    +proj=longlat +datum=NAD27 +no_defs
#> # A tibble: 100 x 3
#>    CNTY_ID  AREA                                                        geometry
#>  *   <dbl> <dbl>                                              <MULTIPOLYGON [°]>
#>  1    1825 0.114 (((-81.47276 36.23436, -81.54084 36.27251, -81.56198 36.27359,…
#>  2    1827 0.061 (((-81.23989 36.36536, -81.24069 36.37942, -81.26284 36.40504,…
#>  3    1828 0.143 (((-80.45634 36.24256, -80.47639 36.25473, -80.53688 36.25674,…
#>  4    1831 0.07  (((-76.00897 36.3196, -76.01735 36.33773, -76.03288 36.33598, …
#>  5    1832 0.153 (((-77.21767 36.24098, -77.23461 36.2146, -77.29861 36.21153, …
#>  6    1833 0.097 (((-76.74506 36.23392, -76.98069 36.23024, -76.99475 36.23558,…
#>  7    1834 0.062 (((-76.00897 36.3196, -75.95718 36.19377, -75.98134 36.16973, …
#>  8    1835 0.091 (((-76.56251 36.34057, -76.60424 36.31498, -76.64822 36.31532,…
#>  9    1836 0.118 (((-78.30876 36.26004, -78.28293 36.29188, -78.32125 36.54553,…
#> 10    1837 0.124 (((-80.02567 36.25023, -80.45301 36.25709, -80.43531 36.55104,…
#> # … with 90 more rows
```

<sup>Created on 2020-03-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment] 2020-03-22 23:19
Duplicate of #4917

**Closed by hadley** 2020-03-22 23:19 UTC
