### ISSUE TITLE
n() computes wrong number of rows inside a pmap

### ISSUE THREAD

**Issue by burkovae** [tidyverse/dplyr#2623] opened 2017-04-07 09:27 UTC
When computing number of rows of a nested `tibble` inside `pmap` using `n()` the returned results is wrong (when compare to `nrow(.)`)

(Sorry, for unstyled code, but somehow github messes it up)

data_frame(var1 = factor(sample(letters[1:3], replace = T, size = 50)),
           var2 = sample(letters[5:8], replace = T, size = 50),
           var3 = sample(letters[15:25], replace = T, size = 50)) %>%
  group_by(var1) %>%
  nest() %>%
  mutate(.m = 5, .sd = 5) %>%
  mutate(res = pmap(list(data, .m, .sd), function(df, m, s) {
    # Here is the bug:
    # nn should be the same as nrows
    # and, if stepping in with the debuger and evaluation the statement, it is 
    # indeed the case. 
    #
    # However, the return result shows nn == 3 , i.e. the number of groups from
    # parent data.frame
    df %>%
      mutate(nn = n(),
             nrows = nrow(.))
      #mutate(random = rnorm(n(), m, s))
  })) %>%
  unnest()

**Comment by lionel-** [comment] 2017-04-07 09:28
duplicate of https://github.com/tidyverse/dplyr/issues/2080

**Closed by lionel-** 2017-04-07 09:28 UTC
