### ISSUE TITLE
group by unique ID vs rowwise - the latter produces a warning

### ISSUE THREAD

**Issue by mkwiecinski** [tidyverse/dplyr#3281] opened 2018-01-02 22:07 UTC
I would expect the following code to behave similarly, irrespectively whether I use rowwise() or group_by(ID) . Logically, they are the same, right? But with rowwise() I get warnings.

I believe this is because during execution of the `do` call on the first line, (at least) the `groups` variable is being converted to a factor. Only when a new value arrives to a column when binding another row during rowwise operations, the column gets converted to a character and the warning is issued.

This is not present in scenario with group_by(ID). Is this correct behaviour?

Possibly this somehow relates to issue #2145 ?

```r
library(tidyverse)
#> Loading tidyverse: ggplot2
#> Loading tidyverse: tibble
#> Loading tidyverse: tidyr
#> Loading tidyverse: readr
#> Loading tidyverse: purrr
#> Loading tidyverse: dplyr
#> Conflicts with tidy packages ----------------------------------------------
#> filter(): dplyr, stats
#> lag():    dplyr, stats

df <- data_frame(
  groups = c("a","b","c")
  , args = c(1,2,3)
) %>% rowid_to_column(., "ID")

foo <- function(x){
  data_frame(foo_result = x^2)
}

df %>% 
  rowwise() %>%
  do(
    cbind(. , foo(.$args))
  )
#> Warning in bind_rows_(x, .id): Unequal factor levels: coercing to character
#> Warning in bind_rows_(x, .id): binding character and factor vector,
#> coercing into character vector

#> Warning in bind_rows_(x, .id): binding character and factor vector,
#> coercing into character vector

#> Warning in bind_rows_(x, .id): binding character and factor vector,
#> coercing into character vector
#> Source: local data frame [3 x 4]
#> Groups: <by row>
#> 
#> # A tibble: 3 x 4
#>      ID groups  args foo_result
#> * <int>  <chr> <dbl>      <dbl>
#> 1     1      a     1          1
#> 2     2      b     2          4
#> 3     3      c     3          9

df %>% 
  group_by(ID) %>%
  do(
    cbind(. , foo(.$args))
  )
#> # A tibble: 3 x 4
#> # Groups:   ID [3]
#>      ID groups  args foo_result
#>   <int>  <chr> <dbl>      <dbl>
#> 1     1      a     1          1
#> 2     2      b     2          4
#> 3     3      c     3          9
```

**Comment by batpigandme** [comment] 2018-01-02 22:39
Hi @mkwiecinski ,

Would you be able to make this into a self-contained, minimal reproducible example (aka a [reprex](https://www.tidyverse.org/help/#reprex))?

It will be much easier to troubleshoot if we can be sure we're working with the same pieces/code.

**Comment by cderv** [comment] 2018-01-03 07:04
I think the issue comes from `cbind` that do not handle well a rowwise data.frame. If I use the `cbind` from `dplyr` (i.e `bind_cols`), it works ok with no warning. Not sure it comes from `dplyr` and that rowwised and grouped tibble should behave the same... 

Why use `do` and `cbind` ? `mutate` or `*_join` functions do not match your use case ? Often there is an another better option that `do`, but it could lie in `purrr`

Example code :
``` r
library(tidyverse)

df <- data_frame(
  groups = c("a","b","c")
  , args = c(1,2,3)
) %>% rowid_to_column(., "ID")

foo <- function(x){
  data_frame(foo_result = x^2)
}

df %>% 
  rowwise() %>%
  do(
    bind_cols(. , foo(.$args))
  )
#> Source: local data frame [3 x 4]
#> Groups: <by row>
#> 
#> # A tibble: 3 x 4
#>      ID groups  args foo_result
#> * <int>  <chr> <dbl>      <dbl>
#> 1     1      a     1          1
#> 2     2      b     2          4
#> 3     3      c     3          9



df %>% 
  group_by(ID) %>%
  do(
    cbind(. , foo(.$args))
  )
#> # A tibble: 3 x 4
#> # Groups:   ID [3]
#>      ID groups  args foo_result
#>   <int>  <chr> <dbl>      <dbl>
#> 1     1      a     1          1
#> 2     2      b     2          4
#> 3     3      c     3          9
```

Created on 2018-01-03 by the [reprex package](http://reprex.tidyverse.org) (v0.1.1.9000).

**Comment by mkwiecinski** [comment] 2018-01-03 07:53
Both solutions (`bind_rows`, `mutate`+`join`) would of course work in this or my full scenario, thank you!

I started with `cbind` and observed this unexpected behaviour. Unexpected especially if it is induced by a function from base packages, as you suggest. 

If you believe that rowwised and grouped tibble should not necessarily behave the same then it might be closed.

**Comment by batpigandme** [comment] 2018-01-03 10:31
Thanks for the reprex, and your help, @cderv. I'm honestly not sure about the "should" statements here, let me do a little digging (unless @krlmlr and/or @hadley has a quick yes/no).

**Comment by krlmlr** [comment] 2018-01-03 10:33
tibble has improvements for `cbind()` in the most recent CRAN version, from the output I'm guessing you're using an older version?

**Comment by krlmlr** [comment] 2018-01-03 10:34
Wrong, `cbind()` just doesn't works with tibbles, please use `bind_cols()`. The tibble improvement I mentioned was about *avoiding* use of `cbind()` for `tibble::add_column()`.

**Comment by mkwiecinski** [comment] 2018-01-03 10:37
Now that you mentioned an update, actually, I was using this code without errors until I updated tidyverse just yesterday, so the tibble "improvement" indeed seems related to this warnings. 

Do not use cbind - understood!

**Comment by krlmlr** [comment] 2018-01-03 10:40
Updating tidyverse doesn't always update tibble. What is your currently installed tibble version?

**Comment by mkwiecinski** [comment] 2018-01-03 10:46
1.3.4

**Comment by romainfrancois** [comment] 2018-05-29 09:47
`group_by()` + `do()` and `rowwise()` + `do()` are not stricly equivalent because of the handling of list columns. 

For example with that tibble: 

```
df <- tibble( x = 1:2, y = list(1:5, 1:10))
```

in the first iteration:
 - a rowwise + do sees `list( x = 1, y = 1:5 )` 
 - a group_by(x) + do sees `tibble( x = 1, y = list(1:5) )`

So with your data: 

```
df <- data_frame(
  groups = c("a","b","c"), args = c(1,2,3)
) %>% rowid_to_column(., "ID")
```

the rowwise case expands to 

```
cbind( list(groups = "a", args = 1), data_frame(x = 1) )
```

And `cbind` uses `stringsAsFactors = TRUE` by default, so `groups` becomes a factor, you can fix this by using stringsAsFactors = FALSE, or as mentioned above use `bind_cols`, or maybe using a `mutate()` : 

``` r
library(tidyverse)

df <- data_frame(
  groups = c("a","b","c"), args = c(1,2,3)
) %>% rowid_to_column(., "ID")

foo <- function(x){
  data_frame(foo_result = x^2)
}

df %>% 
  rowwise() %>%
  do(
    { print(.); cbind(. , foo(.$args)) ; }
  )
#> $ID
#> [1] 1
#> 
#> $groups
#> [1] "a"
#> 
#> $args
#> [1] 1
#> 
#> $ID
#> [1] 2
#> 
#> $groups
#> [1] "b"
#> 
#> $args
#> [1] 2
#> 
#> $ID
#> [1] 3
#> 
#> $groups
#> [1] "c"
#> 
#> $args
#> [1] 3
#> Warning in bind_rows_(x, .id): Unequal factor levels: coercing to character
#> Warning in bind_rows_(x, .id): binding character and factor vector,
#> coercing into character vector

#> Warning in bind_rows_(x, .id): binding character and factor vector,
#> coercing into character vector

#> Warning in bind_rows_(x, .id): binding character and factor vector,
#> coercing into character vector
#> Source: local data frame [3 x 4]
#> Groups: <by row>
#> 
#> # A tibble: 3 x 4
#>      ID groups  args foo_result
#> * <int> <chr>  <dbl>      <dbl>
#> 1     1 a          1          1
#> 2     2 b          2          4
#> 3     3 c          3          9

df %>% 
  rowwise() %>%
  do(
    cbind(. , foo(.$args), stringsAsFactors = FALSE)
  )
#> Source: local data frame [3 x 4]
#> Groups: <by row>
#> 
#> # A tibble: 3 x 4
#>      ID groups  args foo_result
#> * <int> <chr>  <dbl>      <dbl>
#> 1     1 a          1          1
#> 2     2 b          2          4
#> 3     3 c          3          9

df %>% 
  rowwise() %>%
  do(
    bind_cols(. , foo(.$args))
  )
#> Source: local data frame [3 x 4]
#> Groups: <by row>
#> 
#> # A tibble: 3 x 4
#>      ID groups  args foo_result
#> * <int> <chr>  <dbl>      <dbl>
#> 1     1 a          1          1
#> 2     2 b          2          4
#> 3     3 c          3          9

df %>% 
  rowwise() %>%
  mutate( foo_result = foo(args)$foo_result )
#> Source: local data frame [3 x 4]
#> Groups: <by row>
#> 
#> # A tibble: 3 x 4
#>      ID groups  args foo_result
#>   <int> <chr>  <dbl>      <dbl>
#> 1     1 a          1          1
#> 2     2 b          2          4
#> 3     3 c          3          9
```

In any case, I'll close this now as it is intended that rowwise + do is not equivalent to group_by + do

**Closed by romainfrancois** 2018-05-29 09:47 UTC
Labels: data frame
