### ISSUE TITLE
bind_rows cannot bind data.frames containing data.frame columns...

### ISSUE THREAD

**Issue by dan-reznik** [tidyverse/dplyr#4226] opened 2019-02-25 23:05 UTC
bind_rows() fails for data.frame's w/ one or more data.frame columns (stumbled upon this error when jsonlite::fromJSON decoded a json into such a structure). here's a minimalist example:

```r
library(dplyr)
t1<-tibble(x=tibble(a=1:3,b=5:7))
bind_rows(t1) # produces error
```
notice that if the data.frame column is converted to a list of named lists, bind_rows works
```r
library(purrr)
t1%>%mutate(x=x%>%transpose)%>%bind_rows
#> no problem here
```
p.s. -- this error propagates to purrr::map_df code which I believe calls bind_rows.

**Comment by romainfrancois** [comment] 2019-03-04 12:56
For now the alternative is to use `vctrs::vec_rbind()` which deals with data frame columns.

**Comment by hadley** [comment] 2019-05-27 15:51
Duplicate of #3630

**Closed by hadley** 2019-05-27 15:51 UTC
Labels: data frame, vector

**Comment by deliciouslytyped** [comment] 2019-05-29 15:48
I ran into this but `vec_rbind` doesn't seem to work for me.
```
> vec_rbind(ii$json[[4]],ii$json[[5]])
Error in rep_len(NA_integer_, n) : invalid 'length.out' value

> vec_rbind(ii$json[[4]],ii$json[[5]])
Error in rep_len(NA_integer_, n) : invalid 'length.out' value
```
I haven't figured out a decent way to dump a description of my data but I'm also using a column of objects created with fromJSON (using tidyverse with reticulate + a pandas sql query (I love how well this insane stack works)).
