### ISSUE TITLE
summarize_at() fails on database data sources

### ISSUE THREAD

**Issue by JohnMount** [tidyverse/dplyr#3399] opened 2018-03-06 20:16 UTC
`summarize_at()` fails on database data sources.  Also the `one_of()`'s behavior contradicts the `dplyr` documentation.

```r
library("dplyr")
my_db <- DBI::dbConnect(RSQLite::SQLite(),
                        ":memory:")
RSQLite::initExtension(my_db)

dLocal <- data.frame(x = c(1,2,2),
                     y = c(3,5,NA),
                     z = c(NA,'a','b'),
                     stringsAsFactors = FALSE)
dRemote <- dplyr::copy_to(my_db, dLocal, "dRemote")

var_names = c("x", "y", "z")


# local

# works
summarize_at(dLocal, var_names, funs(sum(dplyr::if_else(is.na(.), 1.0, 0.0), na.rm = TRUE)))

# fails, yet help(one_of) says: one_of(): variables in character vector.
summarize_at(dLocal, one_of(var_names), funs(sum(dplyr::if_else(is.na(.), 1.0, 0.0), na.rm = TRUE)))
#  Error: Variable context not set

# works
summarize_at(dLocal, vars(var_names), funs(sum(dplyr::if_else(is.na(.), 1.0, 0.0), na.rm = TRUE)))


# remote

# fails
summarize_at(dRemote, var_names, funs(sum(dplyr::if_else(is.na(.), 1.0, 0.0), na.rm = TRUE)))
# Error in dplyr::if_else(is.na(x), 1, 0) : object 'x' not found 

# fails
summarize_at(dRemote, one_of(var_names), funs(sum(dplyr::if_else(is.na(.), 1.0, 0.0), na.rm = TRUE)))
#  Error: Variable context not set

# fails
summarize_at(dRemote, vars(var_names), funs(sum(dplyr::if_else(is.na(.), 1.0, 0.0), na.rm = TRUE)))
# Error in dplyr::if_else(is.na(x), 1, 0) : object 'x' not found 

DBI::dbDisconnect(my_db)
```

Note simpler expressions (such as just `mean(.)`) appear to work.

Also note `tidyselect` does not show up on `sessionInfo()` (though I am up to date on that).

```
> sessionInfo()
R version 3.4.3 (2017-11-30)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.3

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.4/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] bindrcpp_0.2 dplyr_0.7.4 

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.15     dbplyr_1.2.1     digest_0.6.15    assertthat_0.2.0 R6_2.2.2         DBI_0.8          magrittr_1.5    
 [8] RSQLite_2.0      pillar_1.2.1     rlang_0.2.0      blob_1.1.0       tools_3.4.3      bit64_0.9-7      glue_1.2.0      
[15] bit_1.1-12       yaml_2.1.17      compiler_3.4.3   pkgconfig_2.0.1  memoise_1.1.0    bindr_0.1        tibble_1.4.2    

> packageVersion("tidyselect")

[1] ‘0.2.4’
```

**Comment by hadley** [comment] 2018-05-20 14:09
I think most of the issues are because you forgot to use `vars()`, which is required with `summarise_at()`. The other issue is a duplicate of #3500 

Minimal reprex:

``` r
library(dplyr, warn.conflicts = FALSE)
mf <- dbplyr::memdb_frame(
  x = c(1,2,2),
  y = c(3,5,NA),
  z = c(NA,'a','b')
)

var_names <- c("x", "y", "z")
summarize_at(mf, vars(one_of(var_names)), funs(coalesce(., 0)))
#> Warning in result_fetch(res@ptr, n = n): Column `z`: mixed type, first seen
#> values of type real, coercing other values of type string
#> # Source:   lazy query [?? x 3]
#> # Database: sqlite 3.22.0 [:memory:]
#>       x     y     z
#>   <dbl> <dbl> <dbl>
#> 1     1     3     0
#> 2     2     5     0
#> 3     2     0     0
summarize_at(mf, vars(one_of(var_names)), funs(dplyr::coalesce(., 0)))
#> Error in dots_list(...): object 'x' not found
```

Created on 2018-05-20 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Closed by hadley** 2018-05-20 14:09 UTC
Labels: database
