### ISSUE TITLE
mutate_at: Unexpected result when lambda expression contains columns selected in .vars

### ISSUE THREAD

**Issue by MilesMcBain** [tidyverse/dplyr#4537] opened 2019-08-19 06:56 UTC
This is related to #4183, which established that bare column names should work in lambda expressions used within `mutate_at`. I have noticed the mutation does not proceed as expected when columns are referenced within a lambda in `.funs` that are also selected in `.vars`

My reprex follows, note I am on R 3.6.0 at work, hence the initial warning.

``` r
library(dplyr)
#> Warning: package 'dplyr' was built under R version 3.6.1
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

dat <-
tibble::tribble(
           ~H3Index,            ~X2016,           ~X2021,            ~X2026,            ~X2031,            ~X2036,            ~X2041,
  "88be8d1243fffff", 0.554674821670153, 0.30817397383382, 0.390390984024883, 0.725724408687073, 0.378039373567343, 0.864710747001625,
  "88be8d1249fffff",  4.93014169446379, 11.8542228050832,  1.41323711017703,  3.40709044303009,  2.82178445240587,  1.42924073709316,
  "88be8d124bfffff",   1.1367294908696, 1.46701071643466,  5.07855833984479,  1.99588807484615,  6.77484624074028,  1.95935238342599,
  "88be8d124dfffff", 0.886659748128008,  7.1976989241869,  1.24043900977693,  1.09660666722578,  3.40860262321108,  1.05869844606606,
  "88be8d1251fffff",  2.12844246565062, 2.16878490050055,  4.60619187678171,  3.12576425156238,   1.3985407170482,  3.26692693915042,
  "88be8d1259fffff",  2.10837410303155,  2.1577985315665,  1.69719024725979,  2.79050496707472,   1.8636362095328,  3.99896183929526
  )

## According to https://github.com/tidyverse/dplyr/issues/4183
## This should work:
dat %>%
mutate_at(.vars = vars(starts_with("X")),
          .funs = ~ . / X2016)
#> # A tibble: 6 x 7
#>   H3Index         X2016  X2021 X2026 X2031 X2036 X2041
#>   <chr>           <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl>
#> 1 88be8d1243fffff     1  0.308 0.390 0.726 0.378 0.865
#> 2 88be8d1249fffff     1 11.9   1.41  3.41  2.82  1.43 
#> 3 88be8d124bfffff     1  1.47  5.08  2.00  6.77  1.96 
#> 4 88be8d124dfffff     1  7.20  1.24  1.10  3.41  1.06 
#> 5 88be8d1251fffff     1  2.17  4.61  3.13  1.40  3.27 
#> 6 88be8d1259fffff     1  2.16  1.70  2.79  1.86  4.00

## But actually only the X2016 column is modified.
## Compare with:
dat %>%
mutate_at(.vars = vars(starts_with("X")),
          .funs = ~ . - X2016)
#> # A tibble: 6 x 7
#>   H3Index         X2016  X2021 X2026 X2031 X2036 X2041
#>   <chr>           <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl>
#> 1 88be8d1243fffff     0  0.308 0.390 0.726 0.378 0.865
#> 2 88be8d1249fffff     0 11.9   1.41  3.41  2.82  1.43 
#> 3 88be8d124bfffff     0  1.47  5.08  2.00  6.77  1.96 
#> 4 88be8d124dfffff     0  7.20  1.24  1.10  3.41  1.06 
#> 5 88be8d1251fffff     0  2.17  4.61  3.13  1.40  3.27 
#> 6 88be8d1259fffff     0  2.16  1.70  2.79  1.86  4.00

## When X2016 is excluded from vars, it works:
dat %>%
mutate_at(.vars = vars(starts_with("X202")),
          .funs = ~ . - X2016)
#> # A tibble: 6 x 7
#>   H3Index         X2016   X2021  X2026 X2031 X2036 X2041
#>   <chr>           <dbl>   <dbl>  <dbl> <dbl> <dbl> <dbl>
#> 1 88be8d1243fffff 0.555 -0.247  -0.164 0.726 0.378 0.865
#> 2 88be8d1249fffff 4.93   6.92   -3.52  3.41  2.82  1.43 
#> 3 88be8d124bfffff 1.14   0.330   3.94  2.00  6.77  1.96 
#> 4 88be8d124dfffff 0.887  6.31    0.354 1.10  3.41  1.06 
#> 5 88be8d1251fffff 2.13   0.0403  2.48  3.13  1.40  3.27 
#> 6 88be8d1259fffff 2.11   0.0494 -0.411 2.79  1.86  4.00
```

<sup>Created on 2019-08-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by MilesMcBain** [comment] 2019-08-19 07:16
Oh I see now this is happening because `mutate_at` processes the mutations in sequence, as mentioned in https://github.com/tidyverse/dplyr/issues/4517. That was a bit unexpected.

So this works how I originally expected:

```r
dat %>%
mutate_at(.vars = rev(vars(starts_with("X"))),
          .funs = ~ . - X2016)
```

**Comment by antaldaniel** [comment] 2019-10-19 11:10
I looked up this issue, and it is not because of tidyselect 
```
tb <- tibble ( 
  AT = c(1,2,3,4,5), 
  HU = c(3,4,5,6,7), 
  SK = c(4,5,6,1,2))
```
The following result in the same unexpected result, i.e. only the first column being mutated:
```
tb %>% mutate_at ( vars (one_of("AT", "HU", "SK")), ~./AT)
tb %>% mutate_at ( vars ( c("AT", "HU", "SK")), ~./AT)
tb %>% mutate_at ( vars (1:3), ~./AT)

# A tibble: 5 x 3
     AT    HU    SK
  <dbl> <dbl> <dbl>
1     1     3     4
2     1     4     5
3     1     5     6
4     1     6     1
5     1     7     2
```
And this one mutates all columns:
```
tb %>% mutate_at ( vars (rev(one_of("AT", "HU", "SK"))), ~./AT)](url)
# A tibble: 5 x 3
     AT    HU    SK
  <dbl> <dbl> <dbl>
1     1  3     4   
2     1  2     2.5 
3     1  1.67  2   
4     1  1.5   0.25
5     1  1.4   0.4 
```

Expressing numeric variables as a percentage of one of them is a quiet frequent task, and this is an unexpected behavior, I think.  Given that the reverse formulation does not change the results, I could expect a warning when this happens, though I do not understand exactly what causes it.

**Comment by cderv** [comment] 2019-10-19 13:19
@MilesMcBain I think you are right. `mutate` operate in order. the help page give some hints the `funs` is evaluated each time it is applied. That is why `X2016` applied on second column is applied with new value. When using an existing column in a formula with `mutate_*`, and if this column is in the selection, the order of column matters.

 I think it needs to be put last to be applied on all column. That is what happens in the last example from @antaldaniel . 

 I think applying `rev` on `vars` does not do what you think. 
``` r
library(dplyr)
#> 
#> Attachement du package : 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
vars(starts_with("X"))
#> <list_of<quosure>>
#> 
#> [[1]]
#> <quosure>
#> expr: ^starts_with("X")
#> env:  global
rev(vars(starts_with("X")))
#> <list_of<quosure>>
#> 
#> [[1]]
#> <quosure>
#> expr: ^starts_with("X")
#> env:  global
```

`vars` create a list of quosure. Here of length one. so rev does nothing. 

Order of column can be change in pipe also. 
``` r
library(dplyr)
#> 
#> Attachement du package : 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
dat <-
  tibble::tribble(
    ~H3Index,            ~X2016,           ~X2021,            ~X2026,            ~X2031,            ~X2036,            ~X2041,
    "88be8d1243fffff", 0.554674821670153, 0.30817397383382, 0.390390984024883, 0.725724408687073, 0.378039373567343, 0.864710747001625,
    "88be8d1249fffff",  4.93014169446379, 11.8542228050832,  1.41323711017703,  3.40709044303009,  2.82178445240587,  1.42924073709316,
    "88be8d124bfffff",   1.1367294908696, 1.46701071643466,  5.07855833984479,  1.99588807484615,  6.77484624074028,  1.95935238342599,
    "88be8d124dfffff", 0.886659748128008,  7.1976989241869,  1.24043900977693,  1.09660666722578,  3.40860262321108,  1.05869844606606,
    "88be8d1251fffff",  2.12844246565062, 2.16878490050055,  4.60619187678171,  3.12576425156238,   1.3985407170482,  3.26692693915042,
    "88be8d1259fffff",  2.10837410303155,  2.1577985315665,  1.69719024725979,  2.79050496707472,   1.8636362095328,  3.99896183929526
  )
# if at the end it applies on all 
dat %>%
  select(everything(), -X2016, X2016) %>%
  mutate_at(.vars = vars(starts_with("X")),
            .funs = ~ . - X2016)
#> # A tibble: 6 x 7
#>   H3Index           X2021  X2026  X2031  X2036  X2041 X2016
#>   <chr>             <dbl>  <dbl>  <dbl>  <dbl>  <dbl> <dbl>
#> 1 88be8d1243fffff -0.247  -0.164  0.171 -0.177  0.310     0
#> 2 88be8d1249fffff  6.92   -3.52  -1.52  -2.11  -3.50      0
#> 3 88be8d124bfffff  0.330   3.94   0.859  5.64   0.823     0
#> 4 88be8d124dfffff  6.31    0.354  0.210  2.52   0.172     0
#> 5 88be8d1251fffff  0.0403  2.48   0.997 -0.730  1.14      0
#> 6 88be8d1259fffff  0.0494 -0.411  0.682 -0.245  1.89      0

# if not at the end, it applies ok until it is modified
dat %>%
  select(H3Index, X2021:X2026, X2016, X2031:X2041) %>%
  mutate_at(.vars = vars(starts_with("X")),
            .funs = ~ . - X2016)
#> # A tibble: 6 x 7
#>   H3Index           X2021  X2026 X2016 X2031 X2036 X2041
#>   <chr>             <dbl>  <dbl> <dbl> <dbl> <dbl> <dbl>
#> 1 88be8d1243fffff -0.247  -0.164     0 0.726 0.378 0.865
#> 2 88be8d1249fffff  6.92   -3.52      0 3.41  2.82  1.43 
#> 3 88be8d124bfffff  0.330   3.94      0 2.00  6.77  1.96 
#> 4 88be8d124dfffff  6.31    0.354     0 1.10  3.41  1.06 
#> 5 88be8d1251fffff  0.0403  2.48      0 3.13  1.40  3.27 
#> 6 88be8d1259fffff  0.0494 -0.411     0 2.79  1.86  4.00
```

<sup>Created on 2019-10-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Hope it helps understand current behavior. I agree this is easy to do some mistakes when it is not know.

**Comment by romainfrancois** [comment] 2019-11-26 15:00
That's an example of what #4586 will enable: 

``` r
library(dplyr, warn.conflicts = FALSE)

dat <-
  tibble::tribble(
    ~H3Index,            ~X2016,           ~X2021,            ~X2026,            ~X2031,            ~X2036,            ~X2041,
    "88be8d1243fffff", 0.554674821670153, 0.30817397383382, 0.390390984024883, 0.725724408687073, 0.378039373567343, 0.864710747001625,
    "88be8d1249fffff",  4.93014169446379, 11.8542228050832,  1.41323711017703,  3.40709044303009,  2.82178445240587,  1.42924073709316,
    "88be8d124bfffff",   1.1367294908696, 1.46701071643466,  5.07855833984479,  1.99588807484615,  6.77484624074028,  1.95935238342599,
    "88be8d124dfffff", 0.886659748128008,  7.1976989241869,  1.24043900977693,  1.09660666722578,  3.40860262321108,  1.05869844606606,
    "88be8d1251fffff",  2.12844246565062, 2.16878490050055,  4.60619187678171,  3.12576425156238,   1.3985407170482,  3.26692693915042,
    "88be8d1259fffff",  2.10837410303155,  2.1577985315665,  1.69719024725979,  2.79050496707472,   1.8636362095328,  3.99896183929526
  )

dat %>%
  mutate(across(starts_with("X"), ~ .x / X2016))
#> # A tibble: 6 x 7
#>   H3Index         X2016 X2021 X2026 X2031 X2036 X2041
#>   <chr>           <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#> 1 88be8d1243fffff     1 0.556 0.704 1.31  0.682 1.56 
#> 2 88be8d1249fffff     1 2.40  0.287 0.691 0.572 0.290
#> 3 88be8d124bfffff     1 1.29  4.47  1.76  5.96  1.72 
#> 4 88be8d124dfffff     1 8.12  1.40  1.24  3.84  1.19 
#> 5 88be8d1251fffff     1 1.02  2.16  1.47  0.657 1.53 
#> 6 88be8d1259fffff     1 1.02  0.805 1.32  0.884 1.90
```

<sup>Created on 2019-11-26 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9000)</sup>

**Comment by hadley** [comment] 2019-12-10 22:43
Closing this since it appears that it will be resolved by `across()`

**Closed by hadley** 2019-12-10 22:43 UTC

**Comment by hadley** [comment] 2019-12-10 22:48
Oh and it's a duplicate of #4517
