### ISSUE TITLE
lead/lag throw warning when used with other conditions in filter

### ISSUE THREAD

**Issue by jschelbert** [tidyverse/dplyr#3746] opened 2018-08-10 07:12 UTC
I've noticed a strange warning that gets thrown when I use `lead`/`lag` in a filter statement together with some other conditions. I could use `dplyr::lag` to omit the warning but I'm wondering why I get the warning despite having only loaded dplyr.

``` r
library(dplyr)
#> 
#> Attache Paket: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

df <- data.frame(a = 1:10, b = rep(letters[1:5], 2))

df %>% filter(lead(b) == "b")
#>   a b
#> 1 1 a
#> 2 6 a

df %>% filter(a == 6, lead(b) == "b")
#> Warning in filter_impl(.data, quo): hybrid evaluation forced for `lead`.
#> Please use dplyr::lead() or library(dplyr) to remove this warning.
#>   a b
#> 1 6 a

df %>% filter(a == 7, lag(b) == "a")
#> Warning in filter_impl(.data, quo): hybrid evaluation forced for `lag`.
#> Please use dplyr::lag() or library(dplyr) to remove this warning.
#>   a b
#> 1 7 b

df %>% filter(a == 7, dplyr::lag(b) == "a")
#>   a b
#> 1 7 b
```

Created on 2018-08-10 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by romainfrancois** [comment] 2018-08-13 08:05
Duplicate of #3750 or the other way around, but I've seen #3750 first. All fixed in the branch I'm currently working on.

**Closed by romainfrancois** 2018-08-13 08:05 UTC
