### ISSUE TITLE
rows_update function fails when data has duplicated matching ids

### ISSUE THREAD

**Issue by deschen1** [tidyverse/dplyr#5723] opened 2021-02-01 15:55 UTC
When updating rows in a data frame with `rows_update`, if currently fails if the data frame has duplicated matching ids. However, this should be of no concern to the `rows_update` function since it's purpose (to my understanding) is to update certain values in the data based on finding the id. And if the id occurs several times in the data, the `rows_update` should just update them all.
At least I'd say there shoudl be an optional parameter in the function that let the user decide if they want to see an error or have the matching happen several times.

```
df <- data.frame(id = c("A", "A", "B"),
                 x  = c(1, 2, 3))

lookup <- data.frame(id = c("A", "B"),
                     x = c(9, 8))

df %>%
  rows_update(., lookup, by = "id")
```

This throws an error:

`Error: `x` key values are not unique.`

Expected outcome:

```
  id x
1  A 9
2  A 9
3  B 8
```

**Comment by gregorp** [comment] 2021-04-13 04:27
I think this is a duplicate of #5553 .

**Closed** 2021-04-19 13:32 UTC
