### ISSUE TITLE
Confusing deprecation warning for slice when applied to vector or list

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [tidyverse/dplyr#5222] opened 2020-05-11 09:27 UTC
Applying `slice()` to a non-data frame gives an error, which makes sense. However, the deprecation warning is confusing I think, as it says "use `slice()` instead" which is already what I'm using.

I'll provide two separate reprexes for a vector and a list so that the deprecation message is printed in both:

- character vector:

``` r
suppressMessages(library(dplyr))
packageVersion("dplyr")
#> [1] '0.8.99.9002'

v <- c("hi", "hello")

v %>% slice(1)
#> Warning: `slice_()` is deprecated as of dplyr 0.7.0.
#> Please use `slice()` instead.
#> This warning is displayed once every 8 hours.
#> Call `lifecycle::last_warnings()` to see where this warning was generated.
#> Error in UseMethod("slice_"): no applicable method for 'slice_' applied to an object of class "character"
```

<sup>Created on 2020-05-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

- list:

``` r
suppressMessages(library(dplyr))
packageVersion("dplyr")
#> [1] '0.8.99.9002'

l <- list("hi", "hello")

l %>% slice(1)
#> Warning: `slice_()` is deprecated as of dplyr 0.7.0.
#> Please use `slice()` instead.
#> This warning is displayed once every 8 hours.
#> Call `lifecycle::last_warnings()` to see where this warning was generated.
#> Error in UseMethod("slice_"): no applicable method for 'slice_' applied to an object of class "list"
```

<sup>Created on 2020-05-11 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment] 2020-05-11 20:20
Duplicate of #5083

**Closed by hadley** 2020-05-11 20:20 UTC
Labels: feature, verbs :running_woman:
