### ISSUE TITLE
IDate gets converted to double after left_join

### ISSUE THREAD

**Issue by fedassembly** [tidyverse/dplyr#6687] opened 2023-02-06 11:21 UTC
An`IDate` join key gets converted to `double` after a `left_join` resulting in an error if trying to join with another `IDate` in a downstream join.

<details>

```
library(data.table)
library(dplyr)
idates1 <- seq(as.IDate("2017-06-05"), as.IDate("2021-04-26"), by = "1 weeks")
idates2 <- seq(as.IDate("2017-06-05"), as.IDate("2021-04-26"), by = "1 weeks")
dt1 <- data.table(
  week = idates1,
  value1 = c(1:length(idates1))
)
dt2 <- data.table(
  week = idates2,
  value2 = c(1:length(idates2))
)
typeof(dt1$week)  # `integer`
typeof(dt2$week)  # `integer`
dt12 <- dt1 %>%
  left_join(dt2)
typeof(dt12$week)  # `double`
idates3 <- seq(as.IDate("2017-06-05"), as.IDate("2021-04-26"), by = "1 weeks")
dt3 <- data.table(
  week = idates3,
  value3 = c(1:length(idates3))
)
left_join(dt12, dt3)  # Error in `vctrs::vec_locate_matches()`: ! `x` and `y` should have the same type.
```

```
R version 4.2.1 (2022-06-23)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.3.1

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_1.1.0       data.table_1.14.6

loaded via a namespace (and not attached):
 [1] fansi_1.0.4      withr_2.5.0      utf8_1.2.3       R6_2.5.1         lifecycle_1.0.3  magrittr_2.0.3   pillar_1.8.1     rlang_1.0.6     
 [9] cli_3.6.0        rstudioapi_0.14  vctrs_0.5.2      generics_0.1.3   tools_4.2.1      glue_1.6.2       compiler_4.2.1   pkgconfig_2.0.3 
[17] tidyselect_1.2.0 tibble_3.1.8    
```

</details>

**Comment by hadley** [comment] 2023-02-06 14:28
Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by fedassembly** [comment] 2023-02-06 14:40
Sorry. Here's the reprex.

```
library(data.table)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:data.table':
#> 
#>     between, first, last
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
idates1 <- seq(as.IDate("2017-06-05"), as.IDate("2021-04-26"), by = "1 weeks")
idates2 <- seq(as.IDate("2017-06-05"), as.IDate("2021-04-26"), by = "1 weeks")
dt1 <- data.table(
  week = idates1,
  value1 = c(1:length(idates1))
)
dt2 <- data.table(
  week = idates2,
  value2 = c(1:length(idates2))
)
typeof(dt1$week)
#> [1] "integer"
typeof(dt2$week)
#> [1] "integer"
dt12 <- dt1 %>%
  left_join(dt2)
#> Joining with `by = join_by(week)`
typeof(dt12$week)
#> [1] "double"
idates3 <- seq(as.IDate("2017-06-05"), as.IDate("2021-04-26"), by = "1 weeks")
dt3 <- data.table(
  week = idates3,
  value3 = c(1:length(idates3))
)
left_join(dt12, dt3)
#> Joining with `by = join_by(week)`
#> Error in `vctrs::vec_locate_matches()`:
#> ! `x` and `y` should have the same type.
#> ℹ In file 'match-joint.c' at line 239.
#> ℹ This is an internal error that was detected in the vctrs package.
#>   Please report it at <https://github.com/r-lib/vctrs/issues> with a reprex (<https://https://tidyverse.org/help/>) and the full backtrace.

#> Backtrace:
#>     ▆
#>  1. ├─dplyr::left_join(dt12, dt3)
#>  2. ├─dplyr:::left_join.data.frame(dt12, dt3)
#>  3. │ └─dplyr:::join_mutate(...)
#>  4. │   └─dplyr:::join_rows(...)
#>  5. │     └─dplyr:::dplyr_locate_matches(...)
#>  6. │       ├─base::withCallingHandlers(...)
#>  7. │       └─vctrs::vec_locate_matches(...)
#>  8. └─rlang:::stop_internal_c_lib(...)
#>  9.   └─rlang::abort(message, call = call, .internal = TRUE, .frame = frame)
```

**Comment by hadley** [comment] 2023-02-06 14:46
Somewhat more minimal reprex which suggests the problem isn't just a pure vctrs issue, as I had guessed:

``` r
library(data.table)
library(dplyr, warn.conflicts = FALSE)

x <- as.IDate("2017-06-05")
y <- as.IDate("2021-04-26")
typeof(x)
#> [1] "integer"
typeof(vctrs::vec_c(x, y))
#> [1] "integer"

dt1 <- data.table(week = x, y = 1)
dt2 <- data.table(week = y, z = 1)
dt12 <- left_join(dt1, dt2, by = join_by(week))
typeof(dt12$week)
#> [1] "double"
```

<sup>Created on 2023-02-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by DavisVaughan** [comment] 2023-02-06 15:19
It is vctrs. It is in the proxy/restore system, not the type system

``` r
library(vctrs)
library(data.table)

x <- as.IDate("2017-06-05")
class(x)
#> [1] "IDate" "Date"

typeof(x)
#> [1] "integer"

typeof(vec_slice(x, 1))
#> [1] "double"

# Because of
typeof(vec_proxy(x))
#> [1] "double"

# Proxy is inherited from Date, which normalizes to double
vctrs:::vec_proxy.Date
#> function (x, ...) 
#> {
#>     date_validate(x)
#> }
#> <bytecode: 0x7fedebbeb8f0>
#> <environment: namespace:vctrs>
```

I guess we could provide a `vec_proxy.IDate()` method from vctrs, and maybe a restore method too.

**Comment by DavisVaughan** [comment] 2023-02-06 15:22
This is mostly tough because `IDate` is meant to have `"integer"` storage but `Date` is (at this point) meant to have `"double"` storage, but the `IDate` class structure is `c("IDate", "Date")`, which conflict with one another

**Comment by DavisVaughan** [comment] 2023-02-06 15:23
Closing in favor of https://github.com/r-lib/vctrs/issues/1781

**Closed by DavisVaughan** 2023-02-06 15:23 UTC
