### ISSUE TITLE
`filter` option to keep `NA`s

### ISSUE THREAD

**Issue by spressi** [tidyverse/dplyr#6432] opened 2022-08-25 08:20 UTC
Hey there,
I'd like to propose to add a parameter to `dplyr::filter` to specify how `NA`s are treated in the logical vector.
From the documentation: "Note that when a condition evaluates to NA the row will be dropped, unlike base subsetting with [."
While this is a good default behavior, it would be nice to be able to add, e.g. `.treat.nas=T` to the function call to emulate base R subsetting in a convenient way.

Use case / reprex: Looking for inconsistencies in data, you sometimes want to show NAs:
```r
tibble(col1 = 1:3, col2 = c(1, 1, NA)) %>% filter(col1 != col2)
```
This call only outputs row 2 but it would be nice to be able to obtain row 3 as well if desired.

Thanks and kind regards,
Mario

**Comment by spressi** [comment] 2022-08-25 08:28
Of course, it is possible to call `replace_na` explicitly to produce the desired behavior:
```r
tibble(col1 = 1:3, col2 = c(1, 1, NA)) %>% filter({col1 != col2} %>% replace_na(T))
```
But I think it would be more convenient and more readable with a separate parameter.

**Comment by hadley** [comment] 2022-08-25 10:26
I think the problem is not that `filter()` is lacking but that we're missing some vectorised equality operator with the desired properties. You can get part way with `vctrs::vec_equal()`:

``` r
library(dplyr, warn.conflicts = FALSE)
tibble(col1 = 1:3, col2 = c(1, 1, NA)) %>% 
  filter(!vctrs::vec_equal(col1, col2, na_equal = TRUE))
#> # A tibble: 2 × 2
#>    col1  col2
#>   <int> <dbl>
#> 1     2     1
#> 2     3    NA
```

<sup>Created on 2022-08-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

But this function is unlikely to live in dplyr so I'm going to close this issue. There are some older thoughts in https://github.com/tidyverse/funs/issues/12.

**Closed by hadley** 2022-08-25 10:26 UTC

**Comment by spressi** [comment] 2022-08-25 14:36
I agree that the problem has to do with the definition of the equality operator in the provided example but I also think the question of how to treat NAs in `filter` is somewhat more general than that. I argue that there are use cases (e.g., during data inspection) in which you would want to show rows that are represented by NAs. But then again, there are workarounds, the issue is probably not super important, and the behavior of `filter` is well documented :)
