### ISSUE TITLE
filter() creates an actual error from a failed shiny::req()

### ISSUE THREAD

**Issue by halhen** [tidyverse/dplyr#5552] opened 2020-10-08 11:44 UTC
With dplyr 1.0, `filter()` no longer seems to propagate the shiny silent error from a failed `shiny::req()` but instead interjects and causes an actual error.

With reprex below:

Expected behaviour (in e.g. dplyr 0.7, or when uncommenting the `limit()` outside of `filter()`):
![image](https://user-images.githubusercontent.com/71583/95453956-0cc09e00-096c-11eb-8355-e37d0b5797d3.png)

Actual behaviour: 
![image](https://user-images.githubusercontent.com/71583/95453779-c23f2180-096b-11eb-8201-7a1c349204f2.png)

```r
library(shiny)
library(tidyverse)

ui <- fluidPage(
    textOutput("out")
)

server <- function(input, output) {
    limit <- reactive({
        req(NULL)
        3
    })
    
    output$out <- renderText({
        # uncomment this to see the expected behaviour
        # limit()
        tibble::tibble(a = 1:5) %>%
            filter(a > limit()) %>%
            with(paste0(a, collapse = ', '))
    })
}

shinyApp(ui = ui, server = server)
```

**Comment by antoine-sachet** [comment] 2020-10-12 11:48
I can confirm this also happens with `shiny::validate` - my shiny apps now throw errors left and right instead of the usual grey message.

To replicate, just replace `req(NULL)` with `validate(need(F, "some text")` in the code above.

**Comment by romainfrancois** [comment] 2020-10-15 08:52
One thing we can do is let the `shiny.silent.error` pass, e.g. have something like this in the `error = ` handler: 

```
error = function(e) {
      if (inherits(e, "shiny.silent.error")) stop(e)
      ...
```    

in all of our `withCallingHandlers()` calls. I believe it's better to handle reactivity upfront though by calling `limit()` before doing the `dplyr` thing, as this can be a problem of anything that catches an error and regrows it differently. cc @hadley

**Comment by halhen** [comment] 2020-10-15 10:18
Is the intended design that dplyr should catch exceptions and throw an error of a different type? This was the biggest surprise in behaviour to me, and one that perhaps should be communicated even more loudly since it changes a lot of expectations. (Maybe it is well documented and just passed me by; apologies in advance if so :smile: )

If the behaviour is intentional, I agree that it probably doesn't make sense to treat shiny differently.

**Comment by hadley** [comment] 2020-10-15 12:51
@halhen it is intentional because it allows us to tell you which group the error occurred in (which is often hard to get at otherwise). I'll need to think a little to see what (if anything) we should do about `shiny::req()`.

**Comment by antoine-sachet** [comment] 2020-11-09 12:12
Are you still considering leaving the shiny validation logic (`req`/`need`/`validate`) broken with dplyr 1.0+?

I'd rather not have my new shiny apps depend on dplyr 0.8.5 but until this is fixed I just have to downgrade :(

**Comment by antoine-sachet** [comment] 2020-11-09 14:17
To make the code more generic, `dplyr` could look up the error types to propagate in the options.

```r
options(dplyr.errors_to_propagate = c("shiny.silent.error", "my.custom.error"))
```

The error handlers would look like

```r
error = function(e) {
      if (inherits(e, getOption("dplyr.errors_to_propagate", default = character(0)))) stop(e)
      ...
```

This would allow shiny developers to propagate silent validation errors and provide a workaround for similar issues in the future.

**Comment by hadley** [comment] 2020-11-09 15:24
@antoine-sachet using options in this way is very ill-advised because now the behaviour of dplyr is affected by an option. This tends to make for irreproducible code.

**Comment by romainfrancois** [comment] 2020-11-20 09:18
We only have in some function, special treatment of various kinds of errors, e.g. in `mutate()`. https://github.com/tidyverse/dplyr/blob/master/R/mutate.R#L327

I don't think that it hurts to add some special handling of `shiny.silent.error`. I'll start a pr and move the discussion there.

**Comment by romainfrancois** [comment] 2021-10-04 11:22
If we now adopt chained errors, i.e. 

```r
withCallinngHandlers(<...>, error = function(e) abort(<...>, parent = e))
```

to enhance errors, perhaps there could be a helper to identify if an error was caused by a given kind of error, e.g.

```r
is_caused_by <- function(cond, class = "shiny.silent.error") {
  inherits(cond, class) || (!is.null(cond$parent) && is_caused_by(cond$parent, class))
}
```

so that for example in https://github.com/rstudio/shiny/blob/2360bde13efac1fe501efee447a8f3dde0136722/R/shiny.R#L1117 

shiny would use ` if (is_caused_by(cond, "shiny.silent.error")`

This way, dplyr could keep enhancing errors, but shiny still identify that an error is caused by reactivity ?

``` r
library(rlang)
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

f <- function() {
  abort("bla", class = "shiny.silent.error")
}

is_caused_by <- function(cond, class = "shiny.silent.error") {
  inherits(cond, class) || (!is.null(cond$parent) && is_caused_by(cond$parent, class))
}

with_reactive_error <- function() {
  withCallingHandlers({
    mutate(mtcars, a = cyl > f())
  }, error = function(e) {
    abort("ouch", parent = e)
  })
}

without_reactive_error <- function() {
  withCallingHandlers({
    mutate(mtcars, a = cyl > stop("boom"))
  }, error = function(e) {
    abort("ouch", parent = e)
  })
}


try_catch({
  with_reactive_error()
}, error = function(cond) {
  if (!is_caused_by(cond, "shiny.silent.error")) {
    stop(cond)
  }
})
#> NULL

try_catch({
  without_reactive_error()
}, error = function(cond) {
  if (!is_caused_by(cond, "shiny.silent.error")) {
    stop(cond)
  }
})
#> Error: ouch
```

<sup>Created on 2021-10-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1.9000)</sup>

cc @lionel- I'm not quite sure about my use of `try_catch()` here. Is this the way to catch an error based on a predicate (whether it is caused by an error of type `"shiny.silent.error"`) or let it go otherwise ?

**Comment by lionel-** [comment] 2021-10-04 11:58
@romainfrancois I like the `is_caused_by()` approach instead of special-casing conditions in our handling. Maybe that could be `cnd_inherits()`?

**Comment by lionel-** [comment] 2021-10-04 12:03
It's also possible Shiny should use `signalCondition()` with a class `c("shiny.silent.condition", "condition")` to communicate with their exiting handler. If the handler is not on the stack, `signalCondition()` would return normally and the next line could throw a normal error.

**Comment by romainfrancois** [comment] 2021-10-04 12:27
Closing this here, as a fix is more likely to involve work in `shiny`.

**Closed by romainfrancois** 2021-10-04 12:27 UTC

**Comment by lionel-** [comment] 2021-10-04 12:29
Should we transfer the issue to the Shiny repo @wch?

**Comment by romainfrancois** [comment] 2021-10-04 12:30
I believe this is this one: https://github.com/rstudio/shiny/issues/3250

**Comment by mlpost** [comment] 2022-01-06 14:07
Hello @lionel- @romainfrancois  - I'm a bit new to shiny development so apologies for this elementary question, but... in the current state, is there a workaround for this issue? When trying the reprex below, I see how it bypasses the error, but the actual output never appears in my window. I'm having a similar issue with dplyr::select throwing an error; I can bypass the error so it doesn't show, but my output never prints. Thank you!
> 
> ```r
> library(shiny)
> library(tidyverse)
> 
> ui <- fluidPage(
>     textOutput("out")
> )
> 
> server <- function(input, output) {
>     limit <- reactive({
>         req(NULL)
>         3
>     })
>     
>     output$out <- renderText({
>         # uncomment this to see the expected behaviour
>         # limit()
>         tibble::tibble(a = 1:5) %>%
>             filter(a > limit()) %>%
>             with(paste0(a, collapse = ', '))
>     })
> }
> 
> shinyApp(ui = ui, server = server)
> ```

**Comment by lionel-** [comment] 2022-01-06 14:35
Thanks for reminding us @mlpost. I'll look into posting an issue on the Shiny repo (the issue linked above seems to be about something else) and I'll get in touch with the Shiny team to see what would be their timeframe for a fix. If too long, we'll work around in dplyr.

**Comment by mlpost** [comment] 2022-01-06 15:30
Thanks @lionel- much appreciated!

**Comment by lionel-** [comment] 2022-01-07 13:30
Upstream report at https://github.com/rstudio/shiny/issues/3566
Fix PR at https://github.com/rstudio/shiny/pull/3567
