### ISSUE TITLE
Variable labels get dropped by mutate

### ISSUE THREAD

**Issue by torfason** [tidyverse/dplyr#5255] opened 2020-05-19 09:56 UTC
Mutate does not preserve variable labels specified using the labelled package, making it more cumbersome to work with variable labels in a dplyr workflow. Admittedly, this is an interaction between two packages, but they are both part of the tidyverse, so very often used together I would imagine.

This seems to apply to mutate functions in general, which is a bummer, given how convenient in-place processing using mutate_at or the new across() syntax.

Using base R notation instead of mutate confirms that the issue is not with the intermediate functions but with mutate. In other words, assignment to columns using base R preserves the variable labels as expected. Demonstration below:

```r
library(dplyr)
library(labelled)

# Mutate drops haven_labelled variable labels, but this seems wrong
f <- factor(c("yes", "yes", "no", "no", "don't know"))
value_labels <- c("yes" = 1, "no" = 2, "don't know" = 9)
dat <- tibble(responses = to_labelled(f,value_labels)) %>% 
  set_variable_labels(responses="Variable labels get dropped by mutate")
dat <- dat %>%
  mutate(responses_mut = to_factor(responses))

# Assignement using base R notation does not drop labels
dat$responses_base <- to_factor(dat$responses)
sapply(dat,var_label)
#> $responses
#> [1] "Variable labels get dropped by mutate"
#> 
#> $responses_mut
#> NULL
#> 
#> $responses_base
#> [1] "Variable labels get dropped by mutate"

# This seems to apply to mutate_* functions in general
# (note that the variable label now dropped from responses_base)
dat %>% 
  mutate_if(is.factor,to_labelled) %>%
  sapply(var_label)
#> $responses
#> [1] "Variable labels get dropped by mutate"
#> 
#> $responses_mut
#> NULL
#> 
#> $responses_base
#> NULL

# It also applies to the new across() notation
# (note that the variable label now dropped from responses_base)
dat %>% 
  mutate(across(is.factor,to_labelled)) %>%
  sapply(var_label)
#> $responses
#> [1] "Variable labels get dropped by mutate"
#> 
#> $responses_mut
#> NULL
#> 
#> $responses_base
#> NULL
```

**Comment by hadley** [comment] 2020-05-19 12:01
labelled isn't part of the tidyverse, but this will by and large be fixed in dplyr 1.0.0.

**Closed by hadley** 2020-05-19 12:01 UTC

**Comment by QQuantmod** [comment] 2025-05-14 06:19
> labelled isn't part of the tidyverse, but this will by and large be fixed in dplyr 1.0.0.

Mister hadley, now dplyr 1.1.3 will still drop variable's label using mutate. And I didn't see related description in mutate's _Arguments_.

**Comment by torfason** [comment] 2025-05-14 21:58
Dear @QQuantmod, 

As the original submitter, I can verify that this has indeed been fixed. The original reprex now looks as follows, confirming that all relevant `dplyr` functions preserve variable labels:

```r
library(conflicted)
library(dplyr)
library(labelled)

packageVersion("dplyr")
#> [1] '1.1.4'

# Mutate no longer drops haven_labelled variable labels
f <- factor(c("yes", "yes", "no", "no", "don't know"))
value_labels <- c("yes" = 1, "no" = 2, "don't know" = 9)
dat <- tibble(responses = to_labelled(f,value_labels)) %>% 
  set_variable_labels(responses="Variable labels no longer dropped by mutate")
dat <- dat %>%
  mutate(responses_mut = to_factor(responses))

# Assignement using base R notation does not drop labels
dat$responses_base <- to_factor(dat$responses)
sapply(dat,var_label)
#>                                     responses 
#> "Variable labels no longer dropped by mutate" 
#>                                 responses_mut 
#> "Variable labels no longer dropped by mutate" 
#>                                responses_base 
#> "Variable labels no longer dropped by mutate"

# mutate_* functions now also preserve labels
dat %>% 
  mutate_if(is.factor,to_labelled) %>%
  sapply(var_label)
#>                                     responses 
#> "Variable labels no longer dropped by mutate" 
#>                                 responses_mut 
#> "Variable labels no longer dropped by mutate" 
#>                                responses_base 
#> "Variable labels no longer dropped by mutate"

# As does the (no longer so new) across() notation
dat %>% 
  mutate(across(is.factor,to_labelled)) %>%
  sapply(var_label)
#> Warning: There was 1 warning in `mutate()`.
#> ℹ In argument: `across(is.factor, to_labelled)`.
#> Caused by warning:
#> ! Use of bare predicate functions was deprecated in tidyselect 1.1.0.
#> ℹ Please use wrap predicates in `where()` instead.
#>   # Was:
#>   data %>% select(is.factor)
#> 
#>   # Now:
#>   data %>% select(where(is.factor))
#>                                     responses 
#> "Variable labels no longer dropped by mutate" 
#>                                 responses_mut 
#> "Variable labels no longer dropped by mutate" 
#>                                responses_base 
#> "Variable labels no longer dropped by mutate"
```

**Comment by QQuantmod** [comment] 2025-06-13 14:57
@torfason 

Thanks for your reply!!!

Yes indeed, your code prove that the question has been fixed, but not completely.

But It's my bad. I did't clarify my question clearly. My code is as follows:

```
library(haven)
library(tidyverse)
library(Hmisc)

CHECK1 <- head(read_sas(data_file = r"(C:\Users\16278\Desktop\test.sas7bdat)")) %>% 
  select(SUBJID)
label(CHECK1)
#> SUBJID 
#> "受试者标识符" 

CHECK2 <- CHECK1 %>% 
  mutate(SUBJID = str_sub(SUBJID,end = 3))
label(CHECK2)
#> SUBJID 
#>     ""
```

The dataset(dataframe) is in SAS format originally, imported by function _read_sas()_ in package _haven_. I think maybe it's not _mutate_'s fault?

**Comment by QQuantmod** [comment] 2025-06-13 15:25
@torfason 

Thanks for your reply!!!

Yes indeed, your code prove that the question has been fixed, but not completely.

But It's my bad. I did't clarify my question clearly. My code is as follows:

```
library(haven)
library(tidyverse)
library(Hmisc)

CHECK1 <- head(read_sas(data_file = r"(C:\Users\16278\Desktop\test.sas7bdat)")) %>% 
  select(SUBJID)
label(CHECK1)
#> SUBJID 
#> "label will be dropped" 

CHECK2 <- CHECK1 %>% 
  mutate(SUBJID = str_sub(SUBJID,end = 3))
label(CHECK2)
#> SUBJID 
#>     ""

```

[test.zip](https://github.com/user-attachments/files/20729040/test.zip)

The dataset(dataframe) is in SAS format originally, imported by function _read_sas()_ in package _haven_. I think maybe it's not _mutate_'s fault?

**Comment by torfason** [comment] 2025-06-14 19:13
You are right, it is not `mutate()` that is stripping the label. It is `str_sub()`. Note that the label is in reality an attribute on the `SUBJID` variable in the data frame, but `str_sub()` does not preserve it. You can see the label disappearing even without `mutate()` or even without a data frame at all. See a reprex below, with a function you could use to preserve the labels through these operations if you want to.

``` r
library(stringr)
library(labelled)

# Assign a label to s
s <- "My string"
var_label(s) <- "A label"
var_label(s)
#> [1] "A label"

# Note that the variable label is in reality an attribute on s
attributes(s)
#> $label
#> [1] "A label"

# str_sub strips attributes (or, more accurately, does not copy it to the new variable)
s <- str_sub(s, end = 3)
var_label(s)
#> NULL

# We could define a str_sub2 function that does not drop the labels
str_sub2 <- function(string, start = 1L, end = -1L) {
  result <- stringr::str_sub(string, start, end)
  var_label(result) <- var_label(string)
  result
} 

# Assign label again
var_label(s) <- "A label"
var_label(s)
#> [1] "A label"

# str_sub2 keeps the label (copies it to the new variable)
s <- str_sub2(s, end = 3)
var_label(s)
#> [1] "A label"
```

- Note that you would of course have to define a wrapper function similar to `str_sub2()` for each function that you are using to manipulate the variables.

**Comment by AstroRobin** [comment] 2026-05-13 02:18
Acknowledging that this issue was closed some time ago, however, there are still various issues that pertain to labels in mutate. For example, I also note the following unexpected behavior whereby labels are carried across in cases where they probably shouldn't:

```
dat <- tibble(
  weight = c(50, 60, 55, 70),
  height = c(170, 190, 160, 170)
) %>% 
  set_variable_labels(
    weight="Weight (kg)",
    height="Height (cm)"
  )

var_label(dat)
#> $weight
#> [1] "Weight (kg)"

#> $height
#> [1] "Height (cm)"
```

Now, if we mutate some additional columns, the label of the first column in any _formula_ seems to be applied to the nature of new column.

```
dat_new <- dat %>%
  mutate(height_m = height / 100) %>%
  mutate(bmi = weight / height_m ^ 2)

var_label(dat_new)
#> $weight
[1] "Weight (kg)"

#> $height
[1] "Height (cm)"

#> $height_m   # height_m column gets the original height label
[1] "Height (cm)"

#> $bmi   # BMI column gets the weight label 
[1] "Weight (kg)" 
```

In the above situations, it's more reasonable to drop the label altogether because the operations performed have inherently changed the new columns.

It's a slightly different situation for _non-altering operations_ like `str_sub()` or `factor()`. You noted that as in the case of `str_sub()`, a wrapper function might be needed to retain the label, as would be the case for all functions that drop labels. However, would it not be more appropriate to extract the labels of the `used` columns at the start of the `mutate()` function before executing any (potentially) label-dropping operations. This extracted label could then be returned onto the new column after the function has been performed. 

This warrants adding a `.label` argument in `mutate()`, which could either be a:

- **string**: to add labels inline to newly creating columns (e.g. `mutate(bmi = weight / height_m ^ 2, .label = "BMI")`),
- `TRUE`: to reapply any original labels (if appropriate as in `factor` or `str_sub`), or
- `FALSE`: to drop any new labels (the default?)

Giving the use control over label behaviours in mutate is probably the best way to account for all the different situations.
