### ISSUE TITLE
 '.Random.seed' is not an integer vector but of type 'NULL', so ignored

### ISSUE THREAD

**Issue by komalsrathi** [tidyverse/dplyr#2124] opened 2016-09-14 19:08 UTC
Hi,

I am getting this warning while using dplyr::filter. This happens the first time I run it but warning goes away the next time - not sure what is happening.

```
library(dplyr)
library(DT)

denovo <- read.delim('NLES10_733459.trio.phased.com.filtered.ad.de.nm.snpeff.anno.denovo.txt')

if(nrow(denovo) == 0)
{
  print("0 de novo variants found<br/>")
} else {
  dt <- plyr::count(denovo , 'impact_so')
  datatable(dat = data.frame(Description = dt$impact_so, 
                                 Variants = dt$freq, 
                                 Perc = prop.table(dt$freq)*100))
}

denovo %>% filter(recurrent_genes != "None") -> in_recurrent

Warning message:
In filter_impl(.data, dots) :
  '.Random.seed' is not an integer vector but of type 'NULL', so ignored
```

sessionInfo:

```
R version 3.3.0 (2016-05-03)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.6 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] DT_0.2               dplyr_0.5.0          BiocInstaller_1.23.9

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.7     digest_0.6.10   assertthat_0.1  R6_2.1.3        plyr_1.8.4     
 [6] jsonlite_1.0    DBI_0.5         magrittr_1.5    lazyeval_0.2.0  tools_3.3.0    
[11] htmlwidgets_0.7 yaml_2.1.13     rsconnect_0.4.3 htmltools_0.3.5 tibble_1.2   
```

The denovo data is here:
https://drive.google.com/open?id=0B-8gQV1WZcYdYm1BWmNZU1JzQ2s

**Comment by romainfrancois** [comment] 2016-09-14 19:55
Can you reprexify this please, we don't have `denovo `

**Comment by komalsrathi** [comment] 2016-09-14 23:44
Sorry about that. I have provided the exact code I am using and the google drive link for the data is at the end of the original post.

**Comment by romainfrancois** [comment] 2016-09-15 09:15
Thanks. I can't reproduce the problem

```
in_recurrent <- denovo %>% filter(recurrent_genes != "None")
```

and `filter` does not use anything that needs `.Randon.seed` so this is likely not a `dplyr` issue.

**Comment by komalsrathi** [comment] 2016-09-15 15:20
Alright I will close this then.

**Comment by jennybc** [comment] 2016-10-24 08:15
I'm getting this warning from a call `purrr::map_df()`. In an Rmd document and only when I render it, not when I run the code interactively. And only when I render that specific Rmd, not when I build the entire website it is part of. The whole project is available on GitHub but maybe it's better to see if a smaller reprex presents itself.

**Comment by stevekm** [comment] 2017-06-15 16:00
Same as @jennybc , I am getting this error message when compiling an Rmd document to HTML and trying to use `DT` to print a `datatable` in the document. Is there a way to suppress this message? It does not seem to be affecting anything but I can't stop it from appearing in the document.

**Comment by jbintz** [comment] 2017-08-05 15:17
Same as @jennybc but from call to `readr::read_rds()`, in Rmd document and only when I render it.

**Comment by jto888** [comment] 2017-08-24 01:18
I understand this is closed, but I have been getting these mysterious warnings. Yes, I had imported plyr, and when I changed to a depend some warnings went away.

**Comment by pmcharrison** [comment] 2017-08-29 16:11
I had this problem when running DT::datatable(...) and later plotly::plot_ly(...) in an Rmd document. A quick fix was to insert the following after DT::datatable(...):

```
rm(.Random.seed)
set.seed(1)
```

**Comment by krlmlr** [comment] 2018-02-05 23:39
Can we close this?

**Closed** 2018-03-16 14:00 UTC
