### ISSUE TITLE
Mutate_ and case_when unable to find column variables

### ISSUE THREAD

**Issue by cfhammill** [tidyverse/dplyr#2757] opened 2017-05-08 15:33 UTC
Using `case_when` inside a `mutate_` with tilde quotation produced some unexpected results:

```
data_frame(a = 1:5, b = 6:10) %>% 
  mutate_(c = ~case_when(a < 5 ~ "b", TRUE ~ "c"))
```

This can be fixed by wrapping the `case_when` in a `with`

```
data_frame(a = 1:5, b = 6:10) %>% 
  mutate_(c = ~ with(., case_when(a < 5 ~ "b", TRUE ~ "c")))
``` 
But it seems as though with should pick up the column variables like other expressions supplied to `mutate_`

**Comment by lionel-** [comment] 2017-05-08 15:39
duplicate of https://github.com/tidyverse/dplyr/issues/2745

**Closed by lionel-** 2017-05-08 15:39 UTC

**Comment by cfhammill** [comment] 2017-05-08 16:03
Thanks Lionel!
