### ISSUE TITLE
Filter with across does not work as expected?

### ISSUE THREAD

**Issue by RealCoChenchao** [tidyverse/dplyr#5519] opened 2020-09-03 21:44 UTC
Please briefly describe your problem and what output you expect. If you have a question, please don't use this form. Instead, ask on <https://stackoverflow.com/> or <https://community.rstudio.com/>.

Please include a minimal reproducible example (AKA a reprex). If you've never heard of a [reprex](http://reprex.tidyverse.org/) before, start by reading <https://www.tidyverse.org/help/#reprex>.

---

Brief description of the problem
Basically, I'd like to filter rows with missing value in any of the numeric variables. Using original `filter_if` works fine, but change to `across` with `where(is.numeric())` does not as I expected. Below is a minimal reprex example using `mtcars`.

```r
library(tidyverse)
library(reprex)
glimpse(mtcars)
#> Rows: 32
#> Columns: 11
#> $ mpg  <dbl> 21.0, 21.0, 22.8, 21.4, 18.7, 18.1, 14.3, 24.4, 22.8, 19.2, 17.8…
#> $ cyl  <dbl> 6, 6, 4, 6, 8, 6, 8, 4, 4, 6, 6, 8, 8, 8, 8, 8, 8, 4, 4, 4, 4, 8…
#> $ disp <dbl> 160.0, 160.0, 108.0, 258.0, 360.0, 225.0, 360.0, 146.7, 140.8, 1…
#> $ hp   <dbl> 110, 110, 93, 110, 175, 105, 245, 62, 95, 123, 123, 180, 180, 18…
#> $ drat <dbl> 3.90, 3.90, 3.85, 3.08, 3.15, 2.76, 3.21, 3.69, 3.92, 3.92, 3.92…
#> $ wt   <dbl> 2.620, 2.875, 2.320, 3.215, 3.440, 3.460, 3.570, 3.190, 3.150, 3…
#> $ qsec <dbl> 16.46, 17.02, 18.61, 19.44, 17.02, 20.22, 15.84, 20.00, 22.90, 1…
#> $ vs   <dbl> 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0…
#> $ am   <dbl> 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0…
#> $ gear <dbl> 4, 4, 4, 3, 3, 3, 3, 4, 4, 4, 4, 3, 3, 3, 3, 3, 3, 4, 4, 4, 3, 3…
#> $ carb <dbl> 4, 4, 1, 1, 2, 1, 4, 2, 2, 4, 4, 3, 3, 3, 4, 4, 4, 1, 2, 1, 1, 2…
mutated_mtcars <- mtcars %>%
  dplyr::mutate(hp = ifelse(mpg <= 12,
                            NA,
                            hp))
mutated_mtcars %>%
  dplyr::filter_if(is.numeric,
                   dplyr::any_vars(is.na(.))) 
#>    mpg cyl disp hp drat    wt  qsec vs am gear carb
#> 1 10.4   8  472 NA 2.93 5.250 17.98  0  0    3    4
#> 2 10.4   8  460 NA 3.00 5.424 17.82  0  0    3    4

mutated_mtcars %>%
  dplyr::filter(across(where(is.numeric),
                       dplyr::any_vars(is.na(.))))
#>  [1] mpg  cyl  disp hp   drat wt   qsec vs   am   gear carb
#> <0 rows> (or 0-length row.names)
```

**Comment by Zhuxitong** [comment] 2020-09-08 13:38
Same issue, very wired!

```
> bind_cols(ribo_tpm_matrix[i], rna_tpm_matrix[i]) %>% rownames_to_column() %>% head()
          rowname Omh63_leaf_Ribo Omh63_leaf_RNA
1 OsMH_01G0000100          13.415          9.100
2 OsMH_01G0000200          21.865         28.590
```

when applied filter with across

```
> bind_cols(ribo_tpm_matrix[i], rna_tpm_matrix[i]) %>% rownames_to_column() %>% filter(across(where(is.numeric), all_vars(. >= 0.1))) %>% count()
      n
1 39406
> bind_cols(ribo_tpm_matrix[i], rna_tpm_matrix[i]) %>% rownames_to_column() %>% filter_if(is.numeric, all_vars(. >= 0.1)) %>% count()
      n
1 19357
```

**Comment by moodymudskipper** [comment] 2020-09-14 13:50
As far as I can see, the doc doesn't stipulate that `accross()` should support `any_vars()` nor `all_vars()`.

I read in `vignette("colwise")` : 

> Previously, filter() was paired with the all_vars() and any_vars() helpers. Now, across() is equivalent to all_vars(), and there’s no direct replacement for any_vars(). However you can make a simple helper yourself

if I apply the suggested fix to your case : 

```
library(dplyr, warn.conflicts = FALSE)

mutated_mtcars <- mtcars %>%
  dplyr::mutate(hp = ifelse(mpg <= 12, NA, hp))

mutated_mtcars %>%
  dplyr::filter(rowSums(across(where(is.numeric), ~is.na(.))) > 0)
#>    mpg cyl disp hp drat    wt  qsec vs am gear carb
#> 1 10.4   8  472 NA 2.93 5.250 17.98  0  0    3    4
#> 2 10.4   8  460 NA 3.00 5.424 17.82  0  0    3    4
```

**Comment by hadley** [comment] 2020-11-16 20:30
Duplicate of #4770

**Closed by hadley** 2020-11-16 20:30 UTC
