### ISSUE TITLE
 Could not find function "lead" with latest version of dplyr

### ISSUE THREAD

**Issue by md0u80c9** [tidyverse/dplyr#3456] opened 2018-03-23 22:30 UTC
Hi all,

The following line of code works perfectly in the stable version of dplyr. In the development version however (with the newer version of bindrcpp) this generates an error:

Error in mutate_impl(.data, dots) : could not find function "lead"

I'm not aware of lead being affected by the tidy select changes so is the function being parsed differently in some way?

```r
  importedData <- dplyr::mutate(importedData,
    InpatientReadmission = cumsum(
      (dplyr::lead(.data$TeamCode,
                  n = 1,
                  default = -1) > 0) & (.data$TeamCode < 0) * 1))
```

**Comment by krlmlr** [comment] 2018-03-23 22:39
Thanks for the report, this is really important to fix before release. Could you please create a [reproducible example](http://reprex.tidyverse.org/) that uses a small toy dataset or a commonly available one?

**Comment by md0u80c9** [comment] 2018-03-24 03:35
Hi,

It looks as though this is as simple as:

```
test <- tibble::tibble(foo = c(1,2,3))
test <- dplyr::mutate(test, Bar = dplyr::lead(.data$test, n = 1, default = -1))
```

Fails.

```
test <- tibble::tibble(foo = c(1,2,3))
dplyr::lead(test, n = 1, default = -1)
```

Works.

**Comment by krlmlr** [comment] 2018-03-24 07:43
Thanks. I can't run your first example, I'm seeing:

``` r
test <- tibble::tibble(foo = c(1,2,3))
test <- dplyr::mutate(test, bar = dplyr::lead(.data$test, n = 1, default = -1))
#> Error in mutate_impl(.data, dots): Evaluation error: Column `test` not found in `.data`.
```

> Created on 2018-03-24 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

Also, for the second example I'm seeing:

``` r
test <- tibble::tibble(foo = c(1,2,3))
dplyr::lead(test, n = 1, default = -1)
#> # A tibble: 3 x 1
#>     foo
#> * <dbl>
#> 1   -1.
#> 2   NA 
#> 3   NA
```

> Created on 2018-03-24 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

What do you expect `lead()` on a data frame to return?

**Comment by md0u80c9** [comment] 2018-03-24 08:30
That is the point. The first example doesn’t work.

But if you run that on the stable version of dplyr from CRAN, it will work and it will put the results seen in the second example into the tibble as a new column.

**Comment by md0u80c9** [comment] 2018-03-24 08:42
Apologies - that first example should be:

```
test <- tibble::tibble(foo = c(1,2,3))
test <- dplyr::mutate(test, bar = dplyr::lead(.data$foo, n = 1, default = -1))
```

On dplyr 0.7.4 you get:

```
> test
# A tibble: 3 x 2
    foo   bar
  <dbl> <dbl>
1    1.    2.
2    2.    3.
3    3.   -1.
```

Output from dplyr 0.7.4.9002:
```
> test <- tibble::tibble(foo = c(1,2,3))
> test <- dplyr::mutate(test, bar = dplyr::lead(.data$foo, n = 1, default = -1))
Error in mutate_impl(.data, dots) : could not find function "lead"
```

**Comment by krlmlr** [comment] 2018-03-24 09:07
Thanks, confirmed:

@romainfrancois: Could you please take a look?

**Comment by md0u80c9** [comment] 2018-03-27 12:04
Hi,

Just followed the thread. Don't think the current fixes address the above?

**Comment by romainfrancois** [comment] 2018-03-27 12:56
@md0u80c9  did you try with the `fix-issue-3456` branch?

```
install_github( "tidyverse/dplyr", ref = "fix-issue-3456" )
```

**Comment by md0u80c9** [comment] 2018-03-27 18:58
Tested with that branch now - and that seems to work both on the reprex and on my original code. Great stuff :-).

**Comment by romainfrancois** [comment] 2018-03-27 19:04
Thanks for taking the time to try it. 

Just for the record, a commit message in the branch would have closed the issue automatically on merge. 

Not a big deal because we usually merge fast, but potentially a problem on others repos. 

Thanks again for reporting the problem in the first place.

**Comment by krlmlr** [comment] 2018-03-29 22:24
Reopening, will close when PR is merged.

**Closed** 2018-04-10 01:14 UTC
Labels: bug, data frame
