### ISSUE TITLE
More precise error messages for mutate() et al.

### ISSUE THREAD

**Issue by krlmlr** [tidyverse/dplyr#3128] opened 2017-09-27 15:21 UTC
When propagating an error from the R interpreter, we should mention specifically what caused the error, because the messages may not be very helpful, as in [this SO example](https://stackoverflow.com/q/46450353/946850) where the cause is a mistyped column name but error is simply:

```
Error in mutate_impl(.data, dots): cannot coerce type 'closure' to vector of type 'double'
```

Instead, the error message should be more like:

```
Error: mutate(..., id = as.numeric(id)) cannot be evaluated, cannot coerce type 'closure' to vector of type 'double'
```

**Comment by romainfrancois** [comment] 2018-05-29 09:59
duplicate of #3510

**Closed by romainfrancois** 2018-05-29 09:59 UTC
Labels: data frame, feature
