### ISSUE TITLE
[Bug] dplyr 0.7.1 does not work with data.table objects

### ISSUE THREAD

**Issue by MarkusBonsch** [tidyverse/dplyr#2937] opened 2017-07-03 12:16 UTC
It seems that the new dplyr version fails to work properly with data.table objects.
See also this dtplyr issue: https://github.com/hadley/dtplyr/issues/51

```
library(data.table)
library(dtplyr)
library(dplyr)
dt <- data.table(a=1:10, b=1:10, c=1:10)
dt %>%  mutate_all(as.integer)
# Error in .subset(x, j) : invalid subscript type 'language'
```

```
R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
 [1] dtplyr_0.0.2         dplyr_0.7.1          data.table_1.10.4    RevoUtilsMath_10.0.0 RevoUtils_10.0.3    
 [6] RevoMods_11.0.0      MicrosoftML_1.3.0    mrsdeploy_1.1.0      RevoScaleR_9.1.0     lattice_0.20-34     
[11] rpart_4.1-10        

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.11           codetools_0.2-15       CompatibilityAPI_1.1.0 assertthat_0.1         foreach_1.4.3         
 [6] grid_3.3.3             R6_2.2.0               jsonlite_1.3           magrittr_1.5           rlang_0.1.1           
[11] lazyeval_0.2.0         curl_2.3               bindrcpp_0.2           iterators_1.0.8        tools_3.3.3           
[16] glue_1.1.1             pkgconfig_2.0.1        bindr_0.1              tibble_1.3.3           mrupdate_1.0.1 
```

**Comment by BabaYara** [comment] 2017-07-07 19:30
One work around is to wrap your object in "as_data_frame" to drop the data.table class attributes from the object.

**Comment by hadley** [comment] 2017-08-23 13:40
Duplicate of hadley/dtplyr#51

**Closed by hadley** 2017-08-23 13:40 UTC
