### ISSUE TITLE
Consider providing bind_rows and bind_cols as S3 methods

### ISSUE THREAD

**Issue by javierluraschi** [tidyverse/dplyr#2759] opened 2017-05-08 18:48 UTC
In `sparklyr`, we would like to be able to support specific implementations for `bind_rows` and `bind_cols`:

```r
bind_rows.tbl_spark <- function(...) # custom implementation
bind_cols.tbl_spark <- function(...) # custom implementation
```

Related to: https://github.com/rstudio/sparklyr/pull/662

**Comment by hadley** [comment] 2017-05-08 19:05
Duplicate of #2457

**Closed by hadley** 2017-05-08 19:05 UTC

**Comment by Hong-Revo** [comment] 2017-06-09 09:00
This would be very useful in dplyrXdf as well.
