### ISSUE TITLE
Using R Shiny inputs for filtering or selecting in dplyr

### ISSUE THREAD

**Issue by MarkusBerroth** [tidyverse/dplyr#4385] opened 2019-05-27 09:57 UTC
Hello,

I want to use R Shiny-Inputs for Filtering or Selecing within dplyr. More exactly in order to use it for a Spark or Postgre query. 
With a one month older Shiny & dplyr Version it worked like I would expect with the Shiny input as a direct input for dplyr. (Shiny Version: 1.2.,  dplyr: 0.8.0.1, sparklyr: 1.0.0) 
However, with the newest Versions I get `Warning: Error in UseMethod: no applicable method for 'escape' applied to an object of class "reactivevalues" `

With some research it seems like the Issue #318 , which was resolved in the following commit (https://github.com/tidyverse/dplyr/commit/57741a8072e0b77e6399400ba064668cd638c4d8) exists again.  
Thus, in order to have the Shiny App working again, the use of `local()` or an Interimsvariable is needed. 

Following example is not working anymore 

**server.R**
```r
library(shiny)
library(dplyr)
library(sparklyr)

# Define server logic required to filter numbers
shinyServer(function(input, output) {
    tbl_1 <- tibble(a = 1:5, b = 6:10)
    sc <- spark_connect(master = "local")
    
    tbl_1_sp <-
        sparklyr::copy_to(
            dest = sc,
            df = tbl_1,
            name = "tbl_1_sp",
            overwrite = TRUE
        )
    
    observeEvent(input$select_a, {        
        number_b <- tbl_1_sp %>%
            filter(a == input$select_a) %>%
            collect() %>%
            pull()
        
        output$text_b <- renderText({
            paste0("Selected number : ", number_b)           
        })
    })  
})
```
**ui.R**
```r
library(shiny)
library(dplyr)
library(sparklyr)


# Define UI for application t
shinyUI(fluidPage(
    # Application title
    titlePanel("Select Number Example"),
    
    # Sidebar with a slider input for number
    sidebarLayout(sidebarPanel(
        sliderInput(
            "select_a",
            "Number for 1:",
            min = 1,
            max = 5,
            value = 1
        )
    ),
    
    # Show a text as output
    mainPanel(textOutput("text_b")))
))
```

Whereas, with the use of `local()` the App is working again: 

**server.R**
```r
library(shiny)
library(dplyr)
library(sparklyr)

# Define server logic required to filter numbers
shinyServer(function(input, output) {
    tbl_1 <- tibble(a = 1:5, b = 6:10)
    sc <- spark_connect(master = "local")
    
    tbl_1_sp <-
        sparklyr::copy_to(
            dest = sc,
            df = tbl_1,
            name = "tbl_1_sp",
            overwrite = TRUE
        )
    
    observeEvent(input$select_a, {
        intermediatselect_a <- input$select_a
        
        number_b <- tbl_1_sp %>%
            filter(a == local(input$select_a)) %>%
            collect() %>%
            pull()
        
        output$text_b <- renderText({
            paste0("Selected number : ", number_b)           
        })
    })  
})
```
**ui.R**
```r
library(shiny)
library(dplyr)
library(sparklyr)


# Define UI for application t
shinyUI(fluidPage(
    # Application title
    titlePanel("Select Number Example"),
    
    # Sidebar with a slider input for number
    sidebarLayout(sidebarPanel(
        sliderInput(
            "select_a",
            "Number for 1:",
            min = 1,
            max = 5,
            value = 1
        )
    ),
    
    # Show a text as output
    mainPanel(textOutput("text_b")))
))
```

Or alternatively using intermediatselect_a as input.

Is this the desired new behavior of the NSE for dplyr with shiny and the user should consider when a variable have to be evaluated locally? Or is this a a new issue/bug?

Thank you in Advance!

**Comment by romatik** [comment] 2019-05-27 10:22
The problem is that `$` is no longer executed locally since modern DB tend to provide an option to go into lists. For that reason `$` is passed onto a DB directly. 

What happens if you change this line: 
```
            filter(a == input$select_a) %>%
```
to 
```
            filter(a == !!input$select_a) %>%
```
?

**Comment by romainfrancois** [comment] 2019-05-27 14:23
I second @romatik and unquoting (with !!) should fix it.

@MarkusBerroth I'll close this here, but feel free to reopen in e.g. `dbplyr` or `sparklyr`.

**Closed by romainfrancois** 2019-05-27 14:23 UTC
