### ISSUE TITLE
Add a merge indicator column to full_join

### ISSUE THREAD

**Issue by hassanjfry** [tidyverse/dplyr#6481] opened 2022-09-26 16:11 UTC
Add a new column (indicator of merge) to the full_join output indicating (left_only, both, right_only) .

Please see the link below for more information:
https://stackoverflow.com/questions/40110644/is-there-a-merge-indicator-available-after-a-merge

**Comment by hadley** [comment] 2022-09-26 17:00
Duplicate of #6435

**Closed by hadley** 2022-09-26 17:00 UTC
