### ISSUE TITLE
group_by_at() doesn't handle existig grouping correctly

### ISSUE THREAD

**Issue by tzoltak** [tidyverse/dplyr#3351] opened 2018-02-09 20:54 UTC
`group_by_at(tbl)` is confused if `tbl` is already a grouped tibble and new grouping uses some of variables that were used in this previously existing grouping. Instead of overwriting this existing grouping (as `group_by()` does by default) it returns tibble grouped only by variables that wern't used in previosuly defined grouping (and throws a warning about nonexistence of variables common for existing and newly defined grouping).

```r
library(dplyr)
#> 
#> Dołączanie pakietu: 'dplyr'
#> Następujące obiekty zostały zakryte z 'package:stats':
#> 
#>     filter, lag
#> Następujące obiekty zostały zakryte z 'package:base':
#> 
#>     intersect, setdiff, setequal, union

# some grouped tibble
tbl = tibble(gr1 = rep(1:2, 4), gr2 = rep(1:2, each = 4), x = 1:8) %>%
  group_by(gr1)

# doesn't work
tbl %>%
  group_by_at(vars(one_of("gr1", "gr2"))) %>%
  summarise(xSum = sum(x))
#> Warning: Unknown variables: `gr1`

#> Warning: Unknown variables: `gr1`
#> # A tibble: 2 x 2
#>     gr2  xSum
#>   <int> <int>
#> 1     1    10
#> 2     2    26

# adding ungroup() before group_by_at() helps
tbl %>%
  ungroup() %>%
  group_by_at(vars(one_of("gr1", "gr2"))) %>%
  summarise(xSum = sum(x))
#> # A tibble: 4 x 3
#> # Groups:   gr1 [?]
#>     gr1   gr2  xSum
#>   <int> <int> <int>
#> 1     1     1     4
#> 2     1     2    12
#> 3     2     1     6
#> 4     2     2    14

# however group_by() works without such workaround
tbl %>%
  group_by(gr1, gr2) %>%
  summarise(xSum = sum(x))
#> # A tibble: 4 x 3
#> # Groups:   gr1 [?]
#>     gr1   gr2  xSum
#>   <int> <int> <int>
#> 1     1     1     4
#> 2     1     2    12
#> 3     2     1     6
#> 4     2     2    14
```

**Comment by krlmlr** [comment] 2018-02-10 22:13
Thanks, confirmed!

**Comment by romainfrancois** [comment] 2018-03-12 09:49
Same problem as this : 

```
> select_at( tbl, vars(one_of(c("gr1", "gr2"))) )
# A tibble: 8 x 2
# Groups:   gr1 [2]
    gr1   gr2
  <int> <int>
1     1     1
2     2     1
3     1     1
4     2     1
5     1     2
6     2     2
7     1     2
8     2     2
Warning message:
Unknown columns: `gr1` 
```

**Comment by krlmlr** [comment] 2018-03-12 10:03
I just merged a PR from @lionel- that addresses this for `select()` and `rename()`, and also updated documentation. Maybe follow the ideas there and extract common logic to functions?

**Comment by romainfrancois** [comment] 2018-03-12 10:04
Looks like it happens here: https://github.com/tidyverse/dplyr/blob/master/R/colwise.R#L123

where it specifically removes grouping columns.

**Closed** 2018-04-06 08:56 UTC
Labels: bug, data frame
