### ISSUE TITLE
Permit identification of primary and foreign keys when creating a new SQLite table 

### ISSUE THREAD

**Issue by lhunsicker** [tidyverse/dplyr#2936] opened 2017-07-03 01:31 UTC
RSQLite has a wonderful feature that permits one to enter data from a flat file (e.g., a csv file) directly into an SQLite table.  dbWriteTable does an excellent job of "guessing" field types and creates the tables with appropriate affinities.  However when SQLite tables are created in this way, it is impossible later on to identify primary or foreign fields.  (Unlike other indices, the primary and foreign key fields have to be identified at the time of file definition.)  It would be a neat addition to the dbWriteTable program if there were an option to define the above key fields within the call to dbWriteTable.  Perhaps these definitions could be added by dbWriteTable to the table definitions at the step in the program that it detects the column types and defines the column affinities.  
This would make unnecessary the typical sequence of entering data, reading out the table definition and adding the key constraints, creating a new table, and copying the initial table to the new table.
Thanks for considering the above.
Larry Hunsicker

---

Brief description of the problem

```r
# insert reprex here
```

**Comment by krlmlr** [comment] 2017-07-12 19:58
Thanks. Some methods do have a `unique_indexes` argument, but could you please provide a reproducible example?

**Comment by hadley** [comment] 2017-10-23 16:49
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2017-10-23 16:49 UTC
Labels: database, reprex
