### ISSUE TITLE
dbplyr generates unnecessary subqueries

### ISSUE THREAD

**Issue by ilyaminati** [tidyverse/dplyr#3190] opened 2017-11-05 16:53 UTC
Calls to `select`, `rename` and `filter` induce dplyr to generate subqueries that are excessive. Here's the output from the example below:

```
SELECT "TBL_LEFT"."year" AS "year.x", "TBL_LEFT"."month" AS "month.x", "TBL_LEFT"."day" AS "day", "TBL_RIGHT"."year" AS "year.y", "TBL_RIGHT"."month" AS "month.y"
  FROM (SELECT "year" AS "year", "month" AS "month", "day" AS "day"
FROM "flights") "TBL_LEFT"
  LEFT JOIN (SELECT "year" AS "year", "month" AS "month", "day" AS "day"
FROM "flights") "TBL_RIGHT"
  ON ("TBL_LEFT"."month" = "TBL_RIGHT"."day")
```

```
con <- DBI::dbConnect(
  drv = RPostgreSQL::PostgreSQL(),
  dbname = creds$db_name,
  host = creds$host,
  user = creds$user,
  password = creds$password,
  port = creds$port
)

copy_to(con, nycflights13::flights, "flights",
  indexes = list(
    c("year", "month", "day"), 
    "carrier", 
    "tailnum",
    "dest"
  )
)
f1 <- tbl(con, "flights") %>% select(1:3)
f2 <- tbl(con, "flights") %>% select(1:3)
left_join(f1, f2, by=c("month"="day")) %>% show_query()
```

**Comment by hadley** [comment] 2017-11-06 22:59
I think the join is the root cause of the problem, and hence this is a duplicate of #3091

**Closed by hadley** 2017-11-06 22:59 UTC

**Comment by ilyaminati** [comment] 2017-11-06 23:06
@hadley This problem doesn't occur if you remove the `select` calls in my example, i.e.,

```
f1 <- tbl(con, "flights")
f2 <- tbl(con, "flights")
```

**Comment by hadley** [comment] 2017-11-06 23:14
Right but it doesn't occur without the joins - the joins are forcing subqueries when it doesn't really need to.
