### ISSUE TITLE
Feature Request: Sql functions when joining datasets

### ISSUE THREAD

**Issue by javierluraschi** [tidyverse/dplyr#4214] opened 2019-02-22 02:47 UTC
Can we use custom SQL functions when joining tables under the `by` parameter? Seems to me this in unsupported but is quite important when doing Geo Spatial analysis in SQL.

This is how a query looks in GeoSpark with `sparklyr`, which works fine in DBI:

```r
DBI::dbGetQuery(sc, "
  SELECT area, state, count(*) cnt FROM
    (SELECT area, ST_GeomFromWKT(polygons.geom ,'4326') as y FROM polygons) polygons
  INNER JOIN
    (SELECT ST_GeomFromWKT (points.geom,'4326') as x, state, city FROM points) points
  WHERE ST_Contains(polygons.y,points.x) GROUP BY area, state")
```

However, the following throws an error:

```r
library(dplyr)
polygons_wkt <- mutate(polygons_wkt, y = st_geomfromwkt(geom, "4326"))
points_wkt <- mutate(points_wkt, x = st_geomfromwkt(geom, "4326"))

inner_join(polygons_wkt, points_wkt, by = st_contains(y, x)) %>%
  group_by(area, state) %>%
  summarise(cnt = n())
```
```
Error in st_contains(y, x) : could not find function "st_contains"
```

Is there a known workaround?

CC: @edgararuiz

**Comment by krlmlr** [comment] 2019-02-22 03:01
There is #2240 for _dplyr_, but it's going to take a while. For databases we already have a workaround: https://github.com/tidyverse/dbplyr/pull/146.

**Comment by javierluraschi** [comment] 2019-02-22 06:15
Wasn't aware of the workaround! That helps a lot! But it would be really nice to support this, long-term. Thank you!

**Comment by romainfrancois** [comment] 2019-02-22 08:12
I'll close this as a duplicate of #2240. Flexible joins are on the radar, but that might not happen in the 0.9.* series.

**Closed by romainfrancois** 2019-02-22 08:12 UTC

**Comment by krlmlr** [comment] 2019-06-29 08:33
FWIW, flexible joins are now available in dbplyr with the new `sql_on` argument.
