### ISSUE TITLE
dplyr crash on character string lambda-style expression

### ISSUE THREAD

**Issue by vpanfilov** [tidyverse/dplyr#4390] opened 2019-05-28 09:09 UTC
Hello, dplyr 0.8.1 crashes on R 3.6.0 on `mutate_at` with lambda-style expression containing only character string. Similar code worked completely fine in previous R and dplyr versions.

When I add curly braces around character string it works completely normal again. 

```r
library(tidyverse)
#> Registered S3 methods overwritten by 'ggplot2':
#>   method         from 
#>   [.quosures     rlang
#>   c.quosures     rlang
#>   print.quosures rlang
iris %>%
    head(1) %>%
    mutate_at(1, ~ {"test"})
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 1         test         3.5          1.4         0.2  setosa

iris %>%
    head(1) %>%
    mutate_at(1, ~ "test")
#>  R SESSION CRASH
```

<sup>Created on 2019-05-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
sessionInfo()
#> R version 3.6.0 (2019-04-26)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 17134)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=Russian_Russia.1251  LC_CTYPE=Russian_Russia.1251   
#> [3] LC_MONETARY=Russian_Russia.1251 LC_NUMERIC=C                   
#> [5] LC_TIME=Russian_Russia.1251    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] forcats_0.4.0   stringr_1.4.0   dplyr_0.8.1     purrr_0.3.2    
#> [5] readr_1.3.1     tidyr_0.8.3     tibble_2.1.1    ggplot2_3.1.1  
#> [9] tidyverse_1.2.1
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.1       cellranger_1.1.0 pillar_1.4.0     compiler_3.6.0  
#>  [5] highr_0.8        plyr_1.8.4       tools_3.6.0      digest_0.6.19   
#>  [9] lubridate_1.7.4  jsonlite_1.6     evaluate_0.13    nlme_3.1-139    
#> [13] gtable_0.3.0     lattice_0.20-38  pkgconfig_2.0.2  rlang_0.3.4     
#> [17] cli_1.1.0        yaml_2.2.0       haven_2.1.0      xfun_0.7        
#> [21] withr_2.1.2      xml2_1.2.0       httr_1.4.0       knitr_1.23      
#> [25] hms_0.4.2        generics_0.0.2   grid_3.6.0       tidyselect_0.2.5
#> [29] glue_1.3.1       R6_2.4.0         readxl_1.3.1     rmarkdown_1.12  
#> [33] modelr_0.1.4     magrittr_1.5     backports_1.1.4  scales_1.0.0    
#> [37] htmltools_0.3.6  rvest_0.3.4      assertthat_0.2.1 colorspace_1.4-1
#> [41] stringi_1.4.3    lazyeval_0.2.2   munsell_0.5.0    broom_0.5.2     
#> [45] crayon_1.3.4
```

</details>

**Comment by romainfrancois** [comment] 2019-05-28 11:28
duplicate of #4374 and fixed in #4375. 

``` r
library(dplyr, warn.conflicts = FALSE)

iris %>%
  head(1) %>%
  mutate_at(1, ~ "test")
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> 1         test         3.5          1.4         0.2  setosa
```

**Closed by romainfrancois** 2019-05-28 11:28 UTC
