### ISSUE TITLE
bind_rows with lists in v1.0.0 very slow

### ISSUE THREAD

**Issue by mrcaseb** [tidyverse/dplyr#5370] opened 2020-06-30 08:05 UTC
I was noticing this when running code which uses `purrr:map_dfr()`, where `dplyr::bind_rows()` is used with the list output of `purrr:map()`. This operation is much slower under dplyr v1.0.0 compared to dplyr v0.8.5

I have tried to create a reprex but had to run it twice because of the different dplyr versions required to show the issue. And I have used `microbenchmark` to show runtimes. And sorry the warnings are in german and I took out my username in the session info.

Summary: `dplyr::bind_rows()` with a list under v1.0.0 takes nearly 1400 times the runtime

My current solution is using a tibble instead of a list but that's not always possible for me, still slower than the list in v0.8.5 and I wonder if this is a bug or not.

# reprex with dplyr v0.8.5

``` r
library(dplyr, warn.conflicts = FALSE)
library(purrr)
library(microbenchmark)
#> Warning: Paket 'microbenchmark' wurde unter R Version 4.0.2 erstellt

new_list <- map(1:1000, function(x) {
  list(A = 2 * x, B = 4 * x)
})

microbenchmark(
  df_from_list <- bind_rows(new_list),
  unit = "ms"
)
#> Unit: milliseconds
#>                                 expr    min      lq     mean  median      uq
#>  df_from_list <- bind_rows(new_list) 0.4159 0.44735 0.514581 0.47285 0.51215
#>     max neval
#>  2.9434   100
```

<sup>Created on 2020-06-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 4.0.0 (2020-04-24)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  German_Germany.1252         
#>  ctype    German_Germany.1252         
#>  tz       Europe/Berlin               
#>  date     2020-06-30                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package        * version date       lib source        
#>  assertthat       0.2.1   2019-03-21 [1] CRAN (R 4.0.0)
#>  backports        1.1.8   2020-06-17 [1] CRAN (R 4.0.0)
#>  callr            3.4.3   2020-03-28 [1] CRAN (R 4.0.0)
#>  cli              2.0.2   2020-02-28 [1] CRAN (R 4.0.0)
#>  crayon           1.3.4   2017-09-16 [1] CRAN (R 4.0.0)
#>  desc             1.2.0   2018-05-01 [1] CRAN (R 4.0.0)
#>  devtools         2.3.0   2020-04-10 [1] CRAN (R 4.0.0)
#>  digest           0.6.25  2020-02-23 [1] CRAN (R 4.0.0)
#>  dplyr          * 0.8.5   2020-03-07 [1] CRAN (R 4.0.0)
#>  ellipsis         0.3.1   2020-05-15 [1] CRAN (R 4.0.0)
#>  evaluate         0.14    2019-05-28 [1] CRAN (R 4.0.0)
#>  fansi            0.4.1   2020-01-08 [1] CRAN (R 4.0.0)
#>  fs               1.4.1   2020-04-04 [1] CRAN (R 4.0.0)
#>  glue             1.4.1   2020-05-13 [1] CRAN (R 4.0.0)
#>  highr            0.8     2019-03-20 [1] CRAN (R 4.0.0)
#>  htmltools        0.5.0   2020-06-16 [1] CRAN (R 4.0.0)
#>  knitr            1.28    2020-02-06 [1] CRAN (R 4.0.0)
#>  lifecycle        0.2.0   2020-03-06 [1] CRAN (R 4.0.0)
#>  magrittr         1.5     2014-11-22 [1] CRAN (R 4.0.0)
#>  memoise          1.1.0   2017-04-21 [1] CRAN (R 4.0.0)
#>  microbenchmark * 1.4-7   2019-09-24 [1] CRAN (R 4.0.2)
#>  pillar           1.4.4   2020-05-05 [1] CRAN (R 4.0.0)
#>  pkgbuild         1.0.8   2020-05-07 [1] CRAN (R 4.0.0)
#>  pkgconfig        2.0.3   2019-09-22 [1] CRAN (R 4.0.0)
#>  pkgload          1.1.0   2020-05-29 [1] CRAN (R 4.0.0)
#>  prettyunits      1.1.1   2020-01-24 [1] CRAN (R 4.0.0)
#>  processx         3.4.2   2020-02-09 [1] CRAN (R 4.0.0)
#>  ps               1.3.3   2020-05-08 [1] CRAN (R 4.0.0)
#>  purrr          * 0.3.4   2020-04-17 [1] CRAN (R 4.0.0)
#>  R6               2.4.1   2019-11-12 [1] CRAN (R 4.0.0)
#>  Rcpp             1.0.4.6 2020-04-09 [1] CRAN (R 4.0.0)
#>  remotes          2.1.1   2020-02-15 [1] CRAN (R 4.0.0)
#>  rlang            0.4.6   2020-05-02 [1] CRAN (R 4.0.0)
#>  rmarkdown        2.3     2020-06-18 [1] CRAN (R 4.0.0)
#>  rprojroot        1.3-2   2018-01-03 [1] CRAN (R 4.0.0)
#>  sessioninfo      1.1.1   2018-11-05 [1] CRAN (R 4.0.0)
#>  stringi          1.4.6   2020-02-17 [1] CRAN (R 4.0.0)
#>  stringr          1.4.0   2019-02-10 [1] CRAN (R 4.0.0)
#>  testthat         2.3.2   2020-03-02 [1] CRAN (R 4.0.0)
#>  tibble           3.0.1   2020-04-20 [1] CRAN (R 4.0.0)
#>  tidyselect       1.1.0   2020-05-11 [1] CRAN (R 4.0.0)
#>  usethis          1.6.1   2020-04-29 [1] CRAN (R 4.0.0)
#>  vctrs            0.3.1   2020-06-05 [1] CRAN (R 4.0.0)
#>  withr            2.2.0   2020-04-20 [1] CRAN (R 4.0.0)
#>  xfun             0.15    2020-06-21 [1] CRAN (R 4.0.0)
#>  yaml             2.2.1   2020-02-01 [1] CRAN (R 4.0.0)
#> 
#> [1] C:/Users/.../Documents/R/win-library/4.0
#> [2] C:/Program Files/R/R-4.0.0/library
```

</details>

# reprex with dplyr v1.0.0

``` r
library(dplyr, warn.conflicts = FALSE)
#> Warning: Paket 'dplyr' wurde unter R Version 4.0.2 erstellt
library(purrr)
library(microbenchmark)
#> Warning: Paket 'microbenchmark' wurde unter R Version 4.0.2 erstellt

new_list <- map(1:1000, function(x) {
  list(A = 2 * x, B = 4 * x)
})

microbenchmark(
  df_from_list <- bind_rows(new_list),
  unit = "ms"
)
#> Unit: milliseconds
#>                                 expr      min       lq     mean   median
#>  df_from_list <- bind_rows(new_list) 663.8838 690.2547 699.2142 696.8235
#>        uq      max neval
#>  704.9832 765.9711   100
```

<sup>Created on 2020-06-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 4.0.0 (2020-04-24)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  German_Germany.1252         
#>  ctype    German_Germany.1252         
#>  tz       Europe/Berlin               
#>  date     2020-06-30                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package        * version date       lib source        
#>  assertthat       0.2.1   2019-03-21 [1] CRAN (R 4.0.0)
#>  backports        1.1.8   2020-06-17 [1] CRAN (R 4.0.0)
#>  callr            3.4.3   2020-03-28 [1] CRAN (R 4.0.0)
#>  cli              2.0.2   2020-02-28 [1] CRAN (R 4.0.0)
#>  crayon           1.3.4   2017-09-16 [1] CRAN (R 4.0.0)
#>  desc             1.2.0   2018-05-01 [1] CRAN (R 4.0.0)
#>  devtools         2.3.0   2020-04-10 [1] CRAN (R 4.0.0)
#>  digest           0.6.25  2020-02-23 [1] CRAN (R 4.0.0)
#>  dplyr          * 1.0.0   2020-05-29 [1] CRAN (R 4.0.2)
#>  ellipsis         0.3.1   2020-05-15 [1] CRAN (R 4.0.0)
#>  evaluate         0.14    2019-05-28 [1] CRAN (R 4.0.0)
#>  fansi            0.4.1   2020-01-08 [1] CRAN (R 4.0.0)
#>  fs               1.4.1   2020-04-04 [1] CRAN (R 4.0.0)
#>  generics         0.0.2   2018-11-29 [1] CRAN (R 4.0.0)
#>  glue             1.4.1   2020-05-13 [1] CRAN (R 4.0.0)
#>  highr            0.8     2019-03-20 [1] CRAN (R 4.0.0)
#>  htmltools        0.5.0   2020-06-16 [1] CRAN (R 4.0.0)
#>  knitr            1.28    2020-02-06 [1] CRAN (R 4.0.0)
#>  lifecycle        0.2.0   2020-03-06 [1] CRAN (R 4.0.0)
#>  magrittr         1.5     2014-11-22 [1] CRAN (R 4.0.0)
#>  memoise          1.1.0   2017-04-21 [1] CRAN (R 4.0.0)
#>  microbenchmark * 1.4-7   2019-09-24 [1] CRAN (R 4.0.2)
#>  pillar           1.4.4   2020-05-05 [1] CRAN (R 4.0.0)
#>  pkgbuild         1.0.8   2020-05-07 [1] CRAN (R 4.0.0)
#>  pkgconfig        2.0.3   2019-09-22 [1] CRAN (R 4.0.0)
#>  pkgload          1.1.0   2020-05-29 [1] CRAN (R 4.0.0)
#>  prettyunits      1.1.1   2020-01-24 [1] CRAN (R 4.0.0)
#>  processx         3.4.2   2020-02-09 [1] CRAN (R 4.0.0)
#>  ps               1.3.3   2020-05-08 [1] CRAN (R 4.0.0)
#>  purrr          * 0.3.4   2020-04-17 [1] CRAN (R 4.0.0)
#>  R6               2.4.1   2019-11-12 [1] CRAN (R 4.0.0)
#>  remotes          2.1.1   2020-02-15 [1] CRAN (R 4.0.0)
#>  rlang            0.4.6   2020-05-02 [1] CRAN (R 4.0.0)
#>  rmarkdown        2.3     2020-06-18 [1] CRAN (R 4.0.0)
#>  rprojroot        1.3-2   2018-01-03 [1] CRAN (R 4.0.0)
#>  sessioninfo      1.1.1   2018-11-05 [1] CRAN (R 4.0.0)
#>  stringi          1.4.6   2020-02-17 [1] CRAN (R 4.0.0)
#>  stringr          1.4.0   2019-02-10 [1] CRAN (R 4.0.0)
#>  testthat         2.3.2   2020-03-02 [1] CRAN (R 4.0.0)
#>  tibble           3.0.1   2020-04-20 [1] CRAN (R 4.0.0)
#>  tidyselect       1.1.0   2020-05-11 [1] CRAN (R 4.0.0)
#>  usethis          1.6.1   2020-04-29 [1] CRAN (R 4.0.0)
#>  vctrs            0.3.1   2020-06-05 [1] CRAN (R 4.0.0)
#>  withr            2.2.0   2020-04-20 [1] CRAN (R 4.0.0)
#>  xfun             0.15    2020-06-21 [1] CRAN (R 4.0.0)
#>  yaml             2.2.1   2020-02-01 [1] CRAN (R 4.0.0)
#> 
#> [1] C:/Users/.../Documents/R/win-library/4.0
#> [2] C:/Program Files/R/R-4.0.0/library
```

</details>

**Comment by lionel-** [comment] 2020-06-30 09:04
A large part of the overhead comes from dplyr:

```r
bench::mark(
  vctrs = vctrs::vec_rbind(!!!new_list),
  dplyr = dplyr::bind_rows(new_list),
  check = FALSE
)[1:8]

# dplyr 0.8.5
#>   expression      min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>
#> 1 vctrs        16.3ms   18.4ms      55.4    35.4KB     77.5    10    14
#> 2 dplyr       494.5µs  635.9µs    1536.     23.6KB     31.3   687    14

# dplyr 1.0.0
#>   expression      min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>
#> 1 vctrs        14.2ms   15.5ms     57.7     35.4KB    13.9     29     7
#> 2 dplyr       661.2ms  661.2ms      1.51     903KB     9.07     1     6
```

It would still be nice to reach performance level of dplyr 0.8.5 for this simple case, so I have opened https://github.com/r-lib/vctrs/issues/1169.

@mrcaseb In the mean time maybe create data frames instead of lists:

```r
new_list2 <- purrr::map(1:1000, function(x) {
  data.frame(A = 2 * x, B = 4 * x)
})

bench::mark(
  vctrs = vctrs::vec_rbind(!!!new_list2),
  dplyr = dplyr::bind_rows(new_list2),
  check = FALSE
)[1:8]
#>   expression      min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>
#> 1 vctrs        3.15ms   3.33ms      297.    35.4KB     20.1   133     9
#> 2 dplyr        7.04ms   7.43ms      134.    82.7KB     25.7    52    10
```

**Comment by romainfrancois** [comment] 2020-06-30 09:30
I can get to better performance using `vctrs::new_data_frame()` instead of `tibble(!!!)` : 

before: (with. `tibble()`): 

```
[master] 166.1 MiB ❯ callr::r(f)
# A tibble: 1 x 13
  expression               min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result                memory                      time         gc              
  <bch:expr>          <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>                <list>                      <list>       <list>          
1 bind_rows(new_list)    5.62s    5.62s     0.178    9.38MB     19.4     1   109      5.62s <tibble [10,000 × 2]> <Rprofmem[,3] [34,104 × 3]> <bch:tm [1]> <tibble [1 × 3]>
```


with `vctrs::new_data_frame()`:  

```
[bind_rows_list_perf] 166.1 MiB ❯ callr::r(f)
# A tibble: 1 x 13
  expression               min   median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result                memory                     time         gc              
  <bch:expr>          <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>                <list>                     <list>       <list>          
1 bind_rows(new_list)    232ms    254ms      3.93    1.01MB     43.3     2    22      509ms <tibble [10,000 × 2]> <Rprofmem[,3] [1,154 × 3]> <bch:tm [2]> <tibble [2 × 3]>
```

**Comment by romainfrancois** [comment] 2020-06-30 09:35
@lionel- however `vctrs::vec_rbind()` does not do what `bind_rows()` want here, hence we have to transform the list to a data frame before calling `vec_rbind()`: 

``` r
library(dplyr, warn.conflicts = FALSE)
library(purrr)

new_list <- map(1:2, function(x) {
  list(A = 2 * x, B = 4 * x)
})
str(dplyr::bind_rows(new_list))
#> tibble [2 × 2] (S3: tbl_df/tbl/data.frame)
#>  $ A: num [1:2] 2 4
#>  $ B: num [1:2] 4 8
str(vctrs::vec_rbind(!!!new_list))
#> 'data.frame':    2 obs. of  2 variables:
#>  $ A:List of 2
#>   ..$ : num 2
#>   ..$ : num 4
#>  $ B:List of 2
#>   ..$ : num 4
#>   ..$ : num 8
```

<sup>Created on 2020-06-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Comment by hadley** [comment] 2020-07-01 13:37
I think the root cause of the difference is that `bind_rows()` does auto-splicing but `vec_rbind()` does not. Generally, I think autosplicing was a mistake, so we need to carefully think about how to keep dplyr backward compatible, without doing a bunch of extra work in vctrs.

**Comment by hadley** [comment] 2020-08-28 15:08
It's still not as good as 0.8.5, but it's no longer awful, so I'm going to close this issue and we'll track in the related vctrs issue:

``` r
library(dplyr, warn.conflicts = FALSE)
#> Warning: replacing previous import 'vctrs::data_frame' by 'tibble::data_frame'
#> when loading 'dplyr'

new_list <- lapply(1:1000, function(x) {
  list(A = 2 * x, B = 4 * x)
})

bench::mark(
  vctrs = vctrs::vec_rbind(!!!new_list),
  dplyr = dplyr::bind_rows(new_list),
  check = FALSE
)[1:8]
#> # A tibble: 2 x 6
#>   expression      min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr> <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 vctrs        9.42ms   11.7ms      83.6     112KB     35.8
#> 2 dplyr       11.99ms   12.4ms      80.6     479KB     31.7
```

<sup>Created on 2020-08-28 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

**Closed by hadley** 2020-08-28 15:08 UTC
