### ISSUE TITLE
Incorrect results for all.equal(tibble1, tibble2)

### ISSUE THREAD

**Issue by kenahoo** [tidyverse/dplyr#4574] opened 2019-09-30 19:43 UTC
Using `dplyr` version 0.8.3.

```
tibble <- dplyr::tibble

data <- tibble(a = c(0.287577520124614, 0.788305135443807, 0.4089769218117, 0.883017404004931,
                     0.940467284293845, 0.0455564993899316, 0.528105488047004, 0.892419044394046,
                     0.551435014465824, 0.456614735303447, 0.956833345349878, 0.453334156190977),
               b = c(0.677570635452867, 0.572633401956409, 0.102924682665616, 0.899824970401824,
                     0.24608773435466, 0.0420595335308462, 0.327920719282702, 0.954503649147227,
                     0.889539316063747, 0.6928034061566, 0.640506813768297, 0.994269776623696))

result <- tibble(frac = data$a / data$b)

expected <- tibble(frac = c(0.424424414337859, 1.37663142378798, 3.97355533405328, 0.98132129364071,
                            3.82167476473431, 1.08314323924969, 1.61046697263347, 0.934956136827084,
                            0.619910783601954, 0.659082693944254, 1.49386911236828, 0.455946833394043))

all.equal.default(result, expected)
#> [1] TRUE

all.equal(result, expected)

#> [1] "Rows in x but not y: 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2[...]. Rows in y but not x: 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2[...]. "
```

I'm not sure if I'm having a numerical precision issue and the issue is just in the error message, or whether there's something else going on.

The language of "Rows in x but not y" is a little confusing to me, not sure whether it's trying to compare the tibbles as sets or rows, or compare the row names, or something else?

The two tables do have identical `dput` output:

```
> dput(result)
structure(list(frac = c(0.424424414337859, 1.37663142378798, 
3.97355533405328, 0.98132129364071, 3.82167476473431, 1.08314323924969, 
1.61046697263347, 0.934956136827084, 0.619910783601954, 0.659082693944254, 
1.49386911236828, 0.455946833394043)), row.names = c(NA, -12L
), class = c("tbl_df", "tbl", "data.frame"))
> dput(expected)
structure(list(frac = c(0.424424414337859, 1.37663142378798, 
3.97355533405328, 0.98132129364071, 3.82167476473431, 1.08314323924969, 
1.61046697263347, 0.934956136827084, 0.619910783601954, 0.659082693944254, 
1.49386911236828, 0.455946833394043)), row.names = c(NA, -12L
), class = c("tbl_df", "tbl", "data.frame"))
```

**Comment by kenahoo** [comment] 2019-09-30 19:52
If this is a numerical precision issue, it does not seem to be helped by using the standard `tolerance` argument for `all.equal()`:

```
all.equal(result, expected, tolerance=1e-2)
#> [1] "Rows in x but not y: 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2[...]. Rows in y but not x: 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2[...]. "
```

**Comment by rjpatgit** [comment] 2019-10-01 11:42
This seems like a breaking issue already documented in #2751. It seems the work around is to convert it to a dataframe or in this example specify the column.

``` r
data <- dplyr::tibble(a = c(0.287577520124614, 0.788305135443807, 0.4089769218117, 0.883017404004931,
                             0.940467284293845, 0.0455564993899316, 0.528105488047004, 0.892419044394046,
                             0.551435014465824, 0.456614735303447, 0.956833345349878, 0.453334156190977),
                       b = c(0.677570635452867, 0.572633401956409, 0.102924682665616, 0.899824970401824,
                             0.24608773435466, 0.0420595335308462, 0.327920719282702, 0.954503649147227,
                             0.889539316063747, 0.6928034061566, 0.640506813768297, 0.994269776623696))

result <- dplyr::tibble(frac = data$a / data$b)

expected <- dplyr::tibble(frac = c(0.424424414337859, 1.37663142378798, 3.97355533405328, 0.98132129364071,
                                    3.82167476473431, 1.08314323924969, 1.61046697263347, 0.934956136827084,
                                    0.619910783601954, 0.659082693944254, 1.49386911236828, 0.455946833394043))

all.equal(as.data.frame(expected), as.data.frame(result))
#> [1] TRUE

all.equal(result$frac, expected$frac)
#> [1] TRUE
```

<sup>Created on 2019-10-01 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by kenahoo** [comment] 2019-10-01 17:41
You're right, that does look like the same issue.  A bit disheartening that the bug was reported 2.5 years ago, though - and it looks like a commit to address it was performed by @krlmlr in https://github.com/tidyverse/tibble/issues/247, not sure why that's not taking care of things now?  Is it because `dplyr` isn't delegating to `tibble` properly?  It seems to provide its own `dplyr:::all.equal.tbl_df` method, which is intercepting the call here.

**Comment by kenahoo** [comment] 2019-10-02 17:20
I created a branch that removes `dplyr:::all.equal.dbl_df`, and tests that `all.equal(t1, t2)` works as expected:  https://github.com/tidyverse/dplyr/compare/master...kenahoo:remove-all.equal

Unfortunately it looks like it makes a whole bunch of other tests fail.  I haven't looked into many of the failures, but at least one looks like an invalid test:

```
# In test-tbl-cube.R:
test_that("incomplete", {
  d <- rbind(
    cbind(data.frame(s = 1), expand.grid(j = 1)),
    cbind(data.frame(s = 2), expand.grid(j = 1:2))
  )
  d$value <- 1:3

  cube <- as.tbl_cube(d, met_name = "value")
  expect_true(is.na(as.data.frame(filter(cube, s == 1, j == 2))[["value"]]))
  expect_equal(filter(as_tibble(cube), s != 1 | j != 2), d)
  # the above line is comparing a tibble and a data.frame, it shouldn't pass, but it does in the current 'master' branch.
})
```

**Comment by kenahoo** [comment] 2019-10-07 15:24
@romainfrancois @hadley @krlmlr I believe there is a decision that needs to be made here: do you want the `all.equal` method of tibbles to behave basically like `all.equal.data.frame`, which is what happens if you use the `tibble` package directly, and don't load `dplyr`?  

Or do you want it to have a very different notion of equality, as shown by tests like the one below?

```
# 'dplyr' package, file tests/testthat/test-equality.r
test_that("data frames equal to random permutations of themselves", {
  scramble <- function(x) {
    x[sample(nrow(x)), sample(ncol(x)), drop = FALSE]
  }

  expect_equal(tbl_df(mtcars), tbl_df(scramble(mtcars)))
  expect_equal(tbl_df(iris), tbl_df(scramble(iris)))
  expect_equal(tbl_df(df_all), tbl_df(scramble(df_all)))
})
```

There are various tests like these in the `dplyr` tests.  My vote would be to get rid of these tests.  I'm aware that it is often bad practice to assume an ordering on a tibble (by analogy with a database table), but absolutism leads to non-helpful results like `all.equal(df, arrange(df, col))` being tautologically true.

The situation right now is probably the worst of all - tibbles silently compare differently depending on whether or not you have the `dplyr` package loaded.

**Comment by hadley** [comment] 2019-12-10 22:25
Yes, we need to remove `all.equal.tbl_df()` — i.e. this is duplicate of #2751.

**Closed by hadley** 2019-12-10 22:25 UTC
