### ISSUE TITLE
SET_STRING_ELT() error

### ISSUE THREAD

**Issue by bigmw** [tidyverse/dplyr#3270] opened 2017-12-30 19:47 UTC
I was using tq_performance function in the tidyquant package, which calls functions in dplyr package. Example code:
https://cran.r-project.org/web/packages/tidyquant/vignettes/TQ05-performance-analysis-with-tidyquant.html

Unfortunately, I got errors saying calls to mutate_impl and SET_STRING_ELT() had problem. 

> RaRb_capm <- RaRb %>%
     tq_performance(Ra = Ra, 
                    Rb = Rb, 
                    performance_fun = table.CAPM)
Error in mutate_impl(.data, dots) : 
  Evaluation error: Value of SET_STRING_ELT() must be a 'CHARSXP' not a 'NULL'.

I’ve posted the details at https://github.com/business-science/tidyquant/issues/88. But I believe I can get help here as this is also dplyr issue. Thanks for any help/suggestions.

**Comment by batpigandme** [comment] 2017-12-30 20:15
Hi @bigmw ,

For here _and_ https://github.com/business-science/tidyquant/issues/88, it'll be much easier to help you troubleshoot if you can include [reprex](http://reprex.tidyverse.org/) (short for **repr**oducible **ex**ample).

If you've never heard of a reprex before, you might want to start by reading the tidyverse.org [help page](https://www.tidyverse.org/help/).

Thanks

**Comment by bigmw** [comment] 2017-12-30 20:51
Thanks for the quick response! I think the example code in the CRAN url is an reproduciable example. Below is the exact lines of code as to follow the reprex guideline. I don’t have reprex and rstudio installed, I am running command line R sessions through remote login. I included all the R session info in the original post. Let me know if you need anything else. Thanks.

library(tidyquant)
Ra <- c("AAPL", "GOOG", "NFLX") %>%
    tq_get(get  = "stock.prices",
           from = "2010-01-01",
           to   = "2015-12-31") %>%
    group_by(symbol) %>%
    tq_transmute(select     = adjusted, 
                 mutate_fun = periodReturn, 
                 period     = "monthly", 
                 col_rename = "Ra")

Rb <- "XLK" %>%
    tq_get(get  = "stock.prices",
           from = "2010-01-01",
           to   = "2015-12-31") %>%
    tq_transmute(select     = adjusted, 
                 mutate_fun = periodReturn, 
                 period     = "monthly", 
                 col_rename = "Rb")

RaRb <- left_join(Ra, Rb, by = c("date" = "date"))

RaRb_capm <- RaRb %>%
    tq_performance(Ra = Ra, 
                   Rb = Rb, 
                   performance_fun = table.CAPM)

**Comment by krlmlr** [comment] 2017-12-31 01:14
This works on my Windows machine.

**Comment by bigmw** [comment] 2017-12-31 23:35
I ran the code with R 3.5.0 (devel version) on macOS Sierra 10.12.6. for detailed environment info see the sessionInfo() section of the original post: https://github.com/business-science/tidyquant/issues/88. 
Thanks for the help.

**Comment by krlmlr** [comment] 2018-01-17 09:00
Thanks again. Still works for me on OS X High Sierra with R 3.4.3 and latest packages.

From the session info I see you have rlang 0.1.4 installed. Can you please try on R 3.4.3 with up-to-date packages?

**Comment by romainfrancois** [comment] 2018-04-11 07:47
I can't reproduce it, and I see the original issue has been closed so I'll close it here as well.

**Closed by romainfrancois** 2018-04-11 07:47 UTC
Labels: reprex
