### ISSUE TITLE
sample_n() (with grouping) drastically slower in 0.7.4

### ISSUE THREAD

**Issue by briglass** [tidyverse/dplyr#3561] opened 2018-05-08 15:52 UTC
Upgraded from 0.5.* to 0.7.4, and sample_n() function is running drastically slower. Has anybody else noticed this?

**Comment by krlmlr** [comment] 2018-05-08 15:56
Can you please post example code? Has this changed in the development version?

**Comment by batpigandme** [comment] 2018-05-08 15:57
Hi @briglass, 

Since it's in a ~discussion phase (as opposed to being a bug or feature request), this sort of question might be a better fit for https://community.rstudio.com. Would you mind asking it over there? If it turns out the issue is with dplyr code, we can reopen it.

(You might want to check out https://www.tidyverse.org/help/ first to maximise your chances of getting a good answer.)

**Comment by briglass** [comment] 2018-05-08 16:12
I will try to provide one using a public data set, but for now let me specify that this only occurs with a grouped data frame.

df characteristics:
```
# A tibble: 129,874 x 311
# Groups:   ID_PRSN [70,392]
```
Then, I try: `df %>% sample_n(1)` in order to take 1 row per ID_PRSN

This takes roughly 1 minute in 0.7.4. In the previous dplyr version, it took a few seconds

**Comment by briglass** [comment] 2018-05-08 17:59
I tried this with dev version 0.7.5.9000, but got this error:

```
Error in FUN(X[[i]], ...) : 
  object '_dplyr_quo_is_variable_reference' not found
````

**Comment by batpigandme** [comment] 2018-05-08 18:48
Ran the code above with the dev versions…

``` r
suppressPackageStartupMessages(library(tidyverse))
n = 500000
leng = 5

d1 = tbl_df(data.frame( ID_P=round(runif(n)*(10^leng)), ID_R=round(runif(n)*(10^leng))))
stime=Sys.time()
ds = d1 %>% group_by(ID_P) %>% sample_n(1) %>% ungroup() %>% group_by(ID_R) %>% sample_n(1) %>% ungroup()
print(Sys.time() - stime)
#> Time difference of 4.583714 secs
```
Created on 2018-05-08 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by hadley** [comment] 2018-05-08 19:01
@briglass Could you please rework your reproducible example to use the [reprex package](http://reprex.tidyverse.org) ? That makes it easier to see both the input and the output, formatted in such a way that I can easily re-run in a local session.

**Comment by hadley** [comment] 2018-05-30 13:51
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by hadley** 2018-05-30 13:51 UTC
Labels: reprex
