### ISSUE TITLE
dplyr 0.7.0 can't inner join two tables from different data sources with copy=TRUE

### ISSUE THREAD

**Issue by konny0201** [tidyverse/dplyr#3015] opened 2017-08-09 06:52 UTC
while use then dplyr package up to 0.5.0 version  I got the error :when join two tables from different data sources with copy=TRUE,it is just not work
```r
# insert reprex here
library(dplyr)
data=structure(list(Sepal.Length = c(5.1, 4.9, 4.7, 4.6, 5), Sepal.Width = c(3.5, 3, 3.2, 3.1, 3.6), Petal.Length = c(1.4, 1.4, 1.3, 1.5, 1.4),Petal.Width = c(0.2, 0.2, 0.2, 0.2, 0.2), Species = structure(c(1L,1L, 1L, 1L, 1L), .Label = c("setosa", "versicolor", "virginica"), class = "factor")), .Names = c("Sepal.Length", "Sepal.Width", "Petal.Length", "Petal.Width", "Species"), row.names = c(NA,5L), class = "data.frame")

src_source1<- src_sqlite("data_source1", create = TRUE)
src_source2<- src_sqlite("data_source2", create = TRUE)

copy_to(src_source1,data,'data1',temporary = FALSE)
copy_to(src_source2,data,'data2',temporary = FALSE)

data1=tbl(src_source1,'data1')
data2=tbl(src_source2,'data2')

data1 %>% inner_join(data2,copy=TRUE)

**Comment by hadley** [comment] 2017-10-23 22:38
Duplicate of #3002

**Closed by hadley** 2017-10-23 22:38 UTC
Labels: database
