### ISSUE TITLE
Non-signalling incorrect calculation in dbplyr based mutate

### ISSUE THREAD

**Issue by JohnMount** [tidyverse/dplyr#3223] opened 2017-11-26 16:11 UTC
The following `dbplyr` based `mutate()` has a non-signalling error (that is an incorrect result that is not brought to user attention by an exception).  Examining with `show_query()`: it appears that only 4 of the 5 assignments in the `mutate()` are translated to `SQL`, and one is silently lost.  I know there are related issues filed on complex `mutate()`'s throwing exceptions (and fixes in the works for such), but this kind non-signalling data corruption is important to research and may reveal a different corner-case.  This code may seem complicated, but it is common user code when the user attempts to simulate a per-row conditional assignment.

``` r
library("dplyr")
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
packageVersion("dplyr")
#> [1] '0.7.4'

my_db <- DBI::dbConnect(RSQLite::SQLite(), ":memory:")
d <- copy_to(my_db, 
             data.frame(val = c(0, 5),
                        a_1 = "",
                        a_2 = ""), 
             'd')

# all values in a_1 and a_2 should
# be "treatment" or "control" after
# the following statement.  
# That is not the case.
mutate(d,
       cond = val>2,
       a_1 = ifelse( cond, 
                     'treatment', 
                     a_1),
       a_2 = ifelse( cond, 
                     'control', 
                     a_2),
       a_1 = ifelse( !( cond ), 
                     'control', 
                     a_1),
       a_2 = ifelse( !( cond ), 
                     'treatment', 
                     a_2))
#> # Source:   lazy query [?? x 4]
#> # Database: sqlite 3.19.3 [:memory:]
#>     val     a_1  cond       a_2
#>   <dbl>   <chr> <int>     <chr>
#> 1     0 control     0 treatment
#> 2     5             1   control
```

**Comment by hadley** [comment] 2017-11-28 21:10
Probably duplicate of #3216

**Closed** 2017-12-28 23:11 UTC
Labels: bug, database
