### ISSUE TITLE
spark_tbl throws error when using summarise()

### ISSUE THREAD

**Issue by sriram221189** [tidyverse/dplyr#5613] opened 2020-11-19 09:08 UTC
The spark_tbl does not provide a summarised result when used without a group_by(). 
```r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(sparklyr)

config <- sparklyr::spark_config()
config$`sparklyr.shell.driver-memory` <- "1G"
config$`sparklyr.shell.executor-memory` <- "5G"
config$`spark.sql.crossJoin.enabled` <- "true"
sc <- sparklyr::spark_connect(master = "local[6]", config = config)

copy_to(sc, iris, "iris_spark_tbl")
#> # Source: spark<iris_spark_tbl> [?? x 5]
#>    Sepal_Length Sepal_Width Petal_Length Petal_Width Species
#>           <dbl>       <dbl>        <dbl>       <dbl> <chr>  
#>  1          5.1         3.5          1.4         0.2 setosa 
#>  2          4.9         3            1.4         0.2 setosa 
#>  3          4.7         3.2          1.3         0.2 setosa 
#>  4          4.6         3.1          1.5         0.2 setosa 
#>  5          5           3.6          1.4         0.2 setosa 
#>  6          5.4         3.9          1.7         0.4 setosa 
#>  7          4.6         3.4          1.4         0.3 setosa 
#>  8          5           3.4          1.5         0.2 setosa 
#>  9          4.4         2.9          1.4         0.2 setosa 
#> 10          4.9         3.1          1.5         0.1 setosa 
#> # … with more rows
tbl(sc, "iris_spark_tbl") %>% summarise(row_count = n())
#> Error in regexpr("`", x)[[1]]: subscript out of bounds
Created on 2020-11-19 by the reprex package (v0.3.0)
```

The error appears for functions like count(), which eventually uses summarise() without any grouping.

Session information is provided below:
```
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 4.0.2 (2020-06-22)
#>  os       Ubuntu 20.04 LTS            
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       Etc/UTC                     
#>  date     2020-11-19                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version date       lib source        
#>  assertthat    0.2.1   2019-03-21 [2] CRAN (R 4.0.2)
#>  cli           2.1.0   2020-10-12 [2] CRAN (R 4.0.2)
#>  crayon        1.3.4   2017-09-16 [2] CRAN (R 4.0.2)
#>  digest        0.6.27  2020-10-24 [2] CRAN (R 4.0.2)
#>  evaluate      0.14    2019-05-28 [2] CRAN (R 4.0.2)
#>  fansi         0.4.1   2020-01-08 [2] CRAN (R 4.0.2)
#>  glue          1.4.2   2020-08-27 [2] CRAN (R 4.0.2)
#>  highr         0.8     2019-03-20 [2] CRAN (R 4.0.2)
#>  htmltools     0.5.0   2020-06-16 [2] CRAN (R 4.0.2)
#>  knitr         1.30    2020-09-22 [2] CRAN (R 4.0.2)
#>  magrittr      1.5     2014-11-22 [2] CRAN (R 4.0.2)
#>  rlang         0.4.8   2020-10-08 [2] CRAN (R 4.0.2)
#>  rmarkdown     2.4     2020-09-30 [1] RSPM (R 4.0.2)
#>  sessioninfo   1.1.1   2018-11-05 [2] CRAN (R 4.0.2)
#>  stringi       1.5.3   2020-09-09 [2] CRAN (R 4.0.2)
#>  stringr       1.4.0   2019-02-10 [2] CRAN (R 4.0.2)
#>  withr         2.3.0   2020-09-22 [2] CRAN (R 4.0.2)
#>  xfun          0.19    2020-10-30 [2] CRAN (R 4.0.2)
#>  yaml          2.2.1   2020-02-01 [2] CRAN (R 4.0.2)
#> 
#> [1] /usr/local/lib/R/site-library
#> [2] /usr/local/lib/R/library
Created on 2020-11-19 by the reprex package (v0.3.0)
```

**Comment by romainfrancois** [comment] 2020-11-19 13:33
Please use the excellent [reprex](https://reprex.tidyverse.org) package to update the example, so that we see also the result. Beyond the omitted `"`, I don't see the same problem here when running the code: 

``` r
library(sparklyr) # version 1.4.0
library(dplyr) # version 1.0.2
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
copy_to(sc, iris, "iris_spark_tbl")
#> Error in copy_to(sc, iris, "iris_spark_tbl"): object 'sc' not found
tbl(sc, "iris_spark_tbl") %>% summarise(count = n())
#> Error in tbl(sc, "iris_spark_tbl"): object 'sc' not found
```

<sup>Created on 2020-11-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>

<details style="margin-bottom:10px;">

<summary>Session info</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 4.0.3 (2020-10-10)
#>  os       macOS Catalina 10.15.7      
#>  system   x86_64, darwin17.0          
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_US.UTF-8                 
#>  ctype    en_US.UTF-8                 
#>  tz       Europe/Paris                
#>  date     2020-11-19                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package     * version    date       lib source                               
#>  assertthat    0.2.1      2019-03-21 [1] CRAN (R 4.0.0)                       
#>  backports     1.1.10     2020-09-15 [1] CRAN (R 4.0.2)                       
#>  base64enc     0.1-3      2015-07-28 [1] CRAN (R 4.0.0)                       
#>  cli           2.1.0      2020-10-12 [1] CRAN (R 4.0.2)                       
#>  crayon        1.3.4.9000 2020-11-17 [1] Github (r-lib/crayon@4bceba8)        
#>  DBI           1.1.0      2019-12-15 [1] CRAN (R 4.0.0)                       
#>  dbplyr        2.0.0      2020-11-03 [1] CRAN (R 4.0.0)                       
#>  digest        0.6.27     2020-10-24 [1] CRAN (R 4.0.2)                       
#>  dplyr       * 1.0.2.9000 2020-11-19 [1] local                                
#>  ellipsis      0.3.1      2020-05-15 [1] CRAN (R 4.0.1)                       
#>  evaluate      0.14       2019-05-28 [1] CRAN (R 4.0.0)                       
#>  fansi         0.4.1      2020-01-08 [1] CRAN (R 4.0.0)                       
#>  forge         0.2.0      2019-02-26 [1] CRAN (R 4.0.2)                       
#>  fs            1.5.0      2020-07-31 [1] CRAN (R 4.0.2)                       
#>  generics      0.1.0      2020-10-31 [1] CRAN (R 4.0.2)                       
#>  glue          1.4.2      2020-08-27 [1] CRAN (R 4.0.2)                       
#>  highr         0.8        2019-03-20 [1] CRAN (R 4.0.0)                       
#>  htmltools     0.5.0      2020-06-16 [1] CRAN (R 4.0.0)                       
#>  htmlwidgets   1.5.2.9001 2020-11-17 [1] Github (ramnathv/htmlwidgets@cfeddf0)
#>  httr          1.4.2      2020-07-20 [1] CRAN (R 4.0.2)                       
#>  jsonlite      1.7.1      2020-09-07 [1] CRAN (R 4.0.2)                       
#>  knitr         1.30       2020-09-22 [1] CRAN (R 4.0.2)                       
#>  lifecycle     0.2.0      2020-03-06 [1] CRAN (R 4.0.2)                       
#>  magrittr      1.5        2014-11-22 [1] CRAN (R 4.0.0)                       
#>  pillar        1.4.6      2020-07-10 [1] CRAN (R 4.0.0)                       
#>  pkgconfig     2.0.3      2019-09-22 [1] CRAN (R 4.0.0)                       
#>  purrr         0.3.4      2020-04-17 [1] CRAN (R 4.0.0)                       
#>  r2d3          0.2.3      2018-12-18 [1] CRAN (R 4.0.2)                       
#>  R6            2.5.0      2020-10-28 [1] CRAN (R 4.0.2)                       
#>  reprex        0.3.0.9001 2020-06-19 [1] Github (tidyverse/reprex@d898823)    
#>  rlang         0.4.8      2020-10-08 [1] CRAN (R 4.0.2)                       
#>  rmarkdown     2.3        2020-06-18 [1] CRAN (R 4.0.0)                       
#>  rprojroot     2.0.2      2020-11-15 [1] CRAN (R 4.0.3)                       
#>  rstudioapi    0.13       2020-11-12 [1] CRAN (R 4.0.2)                       
#>  sessioninfo   1.1.1      2018-11-05 [1] CRAN (R 4.0.0)                       
#>  sparklyr    * 1.4.0      2020-09-16 [1] CRAN (R 4.0.2)                       
#>  stringi       1.5.3      2020-09-09 [1] CRAN (R 4.0.2)                       
#>  stringr       1.4.0      2019-02-10 [1] CRAN (R 4.0.0)                       
#>  styler        1.3.2      2020-02-23 [1] CRAN (R 4.0.0)                       
#>  tibble        3.0.4      2020-10-12 [1] CRAN (R 4.0.2)                       
#>  tidyr         1.1.2      2020-08-27 [1] CRAN (R 4.0.2)                       
#>  tidyselect    1.1.0.9000 2020-11-04 [1] local                                
#>  vctrs         0.3.5      2020-11-17 [1] CRAN (R 4.0.3)                       
#>  withr         2.3.0      2020-09-22 [1] CRAN (R 4.0.2)                       
#>  xfun          0.19       2020-10-30 [1] CRAN (R 4.0.2)                       
#>  yaml          2.2.1      2020-02-01 [1] CRAN (R 4.0.0)                       
#> 
#> [1] /Users/romainfrancois/.R/library/4.0
#> [2] /Library/Frameworks/R.framework/Versions/4.0/Resources/library
```

</details>

This might be a `sparklyr` issue ? cc @javierluraschi

**Comment by jkylearmstrong** [comment] 2020-11-19 22:19
ran into similar issue.

**Comment by romainfrancois** [comment] 2020-11-20 08:50
Thanks for the update. I believe this belongs to the `sparlyr` issues. cc @javierluraschi 

I can't reproduce locally myself because of some Java configuration problem, so I can't really get to the real issue.

**Comment by yitao-li** [comment] 2020-11-30 19:01
I think this is definitely unrelated to `dplyr` and also is no longer an issue with recent versions of `sparklyr` . We can close this issue.

**Closed** 2020-12-01 14:09 UTC
Labels: reprex
