### ISSUE TITLE
Failure in Latin-1 locale

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#4329] opened 2019-04-11 15:07 UTC
From CRAN

---

1) The character in don't is an (ASCII) apostrophe, not a right quote: don’t.
(with a right quote) is used in packages CHNOSZ dplyr ptstem skimr 
styler text2vec textTinyR (and others not failing).

2) en and em dashes are not portable, found in packages
CHNOSZ SARP.moodle caret dplyr gestalt ptstem quanteda rchie rcrossref 
rdatacite rerddap rgbif rplos taxize textTinyR traitdataform units .

**Comment by romainfrancois** [comment] 2019-04-12 09:02
I don't know where to find these : 

```r
library(fs)
library(readr)
library(purrr)
library(tidyverse)

fs::dir_ls(all = TRUE, recursive = TRUE, regexp = "[.](cpp|h|R|r|Rmd|md)$") %>% 
  map_df(.id = "file", ~tibble(text = read_lines(.), line = seq_along(text))) %>% 
  filter(str_detect(text, "\u2013\u2014\u2019"))
```

**Comment by hadley** [comment] 2019-04-12 12:41
Don’t you need a | in you regex?

**Comment by romainfrancois** [comment] 2019-05-27 07:46
Still seems to be a problem https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-fedora-clang/dplyr-00check.html

But I can't reproduce this with released R

**Comment by romainfrancois** [comment] 2019-05-27 09:25
Can't reproduce the problem on travis :/ 
https://travis-ci.org/tidyverse/dplyr/builds/537671801

```
$ Rscript -e 'print(tools:::.check_package_ASCII_code("."))'
character(0)
```

Closing this now, will fix when cran tells us what the problem is exactly

**Closed by romainfrancois** 2019-05-27 09:25 UTC
