### ISSUE TITLE
Keep classes set on an object after filtering

### ISSUE THREAD

**Issue by torbjorn** [tidyverse/dplyr#3818] opened 2018-09-14 11:58 UTC
filtering something drops any existing classes and adds just data.frame it seems.

        library(dplyr)
        d <- cars
        class( d ) <- c( "cars", "data.frame" )
        print.cars <- function( x, ... ) { print.data.frame( head( d, n=2 ) ); cat("...\n") }
        d
        class( d )
        class( d %>% filter( speed < 10 ) )
        d %>% filter( speed < 10 )

would be nice if my object kept its classes after filtering

print(d) # produces:

        > d
          speed dist
        1     4    2
        2     4   10
        ...

print(d %>% filter( speed < 10 )) # produces:

        > d %>% filter( speed < 10 )
          speed dist
        1     4    2
        2     4   10
        3     7    4
        4     7   22
        5     8   16
        6     9   10

**Comment by hadley** [comment] 2018-09-14 13:17
Duplicate of #2432

**Closed by hadley** 2018-09-14 13:17 UTC
