### ISSUE TITLE
Feature request: matrix columns

### ISSUE THREAD

**Issue by jgellar** [tidyverse/dplyr#4198] opened 2019-02-19 15:55 UTC
Both data frames and tibbles support matrix columns.

```
d <- tibble(v1 = 1:3, v2 = c("a", "b", "c"))
d$mat <- matrix(rnorm(12), nrow = 3, ncol = 4)
str(d)
```

I find this data format very useful in a number of contexts that I work in, including Bayesian analysis and functional data, where we have a vector of responses per individual, and we might want to perform some matrix algebra. Currently, `dplyr` throws an error if I want to add a matrix using `mutate`:

```
d <- tibble(v1 = 1:3, v2 = c("a", "b", "c")) %>%
    mutate(mat = matrix(rnorm(12), nrow = 3, ncol = 4))
```

Could this ability be added, or is there an alternative that I am missing? The only way I can do this is with the first code, which is annoying because it breaks the pipeline.

**Comment by romainfrancois** [comment] 2019-02-20 08:52
duplicate of #3630

**Closed by romainfrancois** 2019-02-20 08:52 UTC
