### ISSUE TITLE
Join just broked with version 1.0.2

### ISSUE THREAD

**Issue by harshaloyo** [tidyverse/dplyr#5666] opened 2020-12-21 05:46 UTC
Hi ,
after the new update of 1.0.2 , joins in dplyr started showing these error ,which were not there in version 0.7.8 for the same successfully  running done 

Error: Join columns must be unique.
✖ Problem at position 2.
Backtrace:
    █
 1. ├─dplyr::left_join(...)
 2. └─dplyr:::left_join.data.frame(...)
 3.   └─dplyr:::join_mutate(...)
 4.     └─dplyr:::join_cols(...)
 5.       └─dplyr:::standardise_join_by(by, x_names = x_names, y_names = y_names)
 6.         └─dplyr:::check_join_vars(by$x, x_names)
Execution halted

**Comment by romainfrancois** [comment] 2021-01-04 13:19
Please add a [reprex](https://reprex.tidyverse.org) so that we can reproduce and help.

**Comment by romainfrancois** [comment] 2021-01-11 14:10
@harshaloyo can you please share an example of code that reproduces the problem ?

**Comment by romainfrancois** [comment] 2021-01-12 09:36
I've closed this issue due to lack of requested reprex. If you still care about this bug, please open a new issue with a reprex.

**Closed by romainfrancois** 2021-01-12 09:36 UTC
Labels: reprex
