### ISSUE TITLE
mutate() .keep_by = "used" discards grouping variable. Should it?

### ISSUE THREAD

**Issue by jzadra** [tidyverse/dplyr#5535] opened 2020-09-17 20:24 UTC
The experimental feature `.keep_by = "used"` in `mutate()` is awesome.  I just noticed that it discards grouping variables.  I'm wondering whether perhaps it should keep them even if they aren't used in the mutate?

```
diamonds %>% 
group_by(color) %>% 
mutate(xyz = x + y + z, .keep = "used") 
```

**Comment by hadley** [comment] 2020-11-16 18:02
Duplicate of #5582

**Closed by hadley** 2020-11-16 18:02 UTC
