### ISSUE TITLE
Feature request : 'suffix' option in summarise_all

### ISSUE THREAD

**Issue by hugueschips** [tidyverse/dplyr#2950] opened 2017-07-07 13:59 UTC
Hi !

Thanks for the amazing job about dplyr!
I'm using it to handle a SQLite database, where the use dplyr::rename is very slow because of the absence of ALTER table RENAME in SQLite. So to avoid the use of rename, I would like to add a chosen suffix when I summarise_all.
At the moment, the best way I found is to summarize each column separately and to left_join it to the table with already summarized columns.

Would it be reasonable to create such an option?

Kind regards,
     Hugues

**Comment by krlmlr** [comment] 2017-07-12 18:51
Thanks. Could you please provide a reproducible example?

**Comment by hugueschips** [comment] 2017-07-13 07:41
Hi,

Thanks for reading and replying.

Here's an example :
At the moment, it is possible to do 
```
df <- data.frame('a' = 1:10, 'b'=101:110)
df %>% summarise_all(mean)
```
but I would like my result to be like 
`df %>% summarise('a_my_suffix' = mean(a), 'b_my_suffix'=mean(b))`
via a function call like
`df %>% summarise_all(mean, suffix='_my_suffix')`
because I have an undetermined large amount of columns and not just two...

This would be perfect if it could work with remote SQLite tables.

Kind regards,
Hugues

**Comment by krlmlr** [comment] 2017-07-13 07:44
Thanks. Could you use a `rename_all()` call after the summary? I'm aware of issues here which might or might not hit you, but that looks like a cleaner approach to me.

**Comment by hugueschips** [comment] 2017-07-13 07:54
I tried, but it doesn't work on SQLite tables. I managed to do it with rename for each column, but as it copies the table each time, it is awfully slow. 
I finally implemented my own spread function, which is compatible with SQLite. Maybe it could be usefull for others:
```
## SQLite SPREAD ANS SPREAD_ALL FUNCTIONS
get_distinct_val_of_col <- function(dt, key) {
	key_col <- enquo(key)
	out <- dt %>% ungroup %>% select(!!key_col) %>% as.data.frame %>% distinct
	return(out[[1]])
}

spread <- function(dt, key, value, debug=F) {
	## just like tidyverse::spread but works remotely with SQL tables and adds suffixes
	key_col <- enquo(key)
	value_col <- enquo(value)
	col_string <- toString(value_col[2])
	key_distinct <- dt %>% get_distinct_val_of_col(!!key_col)
	if (debug) { key_distinct <- key_distinct[1:2] }
	out_frame <- dt %>% 
			select(-(!!key_col), -(!!value_col)) %>%
			distinct
	join_by <- out_frame %>% colnames
	for (key_val in key_distinct) {
		name <- paste(col_string, key_val, sep='_')
		temp <- dt %>% 
				filter((!!key_col) == key_val) %>%
				mutate(!!name := (!!value_col)) %>%
				select(-(!!key_col), -(!!value_col)) %>%
				distinct
		out_frame <- left_join(out_frame, temp, by=join_by) %>% compute
	}
	return(out_frame)
}

spread_all <- function(dt, key, debug=F) {
	## spreads key column with all other columns
	## except dt's group_vars
	key_col <- enquo(key)
	my_group_vars <- dt %>% group_vars
	group_vars_idx <- which(colnames(dt) %in% my_group_vars)
	key_col_idx <- which(colnames(dt)==toString(key_col[2]))
	exclude_col_idx <- c(group_vars_idx, key_col_idx)
	spread_columns <- colnames(dt)[-exclude_col_idx]
	out_frame <- dt %>% 
			select(!!my_group_vars) %>%
			distinct
	for (col in spread_columns) {
		colname <- as.name(col)
		temp_in <- dt %>% select(!!my_group_vars, !!key_col, !!colname)
		temp_out <- temp_in %>% spread(!!key_col, !!colname, debug=debug)
		out_frame <- left_join(out_frame, temp_out, by=my_group_vars) %>% compute
	}
	return(out_frame)
}
```
So if you put a column with to suffixes (which was pre-existing in my case) you can do it without extra copies in SQLite.

**Comment by krlmlr** [comment] 2017-07-13 08:02
What do you mean by "copies the table each time"? A `rename()` is translated to a `SELECT` with a subquery.

https://github.com/tidyverse/dplyr/issues/2943 looks like a related problem.

Actually, we're looking into a generic `spread()` implementation for SQL sources in tidyr: https://github.com/tidyverse/tidyr/issues/189.

**Comment by hugueschips** [comment] 2017-07-13 08:24
I read [this](http://www.sqlite.org/lang_altertable.html) and [that](https://blog.xojo.com/2013/12/04/renaming-columns-in-sqlite-tables/) and I understood the way SQLite renames a columns is :

1. add a column with the new name;
2. copy the column into the new one;
3. drop the old column.

As ALTER DROP is not supported by SQLite, what happens each time is described [here](https://stackoverflow.com/questions/8442147/how-to-delete-or-add-column-in-sqlite) : 

1. a new table is created;
2. columns you want to keep are copied into it.

So it copies the table each time, doesn't it? Whatever, renaming my SQLite tables with rename function cost about 15% of my computation time...

**Comment by krlmlr** [comment] 2017-07-13 08:25
dbplyr works with temporary tables and subqueries. I think this will be much faster if `rename_all()` works, could you please show me the error for your use case?

**Comment by hugueschips** [comment] 2017-07-13 08:39
dt being my SQLite remote table : 
`dt %>% rename_all(toupper) %>% as.data.frame %>% colnames`
gave me 

> Error in names(select)[match(old_vars, vars)] <- new_vars: NAs are not allowed in subscripted assignments
> Traceback:
> 
> 1. dt %>% rename_all(toupper) %>% as.data.frame %>% colnames
> 2. withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
> 3. eval(quote(`_fseq`(`_lhs`)), env, env)
> 4. eval(quote(`_fseq`(`_lhs`)), env, env)
> 5. `_fseq`(`_lhs`)
> 6. freduce(value, `_function_list`)
> 7. function_list[[i]](value)
> 8. as.data.frame(.)
> 9. as.data.frame.tbl_sql(.)
> 10. as.data.frame(collect(x, n = n))
> 11. collect(x, n = n)
> 12. collect.tbl_sql(x, n = n)
> 13. grouped_df(out, intersect(op_grps(x), names(out)))
> 14. intersect(op_grps(x), names(out))
> 15. op_grps(x)
> 16. op_grps.tbl_lazy(x)
> 17. op_grps(op$ops)
> 18. op_grps.op_rename(op$ops)
> 19. rename_vars(op_grps(op$x), !(!(!op$dots)), strict = FALSE)

**Comment by krlmlr** [comment] 2017-07-13 08:46
Thanks. This looks very much like #2943.

**Comment by krlmlr** [comment] 2017-07-13 08:48
This notwithstanding, a long data format (like you seem to be using in combination with `spread()`) may be the better choice in many cases anyway.

**Comment by hugueschips** [comment] 2017-07-13 08:53
By 'long data format', do you mean 'not aggregated data' ?

**Comment by krlmlr** [comment] 2017-07-13 09:00
I was referring to the format created by `gather()`, with a key and a value column. There, an operation over several columns becomes just a grouped operation over one column.

**Comment by hugueschips** [comment] 2017-07-13 09:08
Like `gather` colnames, add suffix with `mutate` and the `spread` it? Actually, this is what I did since I sent this feature request. So I would need `gather` and  `spread` to be compatible with SQLite and I am happy you're already on it :+1:  !

**Comment by krlmlr** [comment] 2017-07-13 09:11
Don't hold your breath for it, the `rename_all()` fix is likely to arrive sooner. Closing this, because a suffix can be added with existing tools (if they weren't broken).

**Closed by krlmlr** 2017-07-13 09:11 UTC
Labels: database, reprex
