### ISSUE TITLE
Error in as.list(x) : trying to get slot "matsin" from an object (class "quosures") that is not an S4 object

### ISSUE THREAD

**Issue by extabl** [tidyverse/dplyr#4524] opened 2019-08-07 15:31 UTC
I have been successfully using the below piece of code for quite a while, but for some reason now it got broken.
Although I haved loaded the very same packages as before. No changes to R or dplyr versions in the meantime.

It looks like that dplyr's top_n() function does not work with pipes anymore.

Does anyone have experience in resolving this error message please? Any help or hint is highly appreciated.

R: 3.6.1; dplyr: 0.8.3

```
df %>% group_by(ID) %>% top_n(1,MRP)
```

Traceback:
 
```
Error in as.list(x) : trying to get slot "matsin" from an object (class "quosures") that is not an S4 object
20.
as.list(x)
19.
splice(dot_call(capture_dots, frame_env = frame_env, named = named, ignore_empty = ignore_empty, unquote_names = unquote_names, homonyms = homonyms, check_assign = check_assign))
18.
FUN(X[[i]], ...)
17.
lapply(.x, .f, ...)
16.
map(syms, function(sym) { if (!is_symbol(sym)) { abort("Inputs to capture must be argument names") } ...
15.
endots(call = sys.call(), frame_env = parent.frame(), capture_arg = rlang_enquo, capture_dots = rlang_quos_interp, named = .named, ignore_empty = .ignore_empty, unquote_names = .unquote_names, homonyms = .homonyms, check_assign = .check_assign)
14.
enquos(...)
13.
quo_reduce(..., .op = op)
12.
all_exprs(!!!dots, .vectorised = TRUE)
11.
filter.tbl_df(x, top_n_rank({ { n } ...
10.
filter(x, top_n_rank({ { n } ...
9.
top_n(., 1, MRP)
8.
function_list[[k]](value)
7.
withVisible(function_list[[k]](value))
6.
freduce(value, `_function_list`)
5.
`_fseq`(`_lhs`)
4.
eval(quote(`_fseq`(`_lhs`)), env, env)
3.
eval(quote(`_fseq`(`_lhs`)), env, env)
2.
withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
1.
df %>% group_by(ID) %>% top_n(1,MRP)
```

**Comment by cderv** [comment] 2019-08-09 16:57
> It looks like that dplyr's top_n() function does not work with pipes anymore.

`top_n` seems to work fine. 

``` r
library(dplyr)
#> 
#> Attachement du package : 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
packageVersion("dplyr")
#> [1] '0.8.3'

starwars %>%
  group_by(homeworld) %>%
  top_n(1, height)
#> # A tibble: 49 x 13
#> # Groups:   homeworld [49]
#>    name  height  mass hair_color skin_color eye_color birth_year gender
#>    <chr>  <int> <dbl> <chr>      <chr>      <chr>          <dbl> <chr> 
#>  1 Dart~    202   136 none       white      yellow          41.9 male  
#>  2 Obi-~    182    77 auburn, w~ fair       blue-gray       57   male  
#>  3 Wilh~    180    NA auburn, g~ fair       blue            64   male  
#>  4 Han ~    180    80 brown      fair       brown           29   male  
#>  5 Gree~    173    74 <NA>       green      black           44   male  
#>  6 Jabb~    175  1358 <NA>       green-tan~ orange         600   herma~
#>  7 Jek ~    180   110 brown      fair       blue            NA   male  
#>  8 IG-88    200   140 none       metal      red             15   none  
#>  9 Bossk    190   113 none       green      red             53   male  
#> 10 Land~    177    79 black      dark       brown           31   male  
#> # ... with 39 more rows, and 5 more variables: homeworld <chr>,
#> #   species <chr>, films <list>, vehicles <list>, starships <list>
```

<sup>Created on 2019-08-09 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

Can you provide a [reprex](https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html) with some data so that it can be reproduced easily and isolate the issue ? Your error could come also in a change in the data type. What is `df` ?

Thank you.

**Comment by romainfrancois** [comment] 2019-11-27 14:49
Closing this now, please reopen with a [`reprex` ](https://reprex.tidyverse.org).

**Closed by romainfrancois** 2019-11-27 14:49 UTC
Labels: reprex

**Comment by eaurele** [comment] 2020-03-10 09:12
Package `ycinterextra` exports `as.list`, which breaks `select` among other things.
I do not understand why only now, since it has not been updated since 2013.

```r
library(ycinterextra)
library(dplyr)

mtcars %>% 
  select(1)
# Error in as.list(x) : 
#   trying to get slot "matsin" from an object (class "quosures") that is not an S4 object 

as.list <- base::as.list

mtcars %>% 
  select(1)
#                      mpg
# Mazda RX4           21.0
# Mazda RX4 Wag       21.0
# Datsun 710          22.8
# Hornet 4 Drive      21.4
# Hornet Sportabout   18.7
# ....
```

**Comment by batpigandme** [comment] 2020-03-10 12:13
It works fine now with the development version.
``` r
library(ycinterextra)
#> Loading required package: compiler
#> 
#> Attaching package: 'ycinterextra'
#> The following objects are masked from 'package:stats':
#> 
#>     deviance, fitted, residuals
#> The following object is masked from 'package:base':
#> 
#>     as.list
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

mtcars %>% 
  select(1)
#>                      mpg
#> Mazda RX4           21.0
#> Mazda RX4 Wag       21.0
#> Datsun 710          22.8
#> Hornet 4 Drive      21.4
#> Hornet Sportabout   18.7
#> Valiant             18.1
#> Duster 360          14.3
#> Merc 240D           24.4
#> Merc 230            22.8
#> Merc 280            19.2
#> Merc 280C           17.8
#> Merc 450SE          16.4
#> Merc 450SL          17.3
#> Merc 450SLC         15.2
#> Cadillac Fleetwood  10.4
#> Lincoln Continental 10.4
#> Chrysler Imperial   14.7
#> Fiat 128            32.4
#> Honda Civic         30.4
#> Toyota Corolla      33.9
#> Toyota Corona       21.5
#> Dodge Challenger    15.5
#> AMC Javelin         15.2
#> Camaro Z28          13.3
#> Pontiac Firebird    19.2
#> Fiat X1-9           27.3
#> Porsche 914-2       26.0
#> Lotus Europa        30.4
#> Ford Pantera L      15.8
#> Ferrari Dino        19.7
#> Maserati Bora       15.0
#> Volvo 142E          21.4
```

<sup>Created on 2020-03-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0.9001)</sup>
