### ISSUE TITLE
Stop using tibble::repair_names()

### ISSUE THREAD

**Issue by hadley** [tidyverse/dplyr#3786] opened 2018-08-29 20:27 UTC
Since it's soft deprecated, and likely to be harder deprecated in the future.

**Comment by jennybc** [comment] 2018-08-30 06:12
`as_tibble(..., validate = FALSE)` will also merit a look:

https://github.com/cran/dplyr/blob/fe5edb1b273e1c6f091f88bd64f627a0a2aee6f6/R/dataframe.R#L240

**Comment by romainfrancois** [comment] 2018-09-05 09:15
We only use it in `bind_cols` so it should not be too hard to abandon it: 

```
#' @export
#' @rdname bind
bind_cols <- function(...) {
  x <- flatten_bindable(dots_values(...))
  out <- cbind_all(x)
  tibble::repair_names(out)
}
```

But we need to decide what cbind_all should be doing with the names. Or should we splice and delegate this to `tibble()`, e.g. : 

``` r
library(dplyr)
library(rlang)

bind_cols_ <- function(...) tibble(!!!purrr::flatten(dots_values(...)))

bind_cols_(data.frame(x = 1), data.frame(y = 2))
#> # A tibble: 1 x 2
#>       x     y
#>   <dbl> <dbl>
#> 1     1     2
bind_cols_(data.frame(x = 1), data.frame(x = 2))
#> Error: Column `x` must have a unique name.
```

Created on 2018-09-05 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by romainfrancois** [comment] 2018-09-05 09:43
This essentially is a duplicate of #3772

**Closed by romainfrancois** 2018-09-05 09:43 UTC
