### ISSUE TITLE
across used with function that refers to a column

### ISSUE THREAD

**Issue by christophsax** [tidyverse/dplyr#5740] opened 2021-02-06 11:28 UTC
In dplyr \< 1.0.4, I could use an anonymous function or a purrr formula in `across()`, and refer to columns in the data frame. This still works for purrr formulas but not for functions. Is this intentional?

``` r
library(dplyr, warn.conflicts = FALSE)
packageVersion("dplyr")
#> [1] '1.0.4'
```

This used to work in dplyr \< 1.0.4, but errors now:

``` r
tibble(a = 1, b = 2) %>% 
  mutate(across(a, function(x) x / b))
#> Error: Problem with `mutate()` input `..1`.
#> ✖ object 'b' not found
#> ℹ Input `..1` is `(function (.cols = everything(), .fns = NULL, ..., .names = NULL) ...`.
```

It works as before with a purrr style formula

``` r
tibble(a = 1, b = 2) %>% 
  mutate(across(a, ~ .x / b))
#> # A tibble: 1 x 2
#>       a     b
#>   <dbl> <dbl>
#> 1   0.5     2
```

<sup>Created on 2021-02-06 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by CoryMcCartan** [comment] 2021-02-06 23:17
Duplicate of #5734 ?

**Comment by romainfrancois** [comment] 2021-02-11 12:38
Thanks, this is indeed a duplicate of #5734.

**Closed by romainfrancois** 2021-02-11 12:38 UTC
