### ISSUE TITLE
bind_rows produces error in R v4.x

### ISSUE THREAD

**Issue by andybeet** [tidyverse/dplyr#5779] opened 2021-02-22 18:36 UTC
Test data can be found in the [test.rds](https://github.com/NOAA-EDAB/neus-atlantis/blob/andy_testruns/testing/test.rds) file.
It contains a list of 10 data frames. Each data frame (272 x 5). I expect the result to have all data frames in the list to be bound to one large data frame

```
library(dplyr)
a <- readRDS(file="test.rds")
bind_rows(a)
```

Results in the error

```
Error: `vec_cast.Date.Date()` is implemented at C level.
This R function is purely indicative and should never be called.
Run `rlang::last_error()` to see where the error occurred.
```

which does not happen when using R v3.6.1

I can get around this by using 

```
do.call("rbind",a)
```
but i'd rather use `dplyr`

Is this a bug?

<details> <summary><strong>Session Info</strong></summary>

```r
- Session info -------------------------------------------------------------------------------
 setting  value                       
 version  R version 4.0.3 (2020-10-10)
 os       Windows 10 x64              
 system   x86_64, mingw32             
 ui       RStudio                     
 language (EN)                        
 collate  English_United States.1252  
 ctype    English_United States.1252  
 tz       America/New_York            
 date     2021-02-22      
```

**Comment by hadley** [comment] 2021-03-03 14:32
Can you please provide a minimal reprex (reproducible example)? The goal of a reprex is to make it as easy as possible for me to recreate your problem so that I can fix it: please [help me help you](https://nypdecider.files.wordpress.com/2014/08/help-me-help-you.gif)! 

If you've never heard of a reprex before, start by reading "[What is a reprex](http://reprex.tidyverse.org/articles/reprex.html)", and follow the advice further down the page. Please make sure your reprex is created with the reprex package as it gives nicely formatted output and avoids a number of common pitfalls.

**Comment by andybeet** [comment] 2021-03-03 15:23
@hadley Unfortunately i can not provide a reprex, which is why i included a link to the resulting list. Unfortunately, this `bind_rows` call is in the middle of a very large script and would be extremely difficult to distill this to a simple reprex. I have already replaced `bind_rows` with `do.call(`rbind`,a) in my code and that works so I understand if you need to close this issue without resolution. 

As an aside: It is strange that the linked to RDS will not bind though. I don't see anything unusual about this list.

**Comment by hadley** [comment] 2021-03-03 16:49
@andybeet you can provide a reprex _using_ that file.

**Comment by andybeet** [comment] 2021-03-03 17:44
ok. How's this?

``` r
githubURL <- ("https://raw.githubusercontent.com/NOAA-EDAB/neus-atlantis/andy_testruns/testing/test.rds")
download.file(githubURL,"test.rds")
a <- readRDS("test.rds")
dplyr::bind_rows(a)
#> Error: `vec_cast.Date.Date()` is implemented at C level.
#> This R function is purely indicative and should never be called.
```

<sup>Created on 2021-03-03 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by hadley** [comment] 2021-03-03 18:24
Thanks — that let me get it down to this minimal reprex:

``` r
x <- Sys.Date()
dim(x) <- 1
dplyr::bind_rows(data.frame(x), data.frame(x))
#> Error: `vec_cast.Date.Date()` is implemented at C level.
#> This R function is purely indicative and should never be called.
```

<sup>Created on 2021-03-03 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

Which I've filed at https://github.com/r-lib/vctrs/issues/1329.

But the begs the question: how did you manage to make these weird date arrays?

**Comment by romainfrancois** [comment] 2021-03-29 07:51
@andybeet can you let us know how `test.rds` is produced ?

**Comment by andybeet** [comment] 2021-03-29 19:05
Not sure what exactly you are asking. Maybe this:

1. The file is produced using `saveRDS`
2. The dates in this file have been converted from seconds. They were converted to POSIX (`as.POSIXct`) then to date (`as.Date`), like this:

```
as.Date(as.POSIXct(values, origin = '1964-01-01 00:00:00',tz = 'UTC'))
```
where `values` have typeof = double and class = array

Is this what you are asking?

**Comment by hadley** [comment] 2021-03-31 13:46
@andybeet that doesn't explain how they got a `dim` attribute; you're definitely doing something weird to the dates somewhere.

Closing this since we're now tracking in vctrs.

**Closed by hadley** 2021-03-31 13:46 UTC
Labels: vctrs ↗️

**Comment by andybeet** [comment] 2021-04-14 20:50
maybe `netcdf` is doing something weird to those dates. I am not doing anything of note
