### ISSUE TITLE
mutate calls strip custom attributes on dataframes

### ISSUE THREAD

**Issue by davidski** [tidyverse/dplyr#3679] opened 2018-06-18 17:13 UTC
A possible duplicate/extension of #3259, `mutate` calls strip out custom attributes on dataframes.

``` r
suppressPackageStartupMessages(library(dplyr))
dat <- mtcars
attr(dat, "hello") <- "world"
names(attributes(dat))
#> [1] "names"     "row.names" "class"     "hello"

dat <- mutate(dat, "foo" = "bar")
names(attributes(dat))
#> [1] "class"     "names"     "row.names"
```

Created on 2018-06-18 by the [reprex package](http://reprex.tidyverse.org) (v0.2.0).

**Comment by hadley** [comment] 2018-06-18 18:18
Duplicate of #3429

**Closed by hadley** 2018-06-18 18:18 UTC
