### ISSUE TITLE
Support cartesian cross-product grouping (like `group_by(.drop = FALSE)`, only better …)

### ISSUE THREAD

**Issue by huftis** [tidyverse/dplyr#4292] opened 2019-03-18 15:03 UTC
I find the current (`dplyr` 0.8.0) semantics of `group_by(.drop = FALSE)` both to be confusing and usually not at all helpful. So this is a feature request *inspired by* #341.

# The problem

When I'm grouping by variables, I usually want one of the following behaviours:

1. Create groups only for combinations *existing* in the data (the current default behaviour, i.e. `.drop = TRUE`).
2. Create groups for *all* possible combinations of the grouping variables, i.e. cartesian cross-products.

Case 2 is actually the most common case (in my work), but is currently not supported by `dplyr`.

# The solution

What is needed is a cartesian cross-product grouping function (`group_cp()`?), where (unlike for `group_by(.drop = FALSE)`) the *order* in which the variables are specified don't influence *which* groups are created (only their order in the output), and the groups are the cartesian cross-product of *all* values (for non-factors) or levels (for factors).

In other words, a behaviour similar to how the base R `table()` function works.

# An example

Here’s a simple (if perhaps not very realistic) example:

```r
library(tidyverse)
d = tribble(~country, ~year, ~score,
            "NZ",   1976,   c(20,20,30),
            "NZ",   1977,   c(20),
            "US",   1977,   c(10)) %>%
  mutate(country = factor(country, levels=c("NZ","US", "NO"))) %>%
  unnest()
d
#> # A tibble: 5 x 3
#>   country  year score
#>   <fct>   <dbl> <dbl>
#> 1 NZ       1976    20
#> 2 NZ       1976    20
#> 3 NZ       1976    30
#> 4 NZ       1977    20
#> 5 US       1977    10
```

I want to see the number of responses for each combination of country (factor, 3 levels), year (integer, 2 values) and score (integer, 3 values), even non-existing combinations.

(In practice, I would probaby have score be a factor too, to capture all posible scores.)

The `table()` function in base R can easily handle this, creating all 3 * 2 * 3 = 18 rows:

```r
as.data.frame(with(d, table(country, year, score))) # 18 rows
```

But `group_by()` can’t do it (by itself):

```r
d %>% count(country, year, score)              # 4 rows
d %>% count(country, year, score, .drop=FALSE) # 5 rows
d %>% count(country, score, year, .drop=FALSE) # 5 rows
d %>% count(year, country, score, .drop=FALSE) # 7 rows
d %>% count(year, score, country, .drop=FALSE) # 12 rows
d %>% count(score, year, country, .drop=FALSE) # 12 rows
d %>% count(score, country, year, .drop=FALSE) # 10 rows
d %>% count(year, score, country, .drop=FALSE) # 12 rows
```

# A more realistic example

For a more realistic example, we wouldn't group on score, but perhaps on gender (cf. https://kieranhealy.org/blog/archives/2018/11/19/zero-counts-in-dplyr/), and use a more complicated summary function than `count()`. Example:

```r
d2 = d %>% 
  mutate(gender = factor(c(1,2,2,1,2),
                         levels=1:2,
                         labels=c("male", "female")))
d2
#> # A tibble: 5 x 4
#>   country  year score gender
#>   <fct>   <dbl> <dbl> <fct> 
#> 1 NZ       1976    20 male  
#> 2 NZ       1976    20 female
#> 3 NZ       1976    30 female
#> 4 NZ       1977    20 male  
#> 5 US       1977    10 female
```

We want to calculate the average score for each combination of country, gender and year. If we don’t have any responses for a certain gender in a certain year (US male 1977), we still want a row in the output, so the output should have `3 * 2 * 2 = 12` rows (but many of them with a `NaN` average score).

The default (`drop = TRUE)`) is missing data for all non-existing combinations, only returning 4 rows:
```r
d2 %>% 
  group_by(country, gender, year) %>% 
  summarise(mean_score = mean(score))
#> # A tibble: 4 x 4
#> # Groups:   country, gender [3]
#>   country gender  year mean_score
#>   <fct>   <fct>  <dbl>      <dbl>
#> 1 NZ      male    1976         20
#> 2 NZ      male    1977         20
#> 3 NZ      female  1976         25
#> 4 US      female  1977         10
```

And `drop = FALSE` has missing data for non-existing combinations *and* has data
for non-existing and non-valid values (e.g., for `year` equal to `NA`):

```r
d2 %>% 
  group_by(country, gender, year, .drop = FALSE) %>% 
  summarise(mean_score = mean(score))
#> # A tibble: 7 x 4
#> # Groups:   country, gender [6]
#>   country gender  year mean_score
#>   <fct>   <fct>  <dbl>      <dbl>
#> 1 NZ      male    1976         20
#> 2 NZ      male    1977         20
#> 3 NZ      female  1976         25
#> 4 US      male      NA        NaN
#> 5 US      female  1977         10
#> 6 NO      male      NA        NaN
#> 7 NO      female    NA        NaN
```

My expected/needed output (by `group_cp()`) would basically be this (where I have manipulated the order of the variables to get the required number of rows):
```r
d2 %>% 
  group_by(year, gender, country, .drop = FALSE) %>% 
  summarise(mean_score = mean(score)) %>% 
  arrange(country, gender, year) %>% 
  select(country, gender, year, mean_score)
#> # A tibble: 12 x 4
#> # Groups:   year, gender [4]
#>    country gender  year mean_score
#>    <fct>   <fct>  <dbl>      <dbl>
#>  1 NZ      male    1976         20
#>  2 NZ      male    1977         20
#>  3 NZ      female  1976         25
#>  4 NZ      female  1977        NaN
#>  5 US      male    1976        NaN
#>  6 US      male    1977        NaN
#>  7 US      female  1976        NaN
#>  8 US      female  1977         10
#>  9 NO      male    1976        NaN
#> 10 NO      male    1977        NaN
#> 11 NO      female  1976        NaN
#> 12 NO      female  1977        NaN
```

# Final comments

Yes, I know it's possible get this output by using `.drop = TRUE` add adding the missing groups manually afterwards, e.g. by using `complete()`. But this is much work, especially for such a common task, error-prone (it’s easy to overlook a grouping variable or an output variable), and not very flexible (sometimes the summary function can depend on the groups).

So having a grouping function for the cartesian cross-product would be **extremely** useful.

(It might even have its own `.drop` argument (defaulting to `FALSE`), for dropping non-used levels, e.g. `country == "NO"` in this example.)

**Comment by elong0527** [comment] 2019-08-06 05:12
The behavior of `.drop` is different when the `group_by` variable is numeric or factor.

A quick search drives me to this related issue. It would be nice if the behavior is consistent. 

```
> tmp <- tibble(x = 1:3, y = factor(c(2:1,2)) )
> count(tmp, x, y, .drop = FALSE)
# A tibble: 6 x 3
      x y         n
  <int> <fct> <int>
1     1 1         0
2     1 2         1
3     2 1         1
4     2 2         0
5     3 1         0
6     3 2         1
> tmp <- tibble(x = 1:3, y = c(2:1,2) )
> count(tmp, x, y, .drop = FALSE)
# A tibble: 3 x 3
      x     y     n
  <int> <dbl> <int>
1     1     2     1
2     2     1     1
3     3     2     1
```

**Comment by hadley** [comment] 2020-01-06 19:57
Duplicate of #4392

**Closed by hadley** 2020-01-06 19:57 UTC
Labels: feature, grouping :family_man_woman_girl_boy:
