### ISSUE TITLE
R 3.2 ERROR: lazy loading failed for package ‘dplyr’

### ISSUE THREAD

**Issue by igordot** [tidyverse/dplyr#5532] opened 2020-09-17 02:43 UTC
I was testing a package with Travis CI. With R 3.2, I get an error when it gets to dplyr while installing dependencies.

```
* installing *source* package ‘dplyr’ ...
** package ‘dplyr’ successfully unpacked and MD5 sums checked
** libs
g++ -I/opt/R/3.2.5/lib/R/include -DNDEBUG  -I/usr/local/include    -fpic  -g -O2  -c filter.cpp -o filter.o
g++ -I/opt/R/3.2.5/lib/R/include -DNDEBUG  -I/usr/local/include    -fpic  -g -O2  -c funs.cpp -o funs.o
g++ -I/opt/R/3.2.5/lib/R/include -DNDEBUG  -I/usr/local/include    -fpic  -g -O2  -c group_by.cpp -o group_by.o
g++ -I/opt/R/3.2.5/lib/R/include -DNDEBUG  -I/usr/local/include    -fpic  -g -O2  -c group_data.cpp -o group_data.o
g++ -I/opt/R/3.2.5/lib/R/include -DNDEBUG  -I/usr/local/include    -fpic  -g -O2  -c imports.cpp -o imports.o
g++ -I/opt/R/3.2.5/lib/R/include -DNDEBUG  -I/usr/local/include    -fpic  -g -O2  -c init.cpp -o init.o
g++ -I/opt/R/3.2.5/lib/R/include -DNDEBUG  -I/usr/local/include    -fpic  -g -O2  -c mutate.cpp -o mutate.o
g++ -I/opt/R/3.2.5/lib/R/include -DNDEBUG  -I/usr/local/include    -fpic  -g -O2  -c slice.cpp -o slice.o
g++ -I/opt/R/3.2.5/lib/R/include -DNDEBUG  -I/usr/local/include    -fpic  -g -O2  -c summarise.cpp -o summarise.o
g++ -shared -L/opt/R/3.2.5/lib/R/lib -L/usr/local/lib -o dplyr.so filter.o funs.o group_by.o group_data.o imports.o init.o mutate.o slice.o summarise.o -L/opt/R/3.2.5/lib/R/lib -lR
installing to /home/travis/R/Library/dplyr/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘data_frame’
ERROR: lazy loading failed for package ‘dplyr’
* removing ‘/home/travis/R/Library/dplyr’
Error in i.p(...) : 
  (converted from warning) installation of package ‘dplyr’ had non-zero exit status
Calls: <Anonymous> ... with_rprofile_user -> with_envvar -> force -> force -> i.p
Execution halted
The command "Rscript -e 'deps <- remotes::dev_package_deps(dependencies = NA);remotes::install_deps(dependencies = TRUE);if (!all(deps$package %in% installed.packages())) { message("missing: ", paste(setdiff(deps$package, installed.packages()), collapse=", ")); q(status = 1, save = "no")}'" failed and exited with 1 during .
```

Is this a Travis issue or does dplyr no longer work with R 3.2?

**Comment by romainfrancois** [comment] 2020-09-17 07:38
It is supposed to still work on 3.2, I'm not sure what the problem is here, we don't use a `data_frame` package, I don't know why check thinks so.

**Comment by igordot** [comment] 2020-09-17 16:07
I don't think there is a `data_frame` package, which makes this even more difficult to interpret. There was a recent problem with the `data_frame` function in `vctrs` and `tibble` (https://github.com/tidyverse/dplyr/pull/5463/commits/90d6676ab29b92cbc6c0f01e5789b1a669cfdb57). I saw a [similar error mentioned on StackOverflow](https://stackoverflow.com/questions/63569482/updating-dplyr-in-r-gives-no-package-called-data-frame-error) which was resolved by upgrading R from 3.2. Both of those were in the last few weeks, so it may be a recent issue.

**Comment by igordot** [comment] 2020-09-18 17:16
Just wanted to leave a quick update. I ran into a similar problem using R 3.2.5 on RStudio Cloud:

```
installing to /home/rstudio-user/R/x86_64-pc-linux-gnu-library/3.2/dplyr/libs
** R
** data
*** moving datasets to lazyload DB
** inst
** preparing package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘data_frame’
ERROR: lazy loading failed for package ‘dplyr’
* removing ‘/home/rstudio-user/R/x86_64-pc-linux-gnu-library/3.2/dplyr’
Warning in install.packages :
  installation of package ‘dplyr’ had non-zero exit status
```

**Comment by DavisVaughan** [comment] 2020-09-18 23:47
It looks like the `import(except=)` namespace directive was added in R 3.3 

https://github.com/tidyverse/dplyr/blob/e0f014af4bf546e644e03695db54e28812075d63/NAMESPACE#L462

Search for “The import()” at:
https://cran.r-project.org/doc/manuals/NEWS.3

**Comment by hadley** [comment] 2020-11-16 20:22
We only support the last four versions of R (3.6, 3.5, 3.4, 3.3) so we probably won't fix this.

**Closed by hadley** 2020-11-16 20:22 UTC

**Comment by igordot** [comment] 2020-11-16 20:24
Thanks for the clarification. According to `DESCRIPTION`, 3.2 should still be supported. Should `DESCRIPTION` be updated to reflect that?
