### ISSUE TITLE
dplyr::select interferes with MASS::select

### ISSUE THREAD

**Issue by helix123** [tidyverse/dplyr#3759] opened 2018-08-20 17:07 UTC
The generic for dplyr's `select` is defined rather unfortunate as it prevents dispatching on other `select.*` methods, like the one from package `MASS` (a package currently in the standard distribution of R...).

Anything you can do about that?

(Maybe related to #3657.)

```r
library(MASS)
library(dplyr)
data("longley")
names(longley)[1] <- "y"
mod <- lm.ridge(y ~ ., longley)
select(mod)
## Error in UseMethod("select_") : 
##  no applicable method for 'select_' applied to an object of class "ridgelm"
```

**Comment by cderv** [comment] 2018-08-20 17:37
This is a well known issue. 

You can find a proposed solution by RStudio with the {conflicted} 📦 
See blog post : https://www.tidyverse.org/articles/2018/06/conflicted/
Basically, you should use `MASS::select(mod)` or define `select <- MASS::select` if you want to switch.

**Comment by helix123** [comment] 2018-08-20 17:54
Thanks, I know how to circumvent it. I was not aware of the `conflicted` package - looks nice indeed.

However, I fell like this case is somewhat more severe: It would work for both packages due to method dispatching if it wasn't for dyplr "highjacking" `select` by the generic provided by adding an underscore to `select` in the generic...

**Comment by cderv** [comment] 2018-08-20 17:59
This issue is also a duplicate of #841 that has been closed. You can see the answer there.
Based on this, and the blog post I linked before, I don't think there will be another solution.

**Comment by batpigandme** [comment] 2018-08-20 20:22
Hi @helix123,

This has already been discussed and addressed: https://github.com/tidyverse/dplyr/issues/841 (as @cderv mentioned), so I'm going to close.

**Closed by batpigandme** 2018-08-20 20:22 UTC

**Comment by helix123** [comment] 2018-08-20 20:47
As I read in `?select_`

> Thus, the underscored versions are now superfluous.

I hoped there would be some solution for co-existance of the various `select.*` methods (where * does not start with an underscore).

**Comment by moodymudskipper** [comment] 2018-08-27 13:36
What about `select.ridgelm <- MASS::select` ?

**Comment by hadley** [comment] 2018-08-29 19:47
@helix123 we have had this discussion before, and I don't think it's useful to rehash it again here, so I'm going to lock this issue.
