### ISSUE TITLE
bind_rows: does not preserve zoo yearmon and yearqtr class

### ISSUE THREAD

**Issue by mdancho84** [tidyverse/dplyr#2921] opened 2017-06-27 14:32 UTC
When doing grouped or binding operations in `dplyr`, the `zoo::yearmon` and `yearqtr` classes are not preserved. The error that occurs specifies that:

"Warning in bind_rows_(x, .id): Vectorizing 'yearmon' elements may not preserve their attributes"

``` r
library(dplyr)
library(zoo)

# Setup 
dates <- seq.Date(from = as.Date("2017-01-01"), to = as.Date("2017-06-01"), by = "month") %>%
    as.yearmon()

tib_1 <- tibble(dates, symbol = rep("ABC", 6), value = 1:6)
tib_1
#> # A tibble: 6 x 3
#>           dates symbol value
#>   <S3: yearmon>  <chr> <int>
#> 1      Jan 2017    ABC     1
#> 2      Feb 2017    ABC     2
#> 3      Mar 2017    ABC     3
#> 4      Apr 2017    ABC     4
#> 5      May 2017    ABC     5
#> 6      Jun 2017    ABC     6

tib_2 <- tibble(dates, symbol = rep("XYZ", 6), value = 6:1)
tib_2
#> # A tibble: 6 x 3
#>           dates symbol value
#>   <S3: yearmon>  <chr> <int>
#> 1      Jan 2017    XYZ     6
#> 2      Feb 2017    XYZ     5
#> 3      Mar 2017    XYZ     4
#> 4      Apr 2017    XYZ     3
#> 5      May 2017    XYZ     2
#> 6      Jun 2017    XYZ     1

# bind_rows() converts the yearmon class to numeric
bind_rows(tib_1, tib_2)
#> Warning in bind_rows_(x, .id): Vectorizing 'yearmon' elements may not
#> preserve their attributes

#> Warning in bind_rows_(x, .id): Vectorizing 'yearmon' elements may not
#> preserve their attributes
#> # A tibble: 12 x 3
#>       dates symbol value
#>       <dbl>  <chr> <int>
#>  1 2017.000    ABC     1
#>  2 2017.083    ABC     2
#>  3 2017.167    ABC     3
#>  4 2017.250    ABC     4
#>  5 2017.333    ABC     5
#>  6 2017.417    ABC     6
#>  7 2017.000    XYZ     6
#>  8 2017.083    XYZ     5
#>  9 2017.167    XYZ     4
#> 10 2017.250    XYZ     3
#> 11 2017.333    XYZ     2
#> 12 2017.417    XYZ     1

# what should happen
rbind(tib_1, tib_2)
#> # A tibble: 12 x 3
#>            dates symbol value
#>    <S3: yearmon>  <chr> <int>
#>  1      Jan 2017    ABC     1
#>  2      Feb 2017    ABC     2
#>  3      Mar 2017    ABC     3
#>  4      Apr 2017    ABC     4
#>  5      May 2017    ABC     5
#>  6      Jun 2017    ABC     6
#>  7      Jan 2017    XYZ     6
#>  8      Feb 2017    XYZ     5
#>  9      Mar 2017    XYZ     4
#> 10      Apr 2017    XYZ     3
#> 11      May 2017    XYZ     2
#> 12      Jun 2017    XYZ     1
```

**Comment by mdancho84** [comment] 2017-06-29 19:13
Please note that this effects the `tidyquant` users, which will need to be able to use `yearmon` and `yearqtr`. Support for these classes was just added to the development version, which can be installed with `devtools`.

``` r
devtools::install_github("business-science/tidyquant")
library(tidyquant)
FANG %>%
    group_by(symbol) %>%
    tq_transmute(adjusted, periodReturn, period = "monthly") %>%
    mutate(date = as.yearmon(date))
#> Warning in mutate_impl(.data, dots): Vectorizing 'yearmon' elements may not
#> preserve their attributes

#> Warning in mutate_impl(.data, dots): Vectorizing 'yearmon' elements may not
#> preserve their attributes

#> Warning in mutate_impl(.data, dots): Vectorizing 'yearmon' elements may not
#> preserve their attributes

#> Warning in mutate_impl(.data, dots): Vectorizing 'yearmon' elements may not
#> preserve their attributes
#> # A tibble: 192 x 3
#> # Groups:   symbol [4]
#>    symbol     date monthly.returns
#>     <chr>    <dbl>           <dbl>
#>  1     FB 2013.000    0.1064285714
#>  2     FB 2013.083   -0.1204002582
#>  3     FB 2013.167   -0.0612844037
#>  4     FB 2013.250    0.0856137608
#>  5     FB 2013.333   -0.1231544833
#>  6     FB 2013.417    0.0217658727
#>  7     FB 2013.500    0.4790996977
#>  8     FB 2013.583    0.1220109272
#>  9     FB 2013.667    0.2165172871
#> 10     FB 2013.750   -0.0003981883
#> # ... with 182 more rows
```

**Comment by hadley** [comment] 2017-07-19 09:59
Duplicate of #2457

**Closed by hadley** 2017-07-19 09:59 UTC

**Comment by dk2745** [comment] 2017-09-15 21:25
This issue is not fixed in the recent release. Not sure if some other dependency is creating this error for me.
