### ISSUE TITLE
mutate() discards user-defined attributes

### ISSUE THREAD

**Issue by choisy** [tidyverse/dplyr#3884] opened 2018-10-08 11:15 UTC
The functions `filter()` and `mutate()` behave differently in what regards user-defined attributes.
Below is an example. Let's start by adding an attribute to a data frame:
```r
attr(mtcars, "my_attribute_name") <- "my_attribute_value"
```
We can see the attributes of this data frame:
```r
attributes(mtcars)
```
The function `filter()` behaves as expected in the sense that it does not affect the attributes of the data frame (apart from `row.names` of course):
```r
mtcars %>%
  filter(mpg > 20) %>%
  attributes()
```
On the other hand, the function `mutate()` does affect the attributes of the data. Specifically, the above user-defined attribute is discarded (the other ones are unaffected):
```r
mtcars %>%
  mutate(a_new_variable = 3) %>%
  attributes()
```
I think that it would be nicer if `mutate()` preserved the user-defined attributes as `filter()` does.

**Comment by hadley** [comment] 2018-10-08 12:36
Duplicate of #3429

**Closed by hadley** 2018-10-08 12:36 UTC
