### ISSUE TITLE
dplyr's bind_rows() not working when data frame has certain attribute names?

### ISSUE THREAD

**Issue by strengejacke** [tidyverse/dplyr#5042] opened 2020-03-25 11:06 UTC
I can't provide too many details here because I can't install dplyr (see https://github.com/tidyverse/dplyr/issues/5041), but someone else checked this reprex, which fails with the current dplyr-master from GitHub.

I _think_ that this issue is related to `bind_rows()` when a certain attribute is present in the data frames, because this issue _seems_ to work with the latest tibble-master from GitHub, and it works when we use `purrr::map_dfr(x, as.data.frame)`, and it works with the current dplyr version from CRAN.

``` r
library(tidyverse)
x <- iris %>%
  split(., .$Species) %>%
  map(., ~broom::tidy(stats::lm(formula = Sepal.Length ~ Sepal.Width, data = .x)))

x <- lapply(x, function(i) {
  attr(i, "n") <- "test"
  i
})

purrr::map_dfr(x, tibble::as_tibble)
#> Error in (function (x = list(), n = NULL, ..., class = NULL) : formal argument "n" matched by multiple actual arguments
```

<sup>Created on 2020-03-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                                             
#>  version  R Under development (unstable) (2020-02-28 r77874)
#>  os       Windows 10 x64                                    
#>  system   x86_64, mingw32                                   
#>  ui       RTerm                                             
#>  language (EN)                                              
#>  collate  English_United States.1252                        
#>  ctype    English_United States.1252                        
#>  tz       Europe/Berlin                                     
#>  date     2020-03-25                                        
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version      date       lib source                           
#>  assertthat    0.2.1        2019-03-21 [1] CRAN (R 4.0.0)                   
#>  backports     1.1.5        2019-10-02 [1] CRAN (R 4.0.0)                   
#>  broom         0.5.3.9000   2020-03-01 [1] Github (tidymodels/broom@3c922d5)
#>  callr         3.4.2        2020-02-12 [1] CRAN (R 4.0.0)                   
#>  cellranger    1.1.0        2016-07-27 [1] CRAN (R 4.0.0)                   
#>  cli           2.0.2        2020-02-28 [1] CRAN (R 4.0.0)                   
#>  colorspace    1.4-1        2019-03-18 [1] CRAN (R 4.0.0)                   
#>  crayon        1.3.4        2017-09-16 [1] CRAN (R 4.0.0)                   
#>  DBI           1.1.0        2019-12-15 [1] CRAN (R 4.0.0)                   
#>  dbplyr        1.4.2        2019-06-17 [1] CRAN (R 4.0.0)                   
#>  desc          1.2.0        2018-05-01 [1] CRAN (R 4.0.0)                   
#>  devtools      2.2.2        2020-02-17 [1] CRAN (R 4.0.0)                   
#>  digest        0.6.25       2020-02-23 [1] CRAN (R 4.0.0)                   
#>  dplyr       * 0.8.99.9002  2020-03-23 [1] Github (tidyverse/dplyr@35d3ace) 
#>  ellipsis      0.3.0        2019-09-20 [1] CRAN (R 4.0.0)                   
#>  evaluate      0.14         2019-05-28 [1] CRAN (R 4.0.0)                   
#>  fansi         0.4.1        2020-01-08 [1] CRAN (R 4.0.0)                   
#>  forcats     * 0.5.0        2020-03-01 [1] CRAN (R 4.0.0)                   
#>  fs            1.3.2        2020-03-05 [1] CRAN (R 4.0.0)                   
#>  generics      0.0.2        2018-11-29 [1] CRAN (R 4.0.0)                   
#>  ggplot2     * 3.3.0        2020-03-05 [1] CRAN (R 4.0.0)                   
#>  glue          1.3.2        2020-03-12 [1] CRAN (R 4.0.0)                   
#>  gtable        0.3.0        2019-03-25 [1] CRAN (R 4.0.0)                   
#>  haven         2.2.0        2019-11-08 [1] CRAN (R 4.0.0)                   
#>  highr         0.8          2019-03-20 [1] CRAN (R 4.0.0)                   
#>  hms           0.5.3        2020-01-08 [1] CRAN (R 4.0.0)                   
#>  htmltools     0.4.0        2019-10-04 [1] CRAN (R 4.0.0)                   
#>  httr          1.4.1        2019-08-05 [1] CRAN (R 4.0.0)                   
#>  jsonlite      1.6.1        2020-02-02 [1] CRAN (R 4.0.0)                   
#>  knitr         1.28         2020-02-06 [1] CRAN (R 4.0.0)                   
#>  lifecycle     0.2.0.9000   2020-03-16 [1] Github (r-lib/lifecycle@355dcba) 
#>  lubridate     1.7.4        2018-04-11 [1] CRAN (R 4.0.0)                   
#>  magrittr      1.5          2014-11-22 [1] CRAN (R 4.0.0)                   
#>  memoise       1.1.0        2017-04-21 [1] CRAN (R 4.0.0)                   
#>  modelr        0.1.6        2020-02-22 [1] CRAN (R 4.0.0)                   
#>  munsell       0.5.0        2018-06-12 [1] CRAN (R 4.0.0)                   
#>  pillar        1.4.3        2019-12-20 [1] CRAN (R 4.0.0)                   
#>  pkgbuild      1.0.6        2019-10-09 [1] CRAN (R 4.0.0)                   
#>  pkgconfig     2.0.3        2019-09-22 [1] CRAN (R 4.0.0)                   
#>  pkgload       1.0.2        2018-10-29 [1] CRAN (R 4.0.0)                   
#>  prettyunits   1.1.1        2020-01-24 [1] CRAN (R 4.0.0)                   
#>  processx      3.4.2        2020-02-09 [1] CRAN (R 4.0.0)                   
#>  ps            1.3.2        2020-02-13 [1] CRAN (R 4.0.0)                   
#>  purrr       * 0.3.3        2019-10-18 [1] CRAN (R 4.0.0)                   
#>  R6            2.4.1        2019-11-12 [1] CRAN (R 4.0.0)                   
#>  Rcpp          1.0.4        2020-03-17 [1] CRAN (R 4.0.0)                   
#>  readr       * 1.3.1        2018-12-21 [1] CRAN (R 4.0.0)                   
#>  readxl        1.3.1        2019-03-13 [1] CRAN (R 4.0.0)                   
#>  remotes       2.1.1        2020-02-15 [1] CRAN (R 4.0.0)                   
#>  reprex        0.3.0        2019-05-16 [1] CRAN (R 4.0.0)                   
#>  rlang         0.4.5.9000   2020-03-23 [1] Github (r-lib/rlang@a90b04b)     
#>  rmarkdown     2.1          2020-01-20 [1] CRAN (R 4.0.0)                   
#>  rprojroot     1.3-2        2018-01-03 [1] CRAN (R 4.0.0)                   
#>  rvest         0.3.5        2019-11-08 [1] CRAN (R 4.0.0)                   
#>  scales        1.1.0        2019-11-18 [1] CRAN (R 4.0.0)                   
#>  sessioninfo   1.1.1        2018-11-05 [1] CRAN (R 4.0.0)                   
#>  stringi       1.4.6        2020-02-17 [1] CRAN (R 4.0.0)                   
#>  stringr     * 1.4.0        2019-02-10 [1] CRAN (R 4.0.0)                   
#>  testthat      2.3.2        2020-03-02 [1] CRAN (R 4.0.0)                   
#>  tibble      * 2.99.99.9014 2020-03-25 [1] Github (tidyverse/tibble@01d7686)
#>  tidyr       * 1.0.2        2020-01-24 [1] CRAN (R 4.0.0)                   
#>  tidyselect    1.0.0        2020-01-27 [1] CRAN (R 4.0.0)                   
#>  tidyverse   * 1.3.0        2019-11-21 [1] CRAN (R 4.0.0)                   
#>  usethis       1.5.1.9000   2020-03-24 [1] Github (r-lib/usethis@01dbd8f)   
#>  vctrs         0.2.99.9010  2020-03-23 [1] Github (r-lib/vctrs@3675fdf)     
#>  withr         2.1.2        2018-03-15 [1] CRAN (R 4.0.0)                   
#>  xfun          0.12         2020-01-13 [1] CRAN (R 4.0.0)                   
#>  xml2          1.2.5        2020-03-11 [1] CRAN (R 4.0.0)                   
#>  yaml          2.2.1        2020-02-01 [1] CRAN (R 4.0.0)                   
#> 
#> [1] C:/Users/inp099/Documents/R/win-library/4.0
#> [2] C:/Program Files/R/R-devel/library
```

</details>

**Comment by strengejacke** [comment] 2020-03-25 11:12
Working with current dplyr from CRAN:

``` r
library(tidyverse)
x <- iris %>%
  split(., .$Species) %>%
  map(., ~broom::tidy(stats::lm(formula = Sepal.Length ~ Sepal.Width, data = .x)))

x <- lapply(x, function(i) {
  attr(i, "n") <- "test"
  i
})

purrr::map_dfr(x, tibble::as_tibble)
#> # A tibble: 6 x 5
#>   term        estimate std.error statistic  p.value
#>   <chr>          <dbl>     <dbl>     <dbl>    <dbl>
#> 1 (Intercept)    2.64     0.310       8.51 3.74e-11
#> 2 Sepal.Width    0.690    0.0899      7.68 6.71e-10
#> 3 (Intercept)    3.54     0.563       6.29 9.07e- 8
#> 4 Sepal.Width    0.865    0.202       4.28 8.77e- 5
#> 5 (Intercept)    3.91     0.757       5.16 4.66e- 6
#> 6 Sepal.Width    0.902    0.253       3.56 8.43e- 4
```

<details>

<summary>Session info</summary>

```r
devtools::session_info()
#> - Session info ---------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.6.3 (2020-02-29)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  German_Germany.1252         
#>  ctype    German_Germany.1252         
#>  tz       Europe/Berlin               
#>  date     2020-03-25                  
#> 
#> - Packages -------------------------------------------------------------------
#>  package     * version date       lib source        
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.6.1)
#>  backports     1.1.5   2019-10-02 [1] CRAN (R 3.6.1)
#>  broom         0.5.5   2020-02-29 [1] CRAN (R 3.6.2)
#>  callr         3.4.2   2020-02-12 [1] CRAN (R 3.6.2)
#>  cellranger    1.1.0   2016-07-27 [1] CRAN (R 3.6.1)
#>  cli           2.0.2   2020-02-28 [1] CRAN (R 3.6.2)
#>  colorspace    1.4-1   2019-03-18 [1] CRAN (R 3.6.1)
#>  crayon        1.3.4   2017-09-16 [1] CRAN (R 3.6.1)
#>  DBI           1.1.0   2019-12-15 [1] CRAN (R 3.6.2)
#>  dbplyr        1.4.2   2019-06-17 [1] CRAN (R 3.6.1)
#>  desc          1.2.0   2018-05-01 [1] CRAN (R 3.6.1)
#>  devtools      2.2.2   2020-02-17 [1] CRAN (R 3.6.2)
#>  digest        0.6.25  2020-02-23 [1] CRAN (R 3.6.2)
#>  dplyr       * 0.8.5   2020-03-07 [1] CRAN (R 3.6.3)
#>  ellipsis      0.3.0   2019-09-20 [1] CRAN (R 3.6.1)
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 3.6.1)
#>  fansi         0.4.1   2020-01-08 [1] CRAN (R 3.6.2)
#>  forcats     * 0.5.0   2020-03-01 [1] CRAN (R 3.6.3)
#>  fs            1.3.2   2020-03-05 [1] CRAN (R 3.6.3)
#>  generics      0.0.2   2018-11-29 [1] CRAN (R 3.6.1)
#>  ggplot2     * 3.3.0   2020-03-05 [1] CRAN (R 3.6.3)
#>  glue          1.3.2   2020-03-12 [1] CRAN (R 3.6.3)
#>  gtable        0.3.0   2019-03-25 [1] CRAN (R 3.6.3)
#>  haven         2.2.0   2019-11-08 [1] CRAN (R 3.6.1)
#>  highr         0.8     2019-03-20 [1] CRAN (R 3.6.1)
#>  hms           0.5.3   2020-01-08 [1] CRAN (R 3.6.2)
#>  htmltools     0.4.0   2019-10-04 [1] CRAN (R 3.6.1)
#>  httr          1.4.1   2019-08-05 [1] CRAN (R 3.6.1)
#>  jsonlite      1.6.1   2020-02-02 [1] CRAN (R 3.6.2)
#>  knitr         1.28    2020-02-06 [1] CRAN (R 3.6.2)
#>  lattice       0.20-40 2020-02-19 [1] CRAN (R 3.6.3)
#>  lifecycle     0.2.0   2020-03-06 [1] CRAN (R 3.6.3)
#>  lubridate     1.7.4   2018-04-11 [1] CRAN (R 3.6.1)
#>  magrittr      1.5     2014-11-22 [1] CRAN (R 3.6.1)
#>  memoise       1.1.0   2017-04-21 [1] CRAN (R 3.6.1)
#>  modelr        0.1.6   2020-02-22 [1] CRAN (R 3.6.2)
#>  munsell       0.5.0   2018-06-12 [1] CRAN (R 3.6.1)
#>  nlme          3.1-144 2020-02-06 [2] CRAN (R 3.6.3)
#>  pillar        1.4.3   2019-12-20 [1] CRAN (R 3.6.2)
#>  pkgbuild      1.0.6   2019-10-09 [1] CRAN (R 3.6.1)
#>  pkgconfig     2.0.3   2019-09-22 [1] CRAN (R 3.6.1)
#>  pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.6.1)
#>  prettyunits   1.1.1   2020-01-24 [1] CRAN (R 3.6.2)
#>  processx      3.4.2   2020-02-09 [1] CRAN (R 3.6.2)
#>  ps            1.3.2   2020-02-13 [1] CRAN (R 3.6.2)
#>  purrr       * 0.3.3   2019-10-18 [1] CRAN (R 3.6.1)
#>  R6            2.4.1   2019-11-12 [1] CRAN (R 3.6.1)
#>  Rcpp          1.0.3   2019-11-08 [1] CRAN (R 3.6.3)
#>  readr       * 1.3.1   2018-12-21 [1] CRAN (R 3.6.1)
#>  readxl        1.3.1   2019-03-13 [1] CRAN (R 3.6.1)
#>  remotes       2.1.1   2020-02-15 [1] CRAN (R 3.6.2)
#>  reprex        0.3.0   2019-05-16 [1] CRAN (R 3.6.1)
#>  rlang         0.4.5   2020-03-01 [1] CRAN (R 3.6.3)
#>  rmarkdown     2.1     2020-01-20 [1] CRAN (R 3.6.2)
#>  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.6.1)
#>  rvest         0.3.5   2019-11-08 [1] CRAN (R 3.6.1)
#>  scales        1.1.0   2019-11-18 [1] CRAN (R 3.6.1)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.6.1)
#>  stringi       1.4.6   2020-02-17 [1] CRAN (R 3.6.2)
#>  stringr     * 1.4.0   2019-02-10 [1] CRAN (R 3.6.1)
#>  testthat      2.3.2   2020-03-02 [1] CRAN (R 3.6.3)
#>  tibble      * 2.1.3   2019-06-06 [1] CRAN (R 3.6.3)
#>  tidyr       * 1.0.2   2020-01-24 [1] CRAN (R 3.6.2)
#>  tidyselect    1.0.0   2020-01-27 [1] CRAN (R 3.6.2)
#>  tidyverse   * 1.3.0   2019-11-21 [1] CRAN (R 3.6.1)
#>  usethis       1.5.1   2019-07-04 [1] CRAN (R 3.6.1)
#>  utf8          1.1.4   2018-05-24 [1] CRAN (R 3.6.1)
#>  vctrs         0.2.4   2020-03-10 [1] CRAN (R 3.6.3)
#>  withr         2.1.2   2018-03-15 [1] CRAN (R 3.6.1)
#>  xfun          0.12    2020-01-13 [1] CRAN (R 3.6.2)
#>  xml2          1.2.5   2020-03-11 [1] CRAN (R 3.6.3)
#>  yaml          2.2.1   2020-02-01 [1] CRAN (R 3.6.2)
#> 
#> [1] C:/Users/mail/Documents/R/win-library/3.6
#> [2] C:/Program Files/R/R-3.6.3/library
```

</details>

<sup>Created on 2020-03-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by hadley** [comment] 2020-03-25 12:11
Minimal reprex:

``` r
library(dplyr, warn.conflicts = FALSE)
df <- structure(tibble(x = 1), n = 1)
bind_rows(df)
#> Error in (function (x = list(), n = NULL, ..., class = NULL) : formal argument "n" matched by multiple actual arguments
```

<sup>Created on 2020-03-25 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

With backtrace

```
    █
 1. └─dplyr::bind_rows(df)
 2.   ├─dplyr::dplyr_reconstruct(out, first) R/bind.r:122:4
 3.   └─dplyr:::dplyr_reconstruct.data.frame(out, first) R/generics.R:156:2
 4.     └─rlang::exec(...) R/generics.R:173:2
```

@DavisVaughan @lionel- the root cause of this problem is that `new_data_frame()` has an `n` argument so you can't set an `n` attribute

**Comment by DavisVaughan** [comment] 2020-03-25 12:58
In retrospect it should probably be

```
new_data_frame(.x = list(), .size = NULL, ..., .class = NULL)
```

**Comment by DavisVaughan** [comment] 2020-03-25 13:01
Closed in favor of https://github.com/r-lib/vctrs/issues/949

**Closed by DavisVaughan** 2020-03-25 13:01 UTC
