### ISSUE TITLE
Update dplyr vignette to include `{{ }}` syntax

### ISSUE THREAD

**Issue by batpigandme** [tidyverse/dplyr#4549] opened 2019-09-02 12:17 UTC
Related community discussion here (but not terribly relevant)
https://community.rstudio.com/t/documentation-for/38727

**Comment by hadley** [comment] 2019-12-10 22:32
Really probably needs to be re-written from scratch.

**Comment by hadley** [comment] 2019-12-10 22:55
Now duplicate of #4407

**Closed by hadley** 2019-12-10 22:55 UTC
Labels: documentation
