### ISSUE TITLE
New `cbind` method breaks some existing code

### ISSUE THREAD

**Issue by NikNakk** [tidyverse/dplyr#2671] opened 2017-04-16 18:12 UTC
In `dplyr` prior to version 0.6, `cbind` on two `tbl_df`s uses the base R `cbind.data.frame` which in turn calls `data.frame`. This causes some unexpected behaviour (#2475 for example). The fix, as committed [here](https://github.com/tidyverse/dplyr/commit/4e569f57fa98f37f84f4ad256a1c382ee4e8b81f) was to create a new method for `cbind` which in effect makes it an alias for `bind_cols`. For the most part, this seems like a good move. However, it means that existing code which binds together a 1 row `tbl_df` with a >1 row `tbl_df` will now fail.

The error message in this case (`Error in cbind_all(x) : Argument 2: size must be 1, not 3`) is also not as clear as it could be.

```r
library(dplyr)
a <- data_frame(x = LETTERS[1:3])
b <- data_frame(y = "potato")
cbind(a, b)
#Error in cbind_all(x) : Argument 2: size must be 1, not 3
#Works in `dplyr` 0.5, but returns a plain `data.frame`
```

Options would include:

- Make explicit mention of this in the release notes. (I know that the new `cbind` method is mentioned, but it wasn't clear to me that this is a potential issue for existing code and dependent packages.
- Improve the error message to make it clearer what the issue is here.
- Change `bind_cols` to handle the specific case of `tbl_df`s with exactly one row (analogous to the way `mutate` needs a vector either of length `nrow(df)` or `1L`.

**Comment by lionel-** [comment] 2017-04-17 08:37
duplicate of #2667

**Closed by lionel-** 2017-04-17 08:37 UTC
