### ISSUE TITLE
dplyr 0.7.0: Wrong results when cooperating with `lubridate`

### ISSUE THREAD

**Issue by sammo3182** [tidyverse/dplyr#2856] opened 2017-06-13 09:57 UTC
I used the `mutate` function to calculate the week number in two steps. If I tried that in one command line:
```r
library(dplyr);library(lubridate)

start <- ymd("2017-08-21")
end <- ymd("2017-12-17")

datesW <- data.frame(day = seq(from = start, to = end, by = "days")) %>%
  mutate(weekNum = week(day), weekNum = weekNum - (min(weekNum) - 1)) 
```
the command did not produce what I expected:
```r
> unique(datesW$weekNum)
 [1] 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50
[17] 51 52
```

If I did the same thing in two steps, the function worked fine:
```r
datesR <- data.frame(day = seq(from = start, to = end, by = "days")) %>%
  mutate(weekNum = week(day)) %>% 
  mutate(weekNum = weekNum - (min(weekNum) - 1))

unique(datesR$weekNum)
```
I got what I wanted:
```r
> unique(datesR$weekNum)
 [1]  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16
[17] 17 18
```

Before `0.6.0`, the above two commands produced identical results.

**Comment by hadley** [comment] 2017-06-13 13:59
@krlmlr is this related to #2842?

**Comment by hadley** [comment] 2017-06-13 14:00
@sammo3182 Thanks for providing some code that illustrates the problem — it's a great start 😄 However, your reprex could be simpler - can you reduce the number of rows of data needed to illustrate the problem? The goal should be to create a reprex that's sufficiently obvious that you don't also need to calculate the correct values. Can you please also use the reprex package to create the reprex?

**Comment by krlmlr** [comment] 2017-06-13 21:20
Yes, it's most likely a duplicate of #2842. Will fix tomorrow.

**Closed** 2017-06-15 14:32 UTC
Labels: reprex
