### ISSUE TITLE
mutate(across(x, lst(fn)) isn't able to access other columns

### ISSUE THREAD

**Issue by ArthurAndrews** [tidyverse/dplyr#6748] opened 2023-02-21 15:57 UTC
I think this is a bug introduced in a recent update because it's breaking code I wrote a few months ago.

For this workflow:  `mutate(across(x, lst(fn))`, it seems that `fn` isn't able to access other dataframe columns.  It produces an error `object 'y' not found` where `y` is another dataframe column.

`across` works as intended by using `list` instead of `lst`.

Here is a minimal example.  I hope this is useful.

``` r
library(dplyr)
#> Warning: package 'dplyr' was built under R version 4.2.2
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union

packageVersion("dplyr")
#> [1] '1.1.0'

df <- data.frame(x = 1, y = 2)

# ok.  I think this was fixed here: https://github.com/tidyverse/dplyr/issues/5924
df %>% 
  mutate(across(x, lst(f1 = ~. + 1)))
#>   x y x_f1
#> 1 1 2    2

# fails
df %>% 
  mutate(across(x, lst(f2 = ~y + . + 1)))
#> Error in `mutate()`:
#> ℹ In argument: `across(x, lst(f2 = ~y + . + 1))`.
#> Caused by error in `across()`:
#> ! Can't compute column `x_f2`.
#> Caused by error:
#> ! object 'y' not found

#> Backtrace:
#>      ▆
#>   1. ├─df %>% mutate(across(x, lst(f2 = ~y + . + 1)))
#>   2. ├─dplyr::mutate(., across(x, lst(f2 = ~y + . + 1)))
#>   3. ├─dplyr:::mutate.data.frame(., across(x, lst(f2 = ~y + . + 1)))
#>   4. │ └─dplyr:::mutate_cols(.data, dplyr_quosures(...), by)
#>   5. │   ├─base::withCallingHandlers(...)
#>   6. │   └─dplyr:::mutate_col(dots[[i]], data, mask, new_columns)
#>   7. │     ├─base::withCallingHandlers(...)
#>   8. │     └─mask$eval_all_mutate(quo)
#>   9. │       └─dplyr (local) eval()
#>  10. ├─dplyr (local) `<rlng_lm_>`(x)
#>  11. └─base::.handleSimpleError(`<fn>`, "object 'y' not found", base::quote(`<rlng_lm_>`(x)))
#>  12.   └─dplyr (local) h(simpleError(msg, call))
#>  13.     └─rlang::abort(msg, call = call("across"), parent = cnd)

# ok
df %>% 
  mutate(across(x, list(f2 = ~y + . + 1)))
#>   x y x_f2
#> 1 1 2    4
```

<sup>Created on 2023-02-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by DavisVaughan** [comment] 2023-02-22 22:38
@lionel- would you mind weighing in here?

Minimal reprex

``` r
library(dplyr, warn.conflicts = FALSE)

df <- tibble(x = 1, y = 2)

df %>% 
  mutate(across(x, lst(f2 = ~y + . + 1)))
#> Error in `mutate()`:
#> ℹ In argument: `across(x, lst(f2 = ~y + . + 1))`.
#> Caused by error in `across()`:
#> ! Can't compute column `x_f2`.
#> Caused by error:
#> ! object 'y' not found

df %>% 
  mutate(across(x, list(f2 = ~y + . + 1)))
#> # A tibble: 1 × 3
#>       x     y  x_f2
#>   <dbl> <dbl> <dbl>
#> 1     1     2     4
```

I think the problem is that `lst()` captures the `...` and evaluates them in a special data mask, which gives the formulas themselves a special child environment:

```r
# has an env attached to the formula
lst(f2 = ~y + . + 1)
#> $f2
#> ~y + . + 1
#> <environment: 0x7fc525217110>

# env on the formulas is the global env
list(f2 = ~y + . + 1)
#> $f2
#> ~y + . + 1
```

So when we eventually evaluate this `.fns` quosure here
https://github.com/tidyverse/dplyr/blob/68ae92276031c6aeb009d6c02198979c19fc8865/R/across.R#L912-L915

the `sentinel_env` will always be different from the env that `lst()` evaluates the formula in (since it creates a data mask to evaluate it in). Meaning we don't ever alter the formula environment here to ensure it can access columns
https://github.com/tidyverse/dplyr/blob/68ae92276031c6aeb009d6c02198979c19fc8865/R/across.R#L918-L938

I'm not sure we can do much about this one?

**Comment by lionel-** [comment] 2023-02-23 13:43
I think you're right, that's going to be a limitation of `across()` because of the contradictory semantics of expansion and evaluation.

**Comment by DavisVaughan** [comment] 2023-02-23 17:56
Alright, we will close this for now and I'll keep it in mind if something similar comes back up again

**Closed by DavisVaughan** 2023-02-23 17:56 UTC
