### ISSUE TITLE
cummean() function

### ISSUE THREAD

**Issue by wilson0106** [tidyverse/dplyr#5436] opened 2020-07-25 15:00 UTC
The function cummean() doesn't work as explained in the book R for data Science of Hadley Wickham and Garrett Grolemund

```r
(x <- 1:10)

x
[1]  1  2  3  4  5  6  7  8  9 10

cummean(x)
 [1] 1.000000 1.000000 1.333333 1.750000 2.200000 2.666667 3.142857 3.625000 4.111111 4.600000

```

**Comment by hadley** [comment] 2020-07-26 16:02
Duplicate of #5325

**Closed by hadley** 2020-07-26 16:02 UTC
