### ISSUE TITLE
not exact wrap of vars results

### ISSUE THREAD

**Issue by earthcli** [tidyverse/dplyr#3025] opened 2017-08-15 10:28 UTC
I have found a potential problem which may cause unexpect results.

x="yy"
mutate_at(data.frame(xx=1:5, yy=3),vars(x),funs(.*3))
mutate_at(data.frame(x=1:5, yy=3),vars(x),funs(.*3))

If I passed a string x="yy" to vars, and there is also a column named "x", the result of vars will be "x" rather than "yy", so how can i ensure the x passed to vars is a string variable? this may cause error some times!

**Comment by lionel-** [comment] 2017-08-15 10:33
Duplicate of https://github.com/tidyverse/dplyr/issues/2904

Just pass the vector directly:

```r
mutate_at(data.frame(x = 1:5, yy = 3), x, funs(.*3))
```

In the next version, variables passed to `vars()` will have to refer to data frame variables, never to the context. This will avoid this sort of confusion.

**Closed by lionel-** 2017-08-15 10:33 UTC
